- openapi.yaml
Add Open API v3 specification
- add _openapi.yaml_ in root directory
Describe all the functionalities that will be exposed.
> [#IOPAE-268] Add Open API specification

- .github/workflows/code-review.yaml
- .github/workflows/label.yaml
- .github/workflows/release.yaml
See commit list
Use commit sha instead of version tags to defend against malicious retagging.
> [IOPAE-293] Pin actions version to commit sha

- apps/io-services-cms-webapp/src/__tests__/jira_client.test.ts
- apps/io-services-cms-webapp/src/config.ts
- apps/io-services-cms-webapp/src/jira_client.ts
Add Search method and config refactor
> [#IOPAE-295] JiraClient searchJiraIssues

- packages/io-services-cms-models/package.json
Small fix to allow cross build
> Declare export packages

- .github/workflows/azure-deploy.yaml
- .github/workflows/release.yaml
- .identity/03_github_environment_runner.tf
- .identity/99_locals.tf
- .identity/99_variables.tf
- .identity/env/prod/backend.tfvars
- .identity/env/prod/terraform.tfvars
> [IOPAE-300] Setup CD

- .changeset/strong-bugs-vanish.md
- apps/io-services-cms-webapp/package.json
- apps/io-services-cms-webapp/src/webservice/controllers/info.ts
* include right files in the package bundle
* bundle dependencies
* avoid reading from `package.json` (a re-configuration of typescript it's needed)
> Fix webapp package script

- .github/workflows/infra-static-analysis.yaml
- README.md
- docs/terraform-development.md
See commit list
Improve infrastructure development experience by adding a check on PRs that involves terraform code
> Add infrastructure checks on CI

- .changeset/clever-maps-refuse.md
- apps/io-services-cms-webapp/src/pg-client.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
- apps/io-services-cms-webapp/tsconfig.json
> Use `esModuleInterop`

- apps/io-services-cms-webapp/README.md
add db migration docs
update app README with add db migration docs
to share how to execute a db migration using our custom scripts
> docs: add db migration docs

- apps/io-services-cms-webapp/src/_to-solve.ts
- apps/io-services-cms-webapp/src/lib/clients/__tests__/apim-client.test.ts
- apps/io-services-cms-webapp/src/lib/clients/__tests__/jira-client.test.ts
- apps/io-services-cms-webapp/src/lib/clients/apim-client.ts
- apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
- apps/io-services-cms-webapp/src/lib/clients/pg-client.ts
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/request-review-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/request-review-handler.ts
- apps/io-services-cms-webapp/src/utils/__tests__/jira-proxy.test.ts
- apps/io-services-cms-webapp/src/utils/apim-proxy.ts
- apps/io-services-cms-webapp/src/utils/jira-proxy.ts
- apps/io-services-cms-webapp/src/utils/service-review-dao.ts
- apps/io-services-cms-webapp/src/webservice/__tests__/index.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/create-service/index.ts
Project renaming with `kebab-case` convenction.
> [IOPAE-311] kebab-case renaming

- .changeset/violet-walls-yawn.md
- apps/io-services-cms-webapp/src/lib/clients/__tests__/jira-client.test.ts
- apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/request-review-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/review-checker-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/review-checker-handler.ts
- apps/io-services-cms-webapp/src/utils/__tests__/jira-proxy.test.ts
**Add service review checker handler.**
From the list of pending items _(stored on postgreSQL db)_, fetch the related issue list on ticket management system _(Jira)_.
For each issue in status APPROVED or REJECTED, it updates the `serviceLifecycleStore` and the related pending item on _"pending reviews"_ db.
- Add `review-checker-handler` and related unit tests
- Add minor `JiraIssue` type update _(statuscategorychangedate)_
Unit Tests
> [#IOPAE-288] Service Review Checker handler

- .changeset/empty-toys-wave.md
- packages/io-services-cms-models/README.md
- packages/io-services-cms-models/src/index.ts
- packages/io-services-cms-models/src/service-lifecycle/index.ts
- packages/io-services-cms-models/src/service-publication/__tests__/index.test.ts
- packages/io-services-cms-models/src/service-publication/index.ts
* Define the FSM and implement it
* Define common types for FMS
Implements a finite state machine to handle the publication of a service as described in the following diagram:
```mermaid
stateDiagram-v2
* --> unpublished: override
unpublished --> unpublished: override
published --> published: override
unpublished --> published: publish
published --> unpublished: unpublish
```
See [README](https://github.com/pagopa/io-services-cms/blob/IOPAE-256--fsm-service-publication/packages/io-services-cms-models/README.md) for further documentation.
With a local store.
> [IOPAE-256] Service Publication FSM

- .changeset/sixty-camels-dance.md
- apps/io-services-cms-webapp/ServiceLifecycleWatcher/function.json
- apps/io-services-cms-webapp/env.example
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/watchers/__tests__/on-services-lifecycles-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-services-lifecycles-change.ts
- infra/src/webapp.tf
- packages/io-services-cms-models/src/index.ts
- packages/io-services-cms-models/src/queue/index.ts
add a handler to create all "actions" to be applied to each "changed" item.
- implement a new common type RequestReviewItem into packeges/model
- implement "single item" handler
- implement unit tests
This change is required in order to manage (actually, to properly dispatch) every ServiceLifecycle changes
unit tests
> feat: [IOPAE-312] add on service lifecycle change handler

- .changeset/clean-poems-scream.md
- apps/io-services-cms-webapp/src/webservice/__tests__/index.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/review-service/index.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
create review service controller
- create review service controller handler
- bind review service handler to its route
- add unit test
to allow a service submission via API
unit tests
> feat: [IOPAE-325] create review service controller

- .changeset/lovely-pens-kick.md
- apps/io-services-cms-webapp/src/reviewer/review-checker-handler.ts
> Fix broken entrypoint

- apps/io-services-cms-webapp/ReviewService/function.json
> bugfix: [IOPAE-325] add review service fn

- .changeset/ninety-doors-wonder.md
- apps/io-services-cms-webapp/ServiceLifecycleWatcher/function.json
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/utils/jira-proxy.ts
- infra/src/webapp.tf
- openapi.yaml
- packages/io-services-cms-models/src/lib/fsm/store.cosmos.ts
fix webapp config and startup errors
- fix queue connection string placeholder
- fix open api docs
- use partition key when fetch a single item using cosmos client
manually, by running webapp locally
> bugfix: fix errors when running app

- .changeset/swift-snails-buy.md
- apps/io-services-cms-webapp/package.json
- apps/io-services-cms-webapp/src/webservice/controllers/create-service/converters.ts
- apps/io-services-cms-webapp/src/webservice/controllers/create-service/index.ts
- openapi.yaml
Update OpenApi Service model:
- remove `visibility` property
- define 2 different models for `status` property based on api type:
- **ServiceLifecycleStatus** for `GET /services/{serviceId}` _(and all Lifecycle related APIs)_
- **ServicePublicationStatus** for `GET /services/{serviceId}/release` _(and all Publication related APIs)_
- update code import for new/renamed models
> [IOPAE-328] Update OpenApi Service status

- apps/io-services-cms-webapp/DeleteService/function.json
- apps/io-services-cms-webapp/src/webservice/__tests__/index.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/delete-service/index.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
Add Delete Service Endpoint _(**DELETE** /services/:serviceId)_
- Added Azure `function.json`
- Added _Delete Service Controller_
- Added unit tests for _DELETE /services/:serviceId_
Unit Tests
> [#IOPAE-246] Delete Service API

- .changeset/yellow-seals-join.md
- apps/io-services-cms-webapp/src/config.ts
- apps/io-services-cms-webapp/src/lib/clients/pg-client.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/review-checker-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/review-checker-handler.ts
- apps/io-services-cms-webapp/src/utils/service-review-dao.ts
fix pending review error on updating status and fix Pending Review Checker error management in order to properly manage "Business Error" and "Transient Error"
- add updateStatus fn to service-review-dao
- add error mgmt to pending-review-checker
fix error in order to complete a "request review" process and properly manage errors
Unit test
> fix: update pending review error mgmt

- apps/io-services-cms-webapp/src/reviewer/__tests__/review-checker-handler.test.ts
- apps/io-services-cms-webapp/src/utils/__tests__/jira-proxy.test.ts
Fix some test missing mock and type
- added recently added getPendingJiraIssueByServiceId method on mainMockJiraProxy for review_checker_handler.test.ts
- add explicit type JiraIssueStatus[] to const searchStatuses on jira-proxy.test.ts
Unit test
> [FIX] Test review checker handler

- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/publicator/request-publication-handler.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/review-checker-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/review-checker-handler.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__test__/create-service.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__test__/delete-service.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__test__/edit-service.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__test__/get-service-lifecycle.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__test__/get-service-publication.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__test__/publish-service.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__test__/review-service.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__test__/unpublish-service.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/create-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/delete-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/edit-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-lifecycle.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-publication.ts
- apps/io-services-cms-webapp/src/webservice/controllers/publish-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/review-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/unpublish-service.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
- packages/io-services-cms-models/src/lib/fsm/store.memory.ts
- packages/io-services-cms-models/src/service-lifecycle/__tests__/index.test.ts
- packages/io-services-cms-models/src/service-lifecycle/index.ts
- packages/io-services-cms-models/src/service-publication/__tests__/index.test.ts
- packages/io-services-cms-models/src/service-publication/index.ts
Refactor FSM exported actions (`apply` overloaded functions) in order to export a FSM client (an object containing each applicable action as attributes). 
FSM apply functions (and "cascading" files)
The main goal of is to facilitate the writing of unit tests (we can easily mock this client object) and also to provide an homogeneus way to call these "utilities" as "clients objects"
Unit Tests
> refactor: [IOPAE-339] refactor fsm actions

- .github/workflows/azure-deploy.yaml
- .identity/01_data.tf
- .identity/02_application_environment_app_cd.tf
- .identity/03_github_environment_app_cd.tf
- .identity/99_locals.tf
- .identity/99_variables.tf
- .identity/env/prod/terraform.tfvars
> Add ci cd app

- README.md
> Add infra status badge

- .changeset/five-frogs-mate.md
> Test CD pipeline

- .github/workflows/release.yaml
> fix trigger release pipeline

- .changeset/great-timers-vanish.md
- .github/workflows/azure-deploy.yaml
> Fix cd action

- .changeset/afraid-houses-approve.md
- .github/workflows/release.yaml
> Fix release action

- .changeset/eight-planets-remain.md
- .github/workflows/release.yaml
> Fix release action 2

- .changeset/selfish-students-tell.md
- .github/workflows/release.yaml
> Fix release action 3

- .identity/03_github_environment_app_cd.tf
- .identity/99_variables.tf
- .identity/env/prod/terraform.tfvars
> fix permissions

- .changeset/tame-weeks-provide.md
- .github/workflows/azure-deploy.yaml
> Restore azure deploy action

- infra/src/README.md
- infra/src/_shared_vnet.tf
- infra/src/webapp.tf
> add runner subnet to fn allowed list

- infra/src/env/prod/terraform.tfvars
> fix: Update app service plan to P1v3

- infra/src/README.md
- infra/src/database_cms.tf
> fix cosmos config

- infra/src/README.md
- infra/src/database_cms.tf
- infra/src/database_review.tf
- infra/src/key_vault.tf
- infra/src/network.tf
- infra/src/storage_account.tf
- infra/src/webapp.tf
fix this error https://github.com/pagopa/terraform-azurerm-v3/pull/141
> Fix function app worker count

- openapi.yaml
Update **GET Services** openapi query params:
- change `limit` to optional, update description and define range values _(1-100)_ and default value _(20)_
- update `offset` description and define minimum and default value _(0)_
> [#IOPAE-350] Update GET Services openapi query params

- apps/io-services-cms-webapp/README.md
- apps/io-services-cms-webapp/src/reviewer/schema/migrations/reviewer/U1__drop_user_app.sql
- apps/io-services-cms-webapp/src/reviewer/schema/migrations/reviewer/U2__drop_schema.sql
- apps/io-services-cms-webapp/src/reviewer/schema/migrations/reviewer/U3__drop_service_review_table.sql
Improve Postgres migration documentation
- READEME
- removed incorrect UNDOs script files
To improve documentations
> docs: Fix flyway migration

- openapi.yaml
Update `openapi.yaml` specification removing _**Upload Organization Logo API**_.
This removed API will not be developed in this system.
> [#IOPAE-379] OpenApi: remove Upload Organization Logo API definition

- openapi.yaml
Update `openapi.yaml` specification for _**Service Authorization API specification**_.
- add new **GET** `/services/{serviceId}/keys` for retrieving service keys
- update **PUT** `/services/{serviceId}/keys/{keyType} `for regenerating service key
> [#IOPAE-389] OpenApi: update service keys definitions

- openapi.yaml
We removed the placeholder header parameter `X-CUSTOM-KEY` and replace it with the 4 header parameter valued by apim when a function is invoked on `openapi.yaml`.
- Remove `X-CUSTOM-KEY` in openApi and all Api in which was set
- Added and linked, to the api which requires them, the following header parameters: `x-user-email`, `x-user-groups`, `x-user-id` and `x-subscription-id` in `openapi.yaml`.
> [#IOPAE-365] Edit openApi header parameters

- .changeset/yellow-ways-kneel.md
- apps/io-services-cms-webapp/GetServiceKeys/function.json
- apps/io-services-cms-webapp/src/webservice/controllers/__test__/get-service-keys.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-keys.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
Add new API for retrieve service keys.
- Added new GetServiceKeys AZ Function and handler
- Added related unit tests
We need to retrieve security keys for a given service.
Unit tests
> [#IOPAE-378] API Get service keys

- infra/src/README.md
- infra/src/storage_account.tf
- infra/src/webapp.tf
Add a queue to manage sync request from legacy to cms
- add request-sync-cms queue
- add request-sync-cms queue name ENV VAR
This queue is required to store the "commands" in order to keep updated services from legacy to cms system
> feat: [IOPAE-395] add request-sync-cms queue

- README.md
> [#TIBA-1] Just an automation test

- README.md
> [#TIBA-1] last automation test

- .changeset/mighty-bats-compare.md
- apps/io-services-cms-webapp/src/historicizer/__tests__/request-historicization-handler.test.ts
- apps/io-services-cms-webapp/src/publicator/__test__/request-publication-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/request-review-handler.test.ts
- apps/io-services-cms-webapp/src/utils/converters/service-lifecycle-converters.ts
- apps/io-services-cms-webapp/src/utils/converters/service-publication-converters.ts
- openapi.yaml
- packages/io-services-cms-models/src/service-lifecycle/__tests__/index.test.ts
- packages/io-services-cms-models/src/service-lifecycle/definitions.ts
Added `authorized_cidrs` property to **Service** 
- Add cidrs definition to open api
- Add `authorized_cidrs` property to service in open api
- Add `authorized_cidrs` to service model 
- Update converters
- Update unit tests
we need to have this information in services-cms
unit test
> [IOPAE-392] Add authorized_cidrs to service model

- .changeset/kind-foxes-explain.md
- apps/io-services-cms-webapp/ServiceLifecycleWatcher/function.json
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/watchers/__tests__/on-service-lifecycle-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-service-lifecycle-change.ts
add request historicization action to service-lifecycle change feed
- add requestHistoricization action to on-service-lifecycle-change handler
> chore: [IOPAE-396]  historicize service lifecycle changes

- infra/src/env/prod/terraform.tfvars
Update jira configuration
- set right JIRA-USERNAME
Local application run
> [#IOPAE-307] Update Jira configuration

- .changeset/gorgeous-colts-cheat.md
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/watchers/__tests__/on-legacy-service-change.test.ts
- apps/io-services-cms-webapp/src/watchers/__tests__/on-service-history-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts
- apps/io-services-cms-webapp/src/watchers/on-service-history-change.ts
- packages/io-services-cms-models/package.json
- packages/io-services-cms-models/src/service-legacy/index.ts
- yarn.lock
Add CMS to Legacy service mapping into _ServiceHistoryWatcher_.
- added mapping on _ServiceHistoryWatcher_
- updated _LegacyService_ models definition _(added @pagopa/io-functions-commons dependency in models)_
- updated _LegacyService_ imports on webapp
- unit tests
Unit Tests
> [#IOPAE-412] CMS to Legacy mapping

- infra/src/api/io_services_cms/v1/_swagger.yaml.tpl
Update openapi for cms services
- remove cmsExplainService operation (not implemented yet)
Making openapi definition cleaner
> chore: [IOPAE-406] remove cmsExplainService operation (not implemented yet)

- infra/src/webapp.tf
Fix CSM Services Azure Function configurations
- enable ServiceReviewChecker
- disable ServiceHistoryWatcher
Currently we aren't ready to "enable" sync and sync-back features, so we are disabling theirs functions
> fix: [IOPAE-417] fix-cms-services-app-configs

- apps/io-services-cms-webapp/host.json
Add extensionBundle in host.json accoring to https://github.com/Azure/azure-functions-extension-bundles
- add Microsoft.Azure.Functions.ExtensionBundle injection in host.json
> fix: add Microsoft.Azure.Functions.ExtensionBundle in host.json

- .changeset/breezy-monkeys-serve.md
- apps/io-services-cms-webapp/host.json
Add extensionBundle in host.json according to https://github.com/Azure/azure-functions-extension-bundles
- add Microsoft.Azure.Functions.ExtensionBundle injection in host.json
> fix: extension bundle

- infra/src/api/io_services_cms/v1/updateservicelogo_policy/policy.xml
_Add_
```
<set-header name="x-functions-key" exists-action="override">
<value>{{io-fn3-services-key}}</value>
</set-header>`
```
in upload service logo policy needed for correctly redirect to legacy _UploadServiceLogo_ API.
> [#IOPAE-418] Add io-fn3-services-key in upload service logo policy

- .changeset/serious-lobsters-sniff.md
- apps/io-services-cms-webapp/host.json
Change extension bundle version
- Microsoft.Azure.Functions.ExtensionBundle version to `[3.*, 4.0.0)`
> fix: change extensionBundle version

- infra/src/README.md
- infra/src/env/prod/terraform.tfvars
- infra/src/webapp.tf
change postgreSQL user
- change postgreSQL user in `webapp.tf`
> fix: added right postgreSQL user

- .changeset/sixty-poets-lick.md
- apps/io-services-cms-webapp/OnRequestSyncCms/function.json
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/synchronizer/__tests__/request-sync-cms-handler.test.ts
- apps/io-services-cms-webapp/src/synchronizer/request-sync-cms-handler.ts
- apps/io-services-cms-webapp/src/watchers/__tests__/on-legacy-service-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts
- infra/src/webapp.tf
- packages/io-services-cms-models/src/queue/index.ts
When handling a request to sync CSM, add sync legacy tag legacy and call FSM override
- add fn queue trigger
- add its handler
To keep in-sync CSM from Legacy changes
> feat: [IOPAE-384] sync CMS handling

- .changeset/cyan-steaks-reply.md
- apps/io-services-cms-webapp/OnRequestSyncLegacy/function.json
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/synchronizer/__tests__/request-sync-legacy-handler.test.ts
- apps/io-services-cms-webapp/src/synchronizer/request-sync-cms-handler.ts
- apps/io-services-cms-webapp/src/synchronizer/request-sync-legacy-handler.ts
- apps/io-services-cms-webapp/src/watchers/on-service-history-change.ts
- infra/src/webapp.tf
Add OnRequestSyncLegacy Azure Function
Add OnRequestSyncLegacy Azure Function:
- definition
- entry point
- handler
Add this function to dequeue sync request from CSM to Legacy and to "upsert" legacy services database
Unit tests
> feat: [IOPAE-430] request sync legacy handler

- .changeset/twelve-laws-wink.md
- apps/io-services-cms-webapp/src/synchronizer/__tests__/request-sync-cms-handler.test.ts
- apps/io-services-cms-webapp/src/synchronizer/request-sync-cms-handler.ts
- apps/io-services-cms-webapp/src/utils/synchronizer.ts
- apps/io-services-cms-webapp/src/watchers/__tests__/on-service-history-change.test.ts
- apps/io-services-cms-webapp/src/watchers/__tests__/on-service-lifecycle-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-service-history-change.ts
- apps/io-services-cms-webapp/src/watchers/on-service-lifecycle-change.ts
refactor: move from Legacy label into a shared utility
- create `sincronizer.ts` utils file
- move "from legacy" tag inside it
refactor/clean code
unit test
> refactor: move from Legacy label into a shared utility

- infra/src/webapp.tf
Enable Service History Watcher
- `"AzureWebJobs.ServiceHistoryWatcher.Disabled"     =  "0"`
> [#IOPAE-434] Enable service history watcher

- .changeset/afraid-yaks-yell.md
- apps/io-services-cms-webapp/LegacyServiceWatcher/function.json
- apps/io-services-cms-webapp/ServiceHistoryWatcher/function.json
- infra/src/webapp.tf
History Service Watcher set `startFromBeginning` to `false`
> [#IOPAE-434] History service watcher start beginning

- .changeset/cold-moose-applaud.md
- apps/io-services-cms-webapp/src/synchronizer/request-sync-cms-handler.ts
Use RA.filter instead of standard filtering
> chore: code cleanUp Request Legacy Sync

- .changeset/healthy-monkeys-yell.md
- apps/io-services-cms-webapp/src/watchers/__tests__/on-legacy-service-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts
Map legacy not visible service to unpublished CMS service
Unit Test
> fix: [BUG] [#IOPAE-475] fix sync legacy cms unpublish

- .changeset/fifty-crabs-lick.md
- apps/io-services-cms-webapp/src/lib/clients/jira-legacy-client.ts
git push --set-upstream origin IOPAE-478-fix_status_name_jira_legacy_not_recognized
Map `Completata` status.name for Jira Legacy Status name
> fix: [#IOPAE-478] Status name jira legacy not recognized

- .changeset/new-turtles-perform.md
- apps/io-services-cms-webapp/src/watchers/__tests__/on-legacy-service-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts
Wrap error adding information about the processed serviceId in `legacy-service-watcher` in order to identify who caused the error.
Unit Test
> refactor: chore: wrap error adding information about the processed serviceId

- .changeset/brave-bags-share.md
- apps/io-services-cms-webapp/LegacyServiceWatcher/function.json
- infra/src/env/prod/terraform.tfvars
- infra/src/webapp.tf
Configure infra and app to be ready to execute a controlled massive sync from legacy
See commits messages
To to execute a controlled massive sync from legacy
> chore: [IOPAE-458] preparation for controlled massive sync

- .changeset/cold-parrots-scream.md
- apps/io-services-cms-webapp/src/lib/clients/__tests__/jira-client.test.ts
- apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
- apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts
Add status on checkJiraResponse when an unknown status is received
Unit Test
> chore(fix): Log status response jira client

- .changeset/short-sheep-nail.md
- apps/io-services-cms-webapp/src/utils/feature-flag-handler.ts
Optimize Feature Flags evaluation.
Unit Tests
> chore(fix): Feature flag optimization

- .changeset/ten-lies-shop.md
- .github/workflows/azure-deploy.yaml
- .github/workflows/infra-cd.yml
- .github/workflows/infra-ci.yml
- .github/workflows/infra-drift-detection.yml
- infra/src/README.md
- infra/src/azuread.tf
> Update runner version

- .changeset/odd-buckets-brush.md
- apps/io-services-cms-webapp/LegacyServiceWatcher/function.json
- apps/io-services-cms-webapp/src/config.ts
- infra/src/99_variables.tf
- infra/src/README.md
- infra/src/env/prod/terraform.tfvars
- infra/src/webapp.tf
Add Max Items per invocation of LegacyServiceWatcher config.
To avoid Jira Throttling.
> chore(fix): Add max items per invocation on Legacy Service Watcher

- .changeset/real-candles-applaud.md
- apps/io-services-cms-webapp/src/config.ts
Fix type for config `LEGACY_SERVICE_WATCHER_MAX_ITEMS_PER_INVOCATION`
> chore(fix): type legacy max items

- .changeset/slow-peaches-thank.md
- apps/io-services-cms-webapp/src/config.ts
Fix type legacy service watcher max items per invocation
> Numberfromstring legacy max items

- .changeset/funny-donkeys-return.md
- apps/io-services-cms-webapp/src/main.ts
Legacy Service Watcher set `sequential process mode`.
> chore: Legacy service watcher sequential process

- .changeset/tough-pets-shave.md
- apps/io-services-cms-webapp/LegacyServiceWatcher/function.json
- apps/io-services-cms-webapp/src/lib/clients/__tests__/jira-legacy-client.test.ts
- apps/io-services-cms-webapp/src/lib/clients/jira-legacy-client.ts
Add retry on Legacy Service Watcher
> chore: Add retry on Legacy Service Watcher

- .changeset/real-keys-juggle.md
- apps/io-services-cms-webapp/LegacyServiceWatcher/function.json
- apps/io-services-cms-webapp/src/watchers/__tests__/on-legacy-service-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts
Optimization Jira REST Api call on Legacy Service Watcher
Unit test
> chore: Jira optimization on legacy service watcher

- infra/src/webapp.tf
- infra/src/webapp_monitor.tf
- Link `webapp_functions_app_health_check` to main `error_action_group`
This is required in order to forward alerts to main notification channels (email, slack and OpsGenie)
> Link Healthcheck alarm to main error action group

- apps/io-services-cms-webapp/src/config.ts
- infra/src/README.md
- infra/src/storage_account.tf
- infra/src/webapp.tf
> fix: [IOPAE-488] add request-review-legacy queue

- apps/io-services-cms-webapp/package.json
- packages/io-services-cms-models/package.json
- yarn.lock
Vitest configuration has been updated in order to have the code coverage of the unit tests.
To view coverage, run:
`yarn workspace io-services-cms-webapp coverage`
`yarn workspace @io-services-cms/models coverage`
- vitest packages updates
- add @vitest/coverage-v8 _(V8 coverage provider for Vitest)_
_Example result:_
> [#IOPAE-516] Vitest code coverage

- .changeset/tiny-badgers-shop.md
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/request-review-legacy-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/request-review-legacy-handler.ts
- apps/io-services-cms-webapp/src/utils/feature-flag-handler.ts
- packages/io-services-cms-models/src/queue/index.ts
Check apimUserId instead of serviceId on feature flag for request review legacy.
> [IOPAE-518] Optimization feature flag request review legacy

- infra/src/webapp.tf
> [#IOPLT-19] - Prepare APIM switch to v2

- .changeset/young-sheep-bow.md
- apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
Add `statuscategorychangedate` default value on `JiraIssue` io-ts type
> fix: ADD default value for statuscategorychangedate

- .github/workflows/opex_api_services_cms.yml
- .opex/api_services_cms/env/prod/config.yaml
> remove debug and update config on dashboard

- .changeset/unlucky-pianos-brake.md
- apps/backoffice/package.json
- yarn.lock
Update **mui-italia** to **1.0.0** version.
This upgrade affects a number of related packages, such as:
- @emotion/react: "^11.11.1
- @emotion/styled: "^11.11.0"
- @mui/icons-material: "^5.14.3"
- @mui/lab: "^5.0.0-alpha.140"
- @mui/material: "^5.14.5"
- @mui/system: "^5.14.5"
We take this opportunity to also update **next** and **i18n** packages to the latest version.
> [#IOPAE-522] Update mui-italia and related dependencies

- .github/workflows/azure-deploy.yaml
- .github/workflows/infra-cd.yml
- .github/workflows/infra-ci.yml
- .github/workflows/infra-drift-detection.yml
Update actions `Create Runner` and `Cleanup Runner` to use the one included in repo `eng-github-actions-iac-template` instead of repos `github-self-hosted-runner-azure-create-action` and `github-self-hosted-runner-azure-cleanup-action`
Updated github actions:
- `Create Runner` in order to use `eng-github-actions-iac-template/azure/github-self-hosted-runner-azure-create-action` instead of `github-self-hosted-runner-azure-create-action`
- `Cleanup Runner` in order to use `eng-github-actions-iac-template/azure/github-self-hosted-runner-azure-cleanup-action` instead of `github-self-hosted-runner-azure-cleanup-action`
- `Setup terraform` in order to use `eng-github-actions-iac-template/terraform/terraform-install-action` instead of `terraform-install-action`
- `Terraform pre apply` in order to …
> fix: Use github action from repo eng-github-actions-iac-template

- .changeset/hungry-cameras-itch.md
> chore: changeset

- .changeset/eight-items-drive.md
- apps/io-services-cms-webapp/src/watchers/__tests__/on-legacy-service-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts
On legacy service versions are not consecutive, so we have to recursively find it
> fix: Fetch previous version recursive

- .github/workflows/opex_api_services_cms.yml
- apps/io-services-cms-webapp/openapi.yaml
- apps/io-services-cms-webapp/package.json
- infra/src/api/io_services_cms/v1/_swagger.yaml.tpl
- openapi.yaml
- turbo.json
Move project root **openapi.yaml** to `io-services-cms/apps/io-services-cms-webapp/`.
Update **openapi.yaml** removing schemas definitions and referencing shared schemas in `io-services-cms/packages/io-services-cms-models/openapi/`.
**NOTE:**
_This refactor include the update of opex dashboard openapi path._
> [IOPAE-523] Refactor services cms openapi

- apps/io-services-cms-webapp/ServiceHistoryWatcher/function.json
- infra/src/env/prod/terraform.tfvars
- infra/src/webapp.tf
Enable `ServiceHistoryWatcher` AzureFunction
- set `startFromBeginning` true on ServiceHistoryWatcher `function.json`
- allow all user on ServiceHistoryWatcher by setting `USERID_CMS_TO_LEGACY_SYNC_INCLUSION_LIST` to `*`
- enable ServiceHistoryWatcher
> chore: Enable service history watcher

- .changeset/six-pumas-cover.md
- Set `startFromBeginning` on ServiceHistoryWatcher
> chore: Set startFromBeginning on ServiceHistoryWatcher

- .changeset/strange-fishes-act.md
- infra/src/webapp.tf
Enable `OnRequestSyncLegacy` Azure Function
> chore: Enable on request sync legacy

- apps/backoffice/openapi.yaml
- apps/io-services-cms-webapp/openapi.yaml
- packages/io-services-cms-models/openapi/commons-schemas.yaml
- packages/io-services-cms-models/openapi/services-cms-schemas.yaml
Further refactor of openapi **common-schemas** for future model reuses.
**Note:**
The code review goes wrong because the target pointing inserted for the generation of the models is the master branch on which the modifications of this PR will be pushed.
To test the correct functioning, the first commit 86ca944 contains the remote pointers to the current branch.
> [IOPAE-524] Refactor openapi schemas

- infra/src/webapp.tf
disable `OnRequestSyncLegacy` Azure function
> chore: disable OnRequestSyncLegacy

- .github/workflows/opex_api_services_cms.yml
- .opex/api_services_cms/env/prod/config.yaml
Change openapi Path in opex dashboard config file
> fix: Dashboard Fix 

- .github/workflows/opex_api_services_cms.yml
Removed debug line after dashboard fix
> Removed debug line after dashboard fix

- infra/src/99_variables.tf
- infra/src/README.md
- infra/src/env/prod/terraform.tfvars
- infra/src/webapp.tf
Added configuration to implement a mechanism for **automatic approval of submitted services** by certain PAs/technology partners, in order to avoid overloading L1 in manual reviews for such services.
- Added `USERID_AUTOMATIC_SERVICE_APPROVAL_INCLUSION_LIST` feature flag configuration
Some trusted PAs and relative Technological Partners, may massively create and submit for review new services, so in a short time interval we can receive thousands request for service approval, which will cause an excessive overload on L1 service reviews.
To Solve this we will implements an **automatic approval mechanism for submitted services** for such PAs and Technological Partners.
> [#IOPAE-535] Added Automatic Service Approval feature flag configuration

- .sonarcloud.properties
Add **mocks** folder in `.sonarcloud.properties` exclusions to avoid unwanted sonarcloud failures.
> chore: Add mocks folder to sonar exclusions

- .changeset/warm-berries-train.md
- apps/io-services-cms-webapp/src/reviewer/__tests__/review-checker-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/review-checker-handler.ts
- apps/io-services-cms-webapp/src/utils/service-review-dao.ts
The intent of this pr is to unify and improve application logs where they are unsatisfactory, by adding logs where missing and replacing `console` with `context.log` to have bettere log management in Azure Application Insight.
- Replace console with context log in `review-checker-handler`
- Add missing log in `review-checker-handler`
- update `review-checker-handler` unit tests
Unit Test
> [#IOPAE-436] Logging unification and improvements

- .changeset/fresh-beds-pay.md
- apps/backoffice/package.json
Add services CMS integration to Backoffice using an autogenerated rest client
- add services-cms rest client generatorion
Required to implement B4F APIs
No tests. The rest client generation library is widely used in many others PagoPA repos
> feat: [IOPAE-542] add services-cms rest client generation

- .changeset/eighty-weeks-remain.md
- apps/backoffice/src/components/empty-state/index.tsx
Add component used for empty page layout
> [#IOPAE-545] Empty state component

- .changeset/tasty-games-wink.md
- apps/backoffice/src/components/sidenav/index.tsx
- apps/backoffice/src/layouts/page-layout.tsx
- apps/backoffice/src/styles/globals.css
- target `background-color: #F5F5F5` for page content _(also remove unused nextjs global css boilerplate)_
- target menu icons for _Overview_ and _Services_ sections
`run dev` _(localhost)_
> chore: BackOffice target page background color and menu icons

- infra/src/00_monitor.tf
- infra/src/00_network.tf
- infra/src/99_variables.tf
- infra/src/README.md
- infra/src/apim_api.tf
- infra/src/apim_v2_api.tf
- infra/src/backoffice_webapp.tf
- infra/src/database_review.tf
- infra/src/database_review_credentials.tf
- infra/src/env/prod/terraform.tfvars
- infra/src/key_vault.tf
- infra/src/network.tf
- infra/src/storage_account.tf
- infra/src/webapp.tf
- infra/src/webapp_autoscale.tf
Add backoffice infra resources and refactor-move terraform variables
- add app service
- refactor: move all variables inside `99_variables.tf` file
- refactor: move all "io common" variables into a "single object" variable
- refactor: move all "subnets cidrs" variables into a "single object" variable
- refactor: move all "subnets" definitions inside `network.tf` file
To "serve" the new backoffice
> feat: [IOPAE-573] add backoffice infra resources

- infra/src/backoffice_webapp.tf
> fix node version to 18-lts

- .changeset/gentle-rings-suffer.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/headers/page-breadcrumbs.tsx
- apps/backoffice/src/components/headers/page-header.tsx
- apps/backoffice/src/components/headers/page-html-head-title.tsx
- apps/backoffice/src/components/sidenav/index.tsx
- apps/backoffice/src/layouts/app-layout.tsx
- apps/backoffice/src/layouts/page-layout.tsx
- apps/backoffice/src/pages/index.tsx
- apps/backoffice/src/pages/keys/index.tsx
- apps/backoffice/src/pages/services/[serviceId].tsx
- apps/backoffice/src/pages/services/[serviceId]/edit-service.tsx
- apps/backoffice/src/pages/services/index.tsx
- apps/backoffice/src/pages/services/new-service.tsx
Add some update on page header components, refactoring `<PageHeader/>` components and developing target `<PageBreadcrumbs/>`.
- Refactor PageHeader and use it in all pages
- Add PageBreadcrumbs target component
- Add pages title/descriptions locale translations _(IT, EN)_
https://github.com/pagopa/io-services-cms/assets/118166285/4c1562e4-57aa-48ea-b242-0139ecb29942
> [IOPAE-576] Update page header ux/ui

- .changeset/poor-hounds-hope.md
- apps/backoffice/src/components/cards/card-details.tsx
- apps/backoffice/src/components/cards/card-shortcut.tsx
- apps/backoffice/src/components/copy-to-clipboard/index.tsx
- apps/backoffice/src/components/loaders/loader-fullscreen.tsx
Fix the incorrect imports:
`import { useTranslation } from "react-i18next";`
with the correct one:
`import { useTranslation } from "next-i18next";`
> fix:[IOPAE-600] Fix useTranslation import

- apps/backoffice/package.json
- apps/backoffice/src/components/__tests__/access-control.test.tsx
- apps/backoffice/src/components/__tests__/setup.ts
- apps/backoffice/vitest.config.node.ts
- apps/backoffice/vitest.config.react.ts
- yarn.lock
Vitest lacks when it comes to front end testing , adding the jest dom library helps for unit tests on component
- add jest-dom library
- add setup files for jest-dom library
- updated vitest configuration
Simple example of what the library can help for
> [#IOPAE-604]Add jest-dom library

- apps/backoffice/mocks/handlers/backend-handlers.ts
Add Manage Keys APIs msw mocks
- ADD `GET /keys/manage` msw mock
- ADD `PUT /keys/manage/{keyType}` msw mock
> [#IOPAE-610] ADD Manage Keys API msw mocks

- apps/backoffice/src/components/sidenav/index.tsx
- apps/backoffice/src/hooks/use-screen-size.ts
- apps/backoffice/src/layouts/app-layout.tsx
Fully functional prototype of **Sidenav** menu component with dynamic width and opening/closing capability.
This development is aimed at greater BackOffice usability especially at low screen resolutions.
https://github.com/pagopa/io-services-cms/assets/118166285/5fdcbc89-9ec8-44b0-a30b-b668bed2ef58
> [IOPAE-617] BackOffice dynamic sidenav prototype

- apps/backoffice/openapi.yaml
- packages/io-services-cms-models/openapi/backoffice-schemas.yaml
Add Manage Keys Authorized CIDRs APIs definitions in `backoffice/openapi.yaml`
- ADD `GET /keys/manage/cidrs` definition in `backoffice/openapi.yaml`, this api will retrieve the Authorized CIDRs associated to the Manage Keys currently in use(which is located in auth JWT).
- ADD `PUT /keys/manage/cidrs` definition in `backoffice/openapi.yaml`, this api will update the Authorized CIDRs associated to the Manage Keys currently in use(which is located in auth JWT).
> [#IOPAE-621] Add GET, PUT /keys/manage/cidrs BO API openapi.yaml

- .changeset/young-lamps-appear.md
- .github/workflows/azure-deploy.yaml
- apps/backoffice/CHANGELOG.md
- apps/backoffice/package.json
- io-services-cms.code-workspace
- yarn.lock
It is required to change current CD action in order to manage new backoffice app deployment
- deploy action
- backoffice package name
> feat: [IOPAE-575] add backoffice cd action

- .changeset/big-pumas-sip.md
- .changeset/fuzzy-pillows-tap.md
- .changeset/hip-pianos-melt.md
- .changeset/honest-windows-juggle.md
- .changeset/spotty-baboons-lick.md
- .changeset/stale-pigs-mate.md
Package in monorepo for `backoffice` was changed from `@io-services-cms/backoffice` to `io-services-cms-backoffice`, in this PR we are alligning  all changeset not merged
> chore: changeset refinement after backoffice package change

- .changeset/chilly-lizards-explode.md
- .github/workflows/azure-deploy.yaml
add suffix on step id in order to have unique ids along steps
> fix: Duplicate id on azure_deploy Action

- infra/src/99_variables.tf
- infra/src/README.md
- infra/src/apim_api.tf
- infra/src/apim_v2_api.tf
- infra/src/backoffice_webapp.tf
- infra/src/env/prod/terraform.tfvars
- infra/src/key_vault.tf
- add a new key vault secret for backoffice session validation
- add `NEXTAUTH_URL` env var
- add `NEXTAUTH_SECRET` env var
- refactoring `backoffice_app. app_settings` var
> feat: add nextauth env vars

- infra/src/key_vault.tf
> fix: fix bo_auth_session_secret resource name

- .github/workflows/release.yaml
- apps/backoffice/.env
- apps/backoffice/.env.development
- apps/backoffice/.env.production
- apps/backoffice/.gitignore
Resolve a bug into CD GitHub action `release`
- fix `release` GH action
- add .env* to VCS
There is a bug in the CD GitHub action `release` that prevents the zip package from uploading
> fix: [IOPAE-575] fix cd action

- .changeset/little-shirts-build.md
- apps/io-services-cms-webapp/package.json
- yarn.lock
Update `openapi-codegen-ts` to version `^13.1.0` in `io-services-cms-webapp`
> chore:[#IOPAE-648] Update openapi-codegen-ts to version ^13.1.0 in io-services-cms-webapp

- infra/src/README.md
- infra/src/backoffice_webapp.tf
- infra/src/key_vault.tf
> fix: [IOPAE-575] add backoffice app service staging slot

- .changeset/nine-parrots-remember.md
- apps/backoffice/src/components/__tests__/access-control.test.tsx
- apps/backoffice/src/components/__tests__/sidenav.test.tsx
- apps/backoffice/src/components/access-control/index.tsx
- apps/backoffice/src/components/sidenav/index.tsx
- apps/backoffice/src/layouts/app-layout.tsx
- apps/backoffice/src/layouts/protected-layout.tsx
- apps/backoffice/src/pages/_app.tsx
- apps/backoffice/src/pages/index.tsx
- apps/backoffice/src/pages/keys/index.tsx
- apps/backoffice/src/types/auth.ts
- apps/backoffice/src/utils/__tests__/auth-util.test.ts
- apps/backoffice/src/utils/auth-util.ts
- apps/backoffice/vitest.config.react.ts
Added the concept of **Authorization** on the _BackOffice Frontend_ and in particular on _Components_ _(through the use of `<AccessControl/>`)_, on `<Sidenav/>` and on **Pages**.
The **authorization** concept is based on the `RequiredAuthorizations` type in which specify:
- the required role
- the required permissions
necessary to authorize and therefore view/access the information of a specific component or page.
**Note:** _Follow the commits history for a better understanding of developments._
After _authentication_ it's necessary to verify user's _authorizations_ to access/view certain content.
Unit tests, local Dev.
> [IOPAE-646] Frontend authorization level on Components, Sidenav, Page Routes

- .changeset/fuzzy-ties-ring.md
- apps/backoffice/package.json
- apps/backoffice/src/components/sidenav/index.tsx
- apps/backoffice/src/hooks/use-screen-size.ts
- apps/backoffice/src/providers/app.tsx
- yarn.lock
Update **NextJs** to version **13.5**
Minor packages updates.
**Note:** Fix some MUI imports. See [Build warnings with MUI - barrel_optimize #55663](https://github.com/vercel/next.js/issues/55663)
**Dependencies**
- update "eslint": "8.50.0"
- update "eslint-config-next": "^13.5.3"
- update "i18next": "^23.5.1"
- update "next": "^13.5.3"
- update "next-auth": "^4.23.2"
- update "next-i18next": "^14.0.3"
- update "react-hook-form": "^7.47.0"
- update "react-i18next": "^13.2.2"
**DevDependencies:**
- add "vite": "^4.4.9"
> [IOPAE-656] Update NextJs v.13.5 and other minor packages updates

- apps/backoffice/next.config.js
- apps/backoffice/package.json
- apps/backoffice/src/pages/mocks/token-exchange.tsx
> fix: [IOPAE-575] fix build package script

- infra/src/backoffice_webapp.tf
> fix: [IOPAE-575] add github runner snet to bo allowed snet

- .changeset/spotty-walls-matter.md
- apps/backoffice/package.json
- apps/backoffice/src/app/api/keys/manage/route.ts
- apps/backoffice/src/app/api/lib/__tests__/keys-manage.test.ts
- apps/backoffice/src/app/api/lib/apim-helper.ts
- apps/backoffice/src/app/api/lib/keys-manage.ts
- apps/backoffice/src/app/api/lib/keys.ts
- apps/backoffice/src/config/index.ts
- yarn.lock
ADD `GET /keys/manage` API implementation in Backoffice B4F
- ADD `GET /keys/manage` API route implementation
- ADD `GET /keys/manage` unit tests
- ADD `buildApimService`, an utility function to help and centralize building ApimService
Unit Test
> [#IOPAE-631] ADD Manage Keys API handler Implementation in Backoffice

- .changeset/metal-feet-arrive.md
- apps/backoffice/src/app/api/keys/manage/[keyType]/route.ts
- apps/backoffice/src/app/api/lib/__tests__/keys-manage.test.ts
- apps/backoffice/src/app/api/lib/keys-manage.ts
ADD `PUT /keys/manage` API implementation in Backoffice B4F
- ADD `PUT /keys/manage` API route implementation
- ADD `PUT /keys/manage` unit tests
> [#IOPAE-629] ADD PUT /keys/manage API handler Implementation in Backoffice

- .github/workflows/azure-deploy.yaml
after adding retry step to the BO deploy github action we add a final check to interrupt the flow in case after all the retry we still have an error
> fix : add final error status check for BO deploy action

- .github/workflows/azure-deploy.yaml
fix for a syntax error in the azure deploy github action
> fix syntax error on condition

- .changeset/giant-fans-notice.md
- apps/backoffice/package.json
- apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
- Change test command on `backoffice/package.json`
- Fix Auth Route Handler unit test
> chore(fix):  Fix auth unit test

- .changeset/mean-mails-relax.md
- apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/review-checker-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/review-checker-handler.ts
- apps/io-services-cms-webapp/src/reviewer/review-legacy-checker-handler.ts
- apps/io-services-cms-webapp/src/utils/jira-proxy.ts
Handle changed Jira `status.name`.
Multiple solution POC
New status names:
- `Nuovo` was `New`
- `Revisione` was `Review`
- `Approvato` was `Approved`
- `Rifiutato` was `Rejected`
> chore(bug): [IOPAE-692] Handle new jira status names

- .changeset/pink-emus-travel.md
- .github/workflows/azure-deploy.yaml
- .github/workflows/infra-cd.yml
- .github/workflows/infra-ci.yml
- .github/workflows/infra-drift-detection.yml
> chore: Upgrade github action runner image version

- .github/workflows/azure-deploy.yaml
- .github/workflows/infra-cd.yml
- .github/workflows/infra-ci.yml
- .github/workflows/infra-drift-detection.yml
Use default github hosted runner image version
> chore: use default github hosted runner image version

- .changeset/seven-cats-cry.md
- apps/io-services-cms-webapp/UploadServiceLogoTest/function.json
- apps/io-services-cms-webapp/src/webservice/index.ts
> ADD test upload service logo api

- .changeset/violet-cobras-turn.md
- apps/backoffice/openapi.yaml
- apps/backoffice/src/app/api/info/__tests__/route.test.ts
- apps/backoffice/src/app/api/info/route.ts
- apps/backoffice/src/lib/be/__tests__/healthcheck.test.ts
- apps/backoffice/src/lib/be/apim-service.ts
- apps/backoffice/src/lib/be/cms-client.ts
- apps/backoffice/src/lib/be/errors.ts
- apps/backoffice/src/lib/be/healthcheck.ts
- apps/backoffice/src/lib/be/legacy-cosmos.ts
- apps/backoffice/src/lib/be/selfcare-client.ts
- apps/io-services-cms-webapp/openapi.yaml
Implementing HealthChecks for the backoffice B4F.
- ADD new Error `HealthCheckError` in order to handle Health checks
- ADD `getApimHealth` a method for checking the operating status with `APIM`
- ADD `getIoServicesCmsHealth` a method for checking the operating status with `io-services-cms` 
- ADD `getLegacyCosmosHealth` a method for checking the operating status with `io-p-cosmos-api` 
- ADD `getSelfcareHealth` a method for checking the operating status with `selfcare`
- ADD `healthcheck.ts` which is responsible for health checks handling.
- ADD healthchecks information in `GET /api/info` Route Handler
Example Info Response:
1. No Healthcheck failures
```json
{
"name": "io-services-cms-backoffice",
"version": "0.11.0",
"health": {
"status": "ok"
}
}
```
2. One or more Healthchecks fails …
> [IOPAE-723] B4F Healthchecks

- .changeset/curly-steaks-rest.md
- apps/backoffice/.env
- apps/backoffice/src/components/footer/index.tsx
- apps/backoffice/src/config/index.ts
Added correct URLs on BackOffice webapp footer for:
- privacy policy
- terms & conditions (tos)
- personal data protection
- update frontend `footer`
- update `config` file
- add `.env` variables
> [IOPAE-744] Add BackOffice footer links

- .changeset/beige-bikes-wave.md
- apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
- apps/backoffice/src/lib/be/apim-service.ts
- packages/external-clients/src/apim-client/index.ts
Refactor auth implementation in order to keep it clean
- [use getApimService from backoffice lib instead of directly from external-clients](https://github.com/pagopa/io-services-cms/commit/f4f16b675c94e84bf0810fd5938ca19980c79532) 
- [move createOrUpdateUser to external-clients package](https://github.com/pagopa/io-services-cms/commit/d65e2b152d59b6774f1d79f28f75e435dce25006)
- [refactor move createGroupUser to external-clients package](https://github.com/pagopa/io-services-cms/commit/37f77f71009e842f284d79c4d4b0cb2633304f0e)
To keep code clean
> refactor: B4F refactor apim service

- .changeset/nine-paws-admire.md
- apps/backoffice/src/app/api/health/route.ts
- apps/backoffice/src/app/api/info/route.ts
The default behaviour for GET Route Handlers without request is to evaluate the code at build and statically link the result to the api as described [here](https://nextjs.org/docs/app/building-your-application/routing/route-handlers#opting-out-of-caching).
Exporting the string `export const dynamic = "force-dynamic";` on the Route Handlers, more info [here](https://nextjs.org/docs/app/building-your-application/routing/route-handlers#segment-config-options), will force next not to evaluate the api function content and link the actual function code, so the api will be dynamic.
> chore(fix): dynamic api info health

- .changeset/quick-pans-grow.md
- apps/backoffice/mocks/handlers/selfcare-handlers.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
- apps/backoffice/src/lib/be/institutions/selfcare.ts
- apps/backoffice/src/lib/be/selfcare-client.ts
Add logged institution logo to session token and try to improve `selfcare-client` code readability by adding fn signature.
- add logged institution logo to session token
- refactor: add fn signature to selfcare-client
> Iopae 738  b4f fetch logged institution logo

- apps/backoffice/openapi.yaml
Change `ServiceListItem` visibility field from `boolean` to `enum ["published", "unpublished"]`
> [#IOPAE-748] Edit visibility field

- .changeset/modern-rings-cheer.md
- apps/backoffice/src/app/api/keys/manage/[keyType]/__tests__/route.test.ts
- apps/backoffice/src/app/api/keys/manage/__tests__/route.test.ts
- apps/backoffice/src/app/api/keys/manage/cidrs/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/route.ts
- apps/backoffice/src/lib/be/__tests__/services.test.ts
- apps/backoffice/src/lib/be/__tests__/wrappers.test.ts
- apps/backoffice/src/lib/be/services/business.ts
Do not use `bodyUsed` anymore as a check before read request body
> bugfix: [IOPAE-764] b4f problem when parsing request body

- infra/src/env/prod/terraform.tfvars
- infra/src/webapp.tf
- Scale up BO app service plan
- Add BO subnet to services-cms allowed networks
> chore: [IOPAE-577] BO change app service plan

- .changeset/popular-bulldogs-lick.md
- .github/workflows/azure-deploy.yaml
> bugfix: fix deploy healthcheck

- .github/workflows/azure-deploy-manual.yaml
- .github/workflows/azure-deploy.yaml
> chore: B4F patch deploy gh action

- .changeset/sour-owls-call.md
- .github/workflows/azure-deploy-manual.yaml
- .github/workflows/azure-deploy.yaml
- apps/backoffice/mocks/handlers/services-cms-handlers.ts
> chore: Upgrade azure deploy action

- infra/src/backoffice_webapp.tf
> chore: add WEBSITE_RUN_FROM_PACKAGE

- .changeset/kind-cars-exist.md
- apps/backoffice/src/app/api/health/route.ts
- apps/backoffice/src/app/api/info/route.ts
- apps/backoffice/src/lib/be/cms-client.ts
Remove `getIoServicesCmsHealth` healthcheck on `/api/info` and `/api/health` Route handlers
> chore: remove getIoServicesCmsHealth on info api

- .changeset/gold-items-ring.md
- apps/backoffice/next.config.js
- apps/backoffice/package.json
- apps/backoffice/src/instrumentation.ts
- infra/src/backoffice_webapp.tf
- yarn.lock
Integrate BO app with Application insights
> feat: [IOPAE-779] add appinsight configs

- .changeset/brave-months-fold.md
- apps/backoffice/src/app/api/health/__tests__/route.test.ts
- apps/backoffice/src/app/api/health/route.ts
- apps/backoffice/src/app/api/info/__tests__/route.test.ts
- apps/backoffice/src/app/api/info/route.ts
Remove healthchecks which was calling external services.
> chore: removed healtcheck which calls external services

- .changeset/fuzzy-tigers-sort.md
- apps/backoffice/src/app/api/institutions/[institutionId]/route.ts
- apps/backoffice/src/lib/be/cms-client.ts
Add temporany logs to evaluate external api call, and general api process.
> chore: add log for performance test

- .changeset/dry-parrots-talk.md
- apps/backoffice/src/app/api/keys/manage/[keyType]/route.ts
> chore: add time debug log on regenerate manage key

- .github/workflows/azure-deploy-manual.yaml
- .github/workflows/azure-deploy.yaml
> chore: add sleep before staging health-check

- apps/backoffice/.env.production
- apps/backoffice/src/instrumentation.ts
- infra/src/backoffice_webapp.tf
> patch: enable appInsights client only on prod

- apps/backoffice/.gitignore
- apps/backoffice/mocks/index.ts
Update **MSW** configuration for frontend.
- Added `/public/mockServiceWorker.js` on `.gitignore`
- Added check on process env variable `NEXT_PUBLIC_IS_MSW_ENABLED` to start **msw** locally in dev mode
> chore: Update msw configuration for frontend

- .changeset/serious-emus-tie.md
- apps/backoffice/mocks/data/subscription-migration-data.ts
- apps/backoffice/openapi.yaml
Update `MigrationData` field in B4F `openapi.yaml`
> chore(fix): change response schema MigrationData

- .changeset/dry-llamas-work.md
- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/src/components/services/subscriptions-migration/migration-modal.tsx
> chore: Fix frontend subscription migration data

- .changeset/sour-dryers-invite.md
- apps/backoffice/mocks/data/subscription-migration-data.ts
- apps/backoffice/src/lib/be/subscription-migration-client.ts
Adapt ownership claim response
> Fix: b4f sub mig

- .changeset/little-baboons-reply.md
- apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
- apps/backoffice/src/app/api/auth/types.ts
During Token Exchange, add ApiServiceWrite permission to Apim user if missing (required to retrieve _MANAGE_ api key)
> bugfix: [IOPAE-786] add ApiServiceWrite permission if missing

- .changeset/afraid-students-worry.md
- apps/backoffice/src/styles/app-layout.module.css
Fixed an issue that caused the main content layout to break on lower width resolutions.
This "break" brought the main content to a new line and therefore the inline display with the sidenav menu was compromised.
**With this change the problem is solved at any resolution.**
- added `overflow-x` to **auto**
Local `dev` mode with `msw` mock with 3 different browsers _(Chrome, Firefox, Safari)._
> bugfix:[IOPAE-785] Fix main content layout overflow

- .changeset/ten-beers-check.md
- apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
- apps/backoffice/src/app/api/auth/types.ts
- use apimUser.id instead of apimUser.name during manage subscription creation
> bugfix: fix payload create subscription manage

- .changeset/tasty-plants-reflect.md
- apps/backoffice/src/app/api/services/list/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/list/route.ts
- apps/backoffice/src/lib/be/__tests__/services.test.ts
- apps/backoffice/src/lib/be/services/business.ts
- apps/backoffice/src/lib/be/services/utils.ts
ADD missing service placeholder on service list Route Handler result's.
``` json
{
"id": "serviceId",
"status": { 
"value": "deleted"
},
"last_update": 1699964922,
"name": "Servizio non disponibile",
"description": "Descrizione non disponibile",
"organization": {
"name": "Istituzione non disponibile",
"fiscal_code": "00000000000"
},
"metadata": {
"scope": "LOCAL",
"category": "STANDARD"
},
"authorized_recipients": [],
"authorized_cidrs": []
}
```
Unit Test
> chore: Add missing service placeholder on service list Route Handler result's

- .changeset/dull-carrots-beam.md
- apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
Initialize manage cidrs when creating subscription manage
> bugfix: Patch manage subs cidrs

- .changeset/orange-moons-admire.md
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
> chore: log unknown error

- .changeset/tender-tigers-taste.md
- apps/backoffice/.env.production
> bugfix: Patch services logo url config

- .changeset/cuddly-radios-smash.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/table-view/table-view.tsx
- apps/backoffice/src/pages/services/[serviceId]/edit-service.tsx
- apps/backoffice/src/pages/services/index.tsx
- apps/backoffice/src/pages/services/new-service.tsx
IO BackOffice frontend minor fixes:
- 58ed9f619c6d3583d89b387deacfc31dfc167514 [service name left alignment on services table]
- bf501cfad2c169e504dff6c82ed589911249f553 [await create/update service completion before going to services page]
- 957e942a5f6077901cd5242a73a8c9affbedd2f7 [translate table pagination component labels]
> chore: Fix frontend minor issues for mvp0 release

- .changeset/little-dots-invite.md
- packages/io-services-cms-models/openapi/selfcare-schemas.yaml
change mailAddress to digitalAddress in istitution open api
> fix:change mailAddress to digitalAddress in istitution open api

- .changeset/grumpy-pigs-dream.md
- apps/backoffice/mocks/data/selfcare-data.ts
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/lib/be/institutions/business.ts
- apps/backoffice/src/pages/index.tsx
change all `mailAddress` reference to `digitalAddress`
> fix: Follow up fix for institution open api

- .changeset/twenty-queens-hide.md
- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/src/components/services/service-alerts.tsx
Fix frontend service rejection reason drawer,  in case of multiple comments now they will be displayed on multiple rows
> fix: fe service rejection reason drawer

- .changeset/stale-trees-appear.md
> BackOffice MVP0 - Public major version 1.0.0

- .changeset/orange-baboons-do.md
- apps/backoffice/src/app/api/auth/[...nextauth]/route.ts
- apps/backoffice/src/components/headers/header.tsx
- apps/backoffice/src/pages/auth/login.tsx
Enable institution selection
- [allow redirect URL to Selfcare origin](https://github.com/pagopa/io-services-cms/commit/395827b03d8b1d00b1f575ef795796da9f28ed7c)
- [enable party switch](https://github.com/pagopa/io-services-cms/commit/f6385bfd20832da94209a86f74530658c1e0e8b2)
- [remove useless timeout on login page](https://github.com/pagopa/io-services-cms/commit/ccb27315e91c802ab215807ab5a54c322244e7a9)
To allow user to switch between its institutions
Local `dev mode` with `MSW` mock
> feat: [IOPAE-803] BO enable party switch

- .changeset/fluffy-laws-fetch.md
- apps/backoffice/src/app/api/auth/[...nextauth]/route.ts
- [decrease session duration](https://github.com/pagopa/io-services-cms/commit/8fcc295db13b9f5c72db94375864a763fc889fe1)
Local `dev mode` with `MSW` mock
> chore: [IOPAE-804] B4F decrease session duration

- .changeset/healthy-jobs-impress.md
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
- apps/backoffice/src/lib/be/errors.ts
Apim rest error log shrink
Unit test
> chore: Apim rest error log shrink

- .changeset/seven-carrots-approve.md
- apps/backoffice/.env
- apps/backoffice/src/components/headers/header.tsx
- apps/backoffice/src/config/index.ts
- apps/backoffice/src/pages/mocks/selfcare/dashboard/[institutionId]/groups.tsx
- apps/backoffice/src/pages/mocks/selfcare/dashboard/[institutionId]/index.tsx
- apps/backoffice/src/pages/mocks/selfcare/dashboard/[institutionId]/users.tsx
Added **product switch** on _AppLayout_ `Header` component.
This switch is useful for giving user the opportunity to return to the _Reserved Area_ dashboard.
In addition, 3 mock pages of Selfcare sections have been created, very useful in the _local dev environment_: users, groups and dashboard.
**Follow commits history to better understand development.
Watch the video below to appreciate result.**
Need to return on Selfcare dashboard.
**Product switch video:**
https://github.com/pagopa/io-services-cms/assets/118166285/6c66e913-c005-41e8-8730-80b455156a80
**Additional page mocks for SelfCare Users and Groups:**
> [IOPAE-809] Add product switch on BackOffice IO

- .changeset/tough-plums-design.md
- apps/io-services-cms-webapp/src/watchers/__tests__/on-legacy-service-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts
Handle legacy service having name strictly "DELETED" received on `OnLegacyServiceChange`
Unit Test
> chore(fix): workaround on DELETED name received

- .changeset/weak-poets-push.md
- packages/io-services-cms-models/src/service-publication/__tests__/index.test.ts
- packages/io-services-cms-models/src/service-publication/index.ts
Change publish action to allow whether override service data or not based on input parameter
Unit tests
> bugfix: Patch publish action

- .changeset/clean-peaches-suffer.md
- apps/backoffice/mocks/handlers/selfcare-handlers.ts
- apps/backoffice/src/app/api/institutions/route.ts
- apps/backoffice/src/lib/be/__tests__/institutions.test.ts
- apps/backoffice/src/lib/be/institutions/business.ts
Reintroduced GET /api/institutions API, which returns all the user's authorized institutions, in order to remove `authorizedInstitutions` field in session jwe token.
Needed in order to reduce JWE token lenght.
Unit Tests
> bug: [IOPAE-824] Bring back institutions api

- .changeset/breezy-lies-switch.md
- apps/backoffice/openapi.yaml
- apps/backoffice/src/lib/be/__tests__/institutions.test.ts
- apps/backoffice/src/lib/be/institutions/business.ts
Update User Authorized institution API response type in order to return only necessary parameters.
- ADD new `UserAuthorizedInstitutions` and `UserAuthorizedInstitution` schemas in open api
- `GET /api/institutions` Route Handler now returns `UserAuthorizedInstitutions` as response
- Renamed operation `GET /api/institutions` Route Handler in openapi.yaml, from `getInstitutions` to `getUserAuthorizedInstitutions` in order to better identify the Api scope
Unit tests
> [#IOPAE-828] UPDATE User Authorized institution API response type

- .changeset/lucky-camels-draw.md
- apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/route.ts
- apps/backoffice/types/next-auth.d.ts
Remove authorized institutions from session token
Session token became too big if user is related to many institutions
Unit tests
> bugfix: [IOPAE-827] remove authorized institutions from session token

- .changeset/pink-pianos-cry.md
- apps/io-services-cms-webapp/src/utils/converters/service-lifecycle-converters.ts
- apps/io-services-cms-webapp/src/utils/converters/service-publication-converters.ts
to match documentation we need to add require_secure_channel and authorized_recipients in cms api response
> [#IOPAE-810]add require_secure_channel and authorized_recipients in api response

- .changeset/lovely-pianos-hug.md
- apps/io-services-cms-webapp/openapi.yaml
- packages/io-services-cms-models/openapi/services-cms-schemas.yaml
Add service topics in `io-services-cms` openapi.yaml.
- Added `GET /services/topics` api definition in `openapi.yaml`
- Added `ServiceTopicList` schema:
``` json
{
"topics": [
{
"id": 3,
"name": "string"
}
]
}
```
- Added `ServiceTopic` schema:
``` json
{
"id": 3,
"name": "string"
}
```
- Added `topic_id` parameter(optional) in `ServicePayload` schema, api which will receive the new parameter:
- `POST /services`
- `PUT /services/{serviceId}`
- Added `topic` field(optional) in `ServiceLifecycle` and `ServicePublication`, api which will returns the new field:
- `GET /services`
- `POST /services`
-  `GET /services/{serviceId}`
-  `PUT /services/{serviceId}`
-  `GET /services/{serviceId}/release`
> [IOPAE-817] Service Topics in io-services-cms openapi

- .changeset/plenty-planets-hug.md
- apps/backoffice/openapi.yaml
In completion of the https://github.com/pagopa/io-services-cms/pull/580, the backoffice openapi specification has been updated, adding information relating to service **topic**.
> [IOPAE-818] Update BackOffice openapi with topic definition

- apps/io-services-cms-webapp/db/scripts/run_flyway_on_azure.sh
- apps/io-services-cms-webapp/db/scripts/run_flyway_on_server.sh
Update flayway docker version
Executed locally running Postgres instance
> chore: update flayway docker version

- .changeset/ten-steaks-retire.md
- apps/backoffice/src/app/api/services/[serviceId]/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/[serviceId]/keys/[keyType]/route.ts
- apps/backoffice/src/app/api/services/[serviceId]/keys/route.ts
- apps/backoffice/src/app/api/services/[serviceId]/logo/route.ts
- apps/backoffice/src/app/api/services/[serviceId]/release/route.ts
- apps/backoffice/src/app/api/services/[serviceId]/review/route.ts
- apps/backoffice/src/app/api/services/[serviceId]/route.ts
- apps/backoffice/src/app/api/services/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/route.ts
- apps/backoffice/src/lib/be/__tests__/services.test.ts
- apps/backoffice/src/lib/be/services/business.ts
- apps/backoffice/src/lib/be/services/utils.ts
- apps/io-services-cms-webapp/openapi.yaml
For future Audit purpose we are forwarding the client Ip who is calling the BO B4F API to io-services-cms.
> [#IOPAE-868] B4F X-Forwarded-For on io-services-cms request

- .changeset/small-avocados-work.md
- apps/io-services-cms-webapp/host.json
Reduce default logging level (from Information to Warning) and keep Function logging level to Information (see [Configure categories](https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#configure-categories) and [Configure log levels](https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#configure-log-levels))
- [reduce default logging level](https://github.com/pagopa/io-services-cms/commit/a033a0cba00681f92914a56898cbf82643634cea)
To reduce log entropy
> chore: reduce cms logging level

- .changeset/quiet-emus-hug.md
- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/services/adapters.ts
- apps/backoffice/src/components/services/service-info.tsx
- apps/backoffice/src/types/service.ts
Added topic information in service details page _(See red rectangle in the screenshot below)._
_Follow commits history to better understand development._
- [update service topic mock with possible undefined result](https://github.com/pagopa/io-services-cms/commit/4497237423a0323791f6f6968abf813b705c6acc)
- [add useful translations](https://github.com/pagopa/io-services-cms/commit/44fcd9cb7e37b43732f2ed39299f1d808e798cea)
- [update Service view model type](https://github.com/pagopa/io-services-cms/commit/c8f11dcc4466a9d0e16fee186de1e6cac34a6951)
- [add topic on service-info drawer view](https://github.com/pagopa/io-services-cms/commit/2ba0e12d750af3afb90c5e723ab404b15abd80d6)
> [IOPAE-819] Add topic in service details page

- .github/workflows/infra-static-analysis.yaml
- infra/src/README.md
- infra/src/webapp.tf
ADD `BACKOFFICE_INTERNAL_SUBNET_CIDRS` configuration, this config contains the Backoffice subnet, CIDR notation, comma separated list.
> [#IOPAE-869] ADD BACKOFFICE_INTERNAL_SUBNET_CIDRS configuration

- .changeset/olive-icons-raise.md
- apps/io-services-cms-webapp/src/utils/azure-user-attributes-manage-middleware-wrapper.ts
> Add log on AzureUserAttributesManageMiddlewareWrapper

- .changeset/gentle-bikes-deliver.md
- apps/backoffice/package.json
- apps/io-services-cms-webapp/package.json
- yarn.lock
Update `vite` and `vitest` to major versions on **io-services-cms-backoffice** and **io-services-cms-webapp** apps.
The opportunity was taken to update the other backoffice minor dev libraries as well _(see details below)_.
**BackOffice dev dependencies:**
- "@faker-js/faker": "^8.3.1"
- "@testing-library/jest-dom": "^6.1.5"
- "@testing-library/react": "^14.1.2"
- "@types/lodash": "^4.14.202"
- "@types/react": "^18.2.43"
- "@types/react-dom": "^18.2.17"
- "@vitejs/plugin-react": "^4.2.1"
- "@vitest/coverage-v8": "^1.0.4"
- "jsdom": "^23.0.1"
- "vite": "^5.0.8" **major**
- "vitest": "^1.0.4" **major**
**Webapp "APIs" dev dependencies:**
- "@vitest/coverage-v8": "^1.0.4" **major**
- "vitest": "^1.0.4" **major**
_*Remove unused @types/cidr-matcher_
Repo update maintenance, Security …
> chore: Update vite/vitest dev dependencies

- .changeset/happy-meals-double.md
- packages/external-clients/package.json
- packages/io-services-cms-models/package.json
- yarn.lock
Following https://github.com/pagopa/io-services-cms/pull/605 PR, the version of `vitest` has also been updated for the projects in the **packages** folder.
**External-clients:**
- "@vitest/coverage-v8": "^1.0.4"
- "vitest": "^1.0.4"
**Models:**
- "@vitest/coverage-v8": "^1.0.4"
- "vitest": "^1.0.4"
Repo update maintenance, Security [CVE-2023-44270](https://github.com/pagopa/io-services-cms/security/dependabot/16) issue
Unit tests
> chore: Update vite on packages projects

- .changeset/tame-ravens-grin.md
- packages/io-services-cms-models/openapi/services-cms-schemas.yaml
- packages/io-services-cms-models/src/service-lifecycle/definitions.ts
move topic into service metadata object
> chore: move topic into service metadata object

- .changeset/moody-buses-develop.md
- apps/backoffice/src/components/services/adapters.ts
- packages/io-services-cms-models/openapi/services-cms-schemas.yaml
Fix topic metadata on frontend adapter
> bugfix: Fix topic metadata on frontend adapter

- .changeset/early-oranges-fry.md
- apps/backoffice/src/lib/be/services/utils.ts
- apps/io-services-cms-webapp/openapi.yaml
- apps/io-services-cms-webapp/src/utils/converters/service-lifecycle-converters.ts
- apps/io-services-cms-webapp/src/utils/converters/service-publication-converters.ts
- ADD `ServiceBaseMetadata` and `ServicePayloadMetadata` missing on webapp `openapi.yaml`
- FIX metadata imports on webapp and backoffice
> fix: Add missing schemas ref webapp openapi

- .changeset/wild-keys-draw.md
- apps/backoffice/mocks/handlers/apim-handlers.ts
- apps/backoffice/mocks/handlers/backend-handlers.ts
- apps/backoffice/mocks/handlers/cdn-handlers.ts
- apps/backoffice/mocks/handlers/cosmos-legacy-handlers.ts
- apps/backoffice/mocks/handlers/selfcare-handlers.ts
- apps/backoffice/mocks/handlers/services-cms-handlers.ts
- apps/backoffice/mocks/handlers/subscription-migration-handler.ts
- apps/backoffice/mocks/msw-worker.ts
- apps/backoffice/next.config.js
- apps/backoffice/package.json
- yarn.lock
Update **MSW** package to latest major V2 release.
Follow commits history to better understand migration/update steps.
Local build/dev tests.
> chore:[IOPAE-880] update MSW package to v2 major release

- .changeset/few-pigs-perform.md
- apps/io-services-cms-webapp/src/utils/jira-proxy.ts
- Move Up Scope on jira issue for service review
- Set `color to red` when Service Scope is `NATIONAL`
- Add `disclaimer` when Service Scope is `NATIONAL`
> [#IOPAE-894] edit jira layout review ticket

- infra/src/README.md
- infra/src/api/io_services_cms/v1/_swagger.yaml.tpl
- infra/src/api/io_services_cms/v1/getservicetopics_policy/policy.xml
- infra/src/apim_v2_api.tf
- add get service topic api
- add policy on get service topic api
> [#IOPAE-859]Get Service Topic Policy

- infra/src/api/io_services_cms/v1/_swagger.yaml.tpl
> [#IOPAE-859]fix:get service topic swagger errors

- infra/src/api/io_services_cms/v1/_swagger.yaml.tpl
> [#IOPAE-859]remove parameter in get topics api in swagger

- .changeset/thirty-baboons-wonder.md
- apps/backoffice/src/app/api/services/topics/route.ts
- apps/backoffice/src/lib/be/services/business.ts
- apps/backoffice/src/lib/be/services/cms.ts
Add Retrieve Service topics Route Handler in Backoffice B4F.
- ADD `GET /services/topics` Route Handler
- ADD `getServiceTopics` temporany static function, this function will be effectively implemented when the corresponding  io-service-api will be implemented.
> [#IOPAE-899] Service topics route handler in Backoffice B4F

- .changeset/healthy-pens-doubt.md
- apps/backoffice/src/lib/be/__tests__/services.test.ts
- apps/backoffice/src/lib/be/services/business.ts
- apps/backoffice/src/lib/be/services/utils.ts
Enrich topic in serviceList B4F Route Handler
> [#IOPAE-900] Enrich Topic on ServiceList Route Handler

- .changeset/hip-mirrors-burn.md
- apps/io-services-cms-webapp/src/config.ts
- apps/io-services-cms-webapp/src/utils/converters/__tests__/service-lifecycle-converters.test.ts
- apps/io-services-cms-webapp/src/utils/converters/service-lifecycle-converters.ts
- apps/io-services-cms-webapp/src/utils/converters/service-publication-converters.ts
- apps/io-services-cms-webapp/src/utils/service-review-dao.ts
- apps/io-services-cms-webapp/src/utils/service-topic-dao.ts
- apps/io-services-cms-webapp/src/utils/service-topic-validator.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__tests__/edit-service.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__tests__/get-service-lifecycle.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__tests__/get-service-publication.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/create-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/edit-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-lifecycle.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-publication.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-services.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
- infra/src/99_variables.tf
- infra/src/README.md
- infra/src/env/prod/terraform.tfvars
- infra/src/webapp.tf
Add logic from CMS API to manage new topic fields
- [manage topic on create/edit request](https://github.com/pagopa/io-services-cms/commit/3cfa5e2f6b5ad8da475d06fafff49bc8272e5e07)
- [manage topic on all service responses](https://github.com/pagopa/io-services-cms/commit/683b8d73766b450d852169452ffa33c0a2ff4c95)
> feat: [IOPAE-792] cms api manage topic

- .changeset/ninety-pianos-share.md
- apps/io-services-cms-webapp/src/utils/service-topic-dao.ts
Add _is not deleted_ where condition and select only `id` and `name` fields.
> patch: [IOPAE-792] fix query get topic

- .changeset/flat-years-glow.md
- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/openapi.yaml
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/forms/controllers/autocomplete-controller.tsx
- apps/backoffice/src/components/forms/controllers/index.ts
- apps/backoffice/src/components/forms/controllers/select-controller.tsx
- apps/backoffice/src/components/services/__tests__/adapters.test.ts
- apps/backoffice/src/components/services/adapters.ts
- apps/backoffice/src/components/services/service-create-update/service-builder-step-1.tsx
- apps/backoffice/src/components/services/service-create-update/service-create-update.tsx
- apps/backoffice/src/components/services/service-info.tsx
- apps/backoffice/src/pages/services/[serviceId]/edit-service.tsx
- apps/backoffice/src/pages/services/new-service.tsx
- apps/backoffice/src/types/service.ts
Added **topic** management when **creating/editing** a service.
Service topic is an optional property that can be set in the create/update form.
- update backoffice `openapi` with topic data
- update Service **types**, **adapters** and all topic **related data**
- update **translations**
- update `MSW` mocks with topic data
- add new `AutocompleteController` with **MUI** `Autocomplete` component
- add **frontend logic** to manage service topic on create/update form
- minor adjustments
- c90f589 fix MUI warning _(MUI: The value provided to Autocomplete is invalid. None of the options match with `""`.)_
- 35975fc update topic field layout: reduce width to half
Need to manage the topic of a service
Unit tests …
> [IOPAE-793] Frontend topic management on create/update service

- .changeset/five-queens-notice.md
- apps/backoffice/src/lib/be/services/utils.ts
- apps/io-services-cms-webapp/src/utils/converters/service-lifecycle-converters.ts
- apps/io-services-cms-webapp/src/utils/converters/service-publication-converters.ts
- apps/io-services-cms-webapp/src/utils/service-topic-validator.ts
> patch: [IOPAE-792] fix topic not null check

- .changeset/perfect-ants-speak.md
- apps/io-services-cms-webapp/src/utils/converters/__tests__/service-lifecycle-converters.test.ts
- apps/io-services-cms-webapp/src/utils/converters/service-lifecycle-converters.ts
- apps/io-services-cms-webapp/src/utils/converters/service-publication-converters.ts
remove category and custom_special_flow from api response , this fields should only be visible to admin
- remove category in api response
- remove custom-special_flow in api response
- adjust unit tests
> [#IOPAE-844]remove category and custom_special_flow from api response

- .github/workflows/infra-cd.yml
Add checkout, tf setup and artifact upload/download
Runners are ephemeral now and everything is wiped out when a job ends
> [EC-69] Add missing steps from infra CD pipeline

- .github/workflows/infra-cd.yml
Replace `terraform.sh apply` with `terraform apply`
terraform.sh always add a `-var` flag and this is not supported when plan is saved to a file
> [EC-69] Replace sh script with tf command

- .changeset/forty-ducks-crash.md
- apps/io-services-cms-webapp/src/webservice/index.ts
- infra/src/README.md
- infra/src/api/io_services_cms/v1/getservicetopicstest_policy/policy.xml
- infra/src/apim_v2_api.tf
Add policy cache on GET /services/topicstest API
> Add policy cache on GET /services/topicstest API

- .changeset/many-cherries-approve.md
- apps/io-services-cms-webapp/src/watchers/__tests__/on-service-history-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-service-history-change.ts
Sync to legacy only Publication Items and Delete
> [#IOPAE-910] Sync to legacy only Publication and Deleted Items

- .changeset/shiny-papayas-know.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
Correction to the information text of the **upload service logo box** where the text _"institution logo"_ was incorrectly reported instead of _"service logo"_
- translations
> [IOPAE-853] Fix upload service logo copy

- .changeset/proud-starfishes-return.md
- apps/io-services-cms-webapp/src/lib/clients/pg-client.ts
- apps/io-services-cms-webapp/src/webservice/controllers/info.ts
Add PostgreSQL DB Healthcheck.
> [#IOPAE-310] Add postgreSQL DB Health Check

- .changeset/few-planets-drive.md
- apps/backoffice/public/locales/it/common.json
Change `it` translation for _"Chiavi API"_: we will use _"API Key"_ in all references.
- translations
> [IOPAE-851] Fix API Key copy

- .changeset/poor-apples-report.md
- apps/io-services-cms-webapp/GetServiceLifecycleInternal/function.json
- apps/io-services-cms-webapp/GetServicePublicationInternal/function.json
- apps/io-services-cms-webapp/src/utils/applicationinsight.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-lifecycle-internal.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-publication-internal.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
ADD Internal GET Service Publication and Lifecycle APIs called By Developer Portal
- ADD GET `/internal/services/:serviceId` API
- ADD GET `/internal/services/:serviceId/release` API
> [IOPAE-907] Get Service Publication internal api

- .changeset/selfish-beds-sparkle.md
- apps/backoffice/src/components/cards/card-details.tsx
Update card tertiary CTA layout, replacing the _MUI_ `Button` with the _mui-italia_ `ButtonNaked` component.
_Watch screenshot to better understand layout update._
**Before change:**
**After change:**
> [IOPAE-854] Update card tertiary CTA layout

- .changeset/pretty-feet-work.md
- apps/backoffice/src/components/buttons/button-with-loader.tsx
- apps/backoffice/src/components/buttons/index.ts
- apps/backoffice/src/components/services/subscriptions-migration/migration-manager.tsx
Update services import button layout:
- add **upload** startIcon
- update button font-weight to **700**
- Update `ButtonWithLoader` component to manage _startIcon_, _endIcon_, _sx_ theme props
> [IOPAE-852] Update services import button layout

- .changeset/stupid-rockets-swim.md
- apps/backoffice/src/components/forms/controllers/url-field-controller.tsx
- apps/backoffice/src/components/forms/form-step-section-wrapper.tsx
- apps/backoffice/src/components/services/service-create-update/service-builder-step-1.tsx
- apps/backoffice/src/components/services/service-create-update/service-builder-step-2.tsx
- apps/backoffice/src/components/services/service-create-update/service-builder-step-3.tsx
- apps/backoffice/src/components/services/service-create-update/service-extra-configurator.tsx
Update service create/update form icons.
> [IOPAE-886] Update service create/update form icons

- .changeset/three-spies-return.md
- apps/backoffice/src/pages/services/index.tsx
Reduce visibility icons size in services page.
> [IOPAE-898] Reduce visibility icons size in services page

- .identity/04_github_identity.tf
- infra/src/.terraform.lock.hcl
- infra/src/README.md
- infra/src/apim_v2_api.tf
- infra/src/backoffice_webapp.tf
- infra/src/database_cms.tf
- infra/src/database_review.tf
- infra/src/env/prod/terraform.tfvars
- infra/src/key_vault.tf
- infra/src/network.tf
- infra/src/storage_account.tf
- infra/src/webapp.tf
Migrate tf modules to version 7.45.0
- [updates infra tf modules to version 7.45.0](https://github.com/pagopa/io-services-cms/commit/8fc90c5ac2010071db0de11022879652ee251a79)
- [updates ci-cd tf modules to version 7.45.0](https://github.com/pagopa/io-services-cms/commit/9ed90f12330621466640ea741f0895d9e1a91275)
Change requested from Cloud Engineering Team
> refactor: [IOPAE-918] migrate tf modules

- infra/src/.terraform.lock.hcl
- infra/src/99_variables.tf
- infra/src/README.md
- infra/src/container_app_job.tf
- infra/src/env/prod/terraform.tfvars
Add container app job definition to terraform
Each repo has its own container app job
> [EC-84] Add GitHub private runner on Container App job

- .changeset/cool-guests-learn.md
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/watchers/__tests__/on-service-history-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-service-history-change.ts
Sync on legacy when service was never published.
Unit Tests
> [#IOPAE-932] Sync on legacy when service was never published

- .changeset/new-eyes-boil.md
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/request-review-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/request-review-handler.ts
- apps/io-services-cms-webapp/src/utils/__tests__/jira-proxy.test.ts
- apps/io-services-cms-webapp/src/utils/jira-proxy.ts
Added in the ticket if the review request is related to a first service activation or a subsequent change.
Unit Test
> [#IOPAE-904] First service activation info on review ticket

- .changeset/little-hounds-sell.md
- apps/backoffice/src/components/services/service-context-menu.tsx
Update **ServiceContextMenu** component in service details page.
- update publish/unpublish action icons
- update publish action button variant
- fix edit action color _(from text to primary)_
Quality Assurance activity
> [IOPAE-888] Update service-context-menu in service details page

- apps/backoffice/openapi.yaml
Add new api definition for Zendesk integration
- add api `post : /assistance`
- add type for requestBody and response
Integrate the possibility of requesting assistance by indicating an email on which to receive feedback
> [IOPAE-831] New assistance api definition for Zendesk integration

- .changeset/funny-lemons-sing.md
- apps/backoffice/src/components/services/service-version-switcher.tsx
Update **ServiceVersionSwitcher** component layout.
_Watch screenshots below to better appreciate changes._
**Before update:**
**After update:**
> [IOPAE-884] Update ServiceVersionSwitcher component layout

- .changeset/late-deers-fold.md
- apps/backoffice/src/components/table-view/table-row-menu.tsx
- apps/backoffice/src/pages/services/index.tsx
Services **TableRowMenu**: add icons and set delete action as last.
_Watch screenshots below to better appreciate changes._
- add icons for each menu item
- the delete action is always last on the list
> [IOPAE-852] Services TableRowMenu: add icons and set delete action as last

- .changeset/wild-mangos-joke.md
- apps/backoffice/src/config/app-theme.ts
- apps/backoffice/src/providers/app.tsx
Color customization for **MUI** `Chip` component.
_Watch screenshot below to appreciate highlighted color changes._
- override `backgroundColor` and `color` for success, warning, error Chip variant
Quality assurance activity: component accessibility and readability.
> [IOPAE-881] MUI Chip custom styleOverrides

- .changeset/long-goats-live.md
- packages/io-services-cms-models/openapi/selfcare-schemas.yaml
- add AS to Selfcare institution type enum
> feat: [IOPAE-823] add AS to institution type enum

- .changeset/fresh-suits-dream.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/api-keys/api-keys.tsx
- apps/backoffice/src/components/api-keys/authorized-cidrs.tsx
- apps/backoffice/src/components/cards/card-base-container.tsx
- apps/backoffice/src/components/services/service-logo.tsx
**Service details page**: update text color and fix logo card height
- fix service logo box **height**: now is equal to the info box on the left
- update some text **color**: from t`ext.primary` to `text.secondary`
- update `authorized_cidrs` copy
Qaality assurance activity.
> [IOPAE-889] Service details: update text color and fix logo card height

- infra/src/README.md
- infra/src/container_app_job.tf
Update container app job module version
New version has new github runner base image
> [EC-103] Update container app job module

- .changeset/loud-nails-exercise.md
- apps/backoffice/src/components/api-keys/api-key-value.tsx
**ApiKeyValue**: fix gray background color which is now only present under the key value and the copy to clipboard button.
- update css property for root _MUI Box_ of **ApiKeyValue** component
Quality assurance activity
> [IOPAE-871] ApiKeyValue: fix background layout

- apps/backoffice/src/components/assistance-email-form/index.tsx
- apps/backoffice/src/pages/assistance.tsx
Change email type for assistance call from `string` to `EmailString`.
> fix: change email type for assistance call from string to EmailString

- .changeset/eighty-dolls-nail.md
- apps/backoffice/src/components/headers/top-bar.tsx
> fix: Disable support button

- .changeset/cuddly-buttons-chew.md
- apps/io-services-cms-webapp/src/synchronizer/__tests__/request-sync-legacy-handler.test.ts
- apps/io-services-cms-webapp/src/synchronizer/request-sync-legacy-handler.ts
- apps/io-services-cms-webapp/src/watchers/__tests__/on-service-history-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-service-history-change.ts
Fix default CIDRs on sync legacy
Unit Tests
> Fix default CIDRs on sync legacy

- .changeset/blue-meals-search.md
- apps/io-services-cms-webapp/src/config.ts
- apps/io-services-cms-webapp/src/lib/clients/__tests__/jira-client.test.ts
- apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
- apps/io-services-cms-webapp/src/utils/__tests__/jira-proxy.test.ts
- apps/io-services-cms-webapp/src/utils/jira-proxy.ts
Change `priority.id` type in jira create/update API call.
Unit Tests
> [IOPAE-947] Change priority.id type in jira create/update API call

- .changeset/smooth-pandas-mate.md
- apps/backoffice/src/lib/be/apim-service.ts
- apps/backoffice/src/lib/be/azure-access-token.ts
- apps/backoffice/src/lib/be/cosmos-store.ts
- apps/backoffice/src/lib/be/selfcare-client.ts
- apps/backoffice/src/lib/be/subscription-migration-client.ts
Replace React cache with singleton for all `getConfiguration...` functions
> refactor: [IOPAE-951] B4F remove react cache

- infra/src/README.md
- infra/src/webapp.tf
Fix drift detection "false positive" due to different configuration between _function app_ and _function app slot_ modules
- [update funtion app modules to latest version (7.50.0)](https://github.com/pagopa/io-services-cms/commit/50c8644c971f49c4a153a910019a5bc650e4708a)
Drift detection results in a "false positive" after deploying with a slot swap configuration
Terraform plan
> chore: patch drift detection false positive result

- .changeset/twenty-badgers-remain.md
- apps/io-services-cms-webapp/src/utils/__tests__/subscription.test.ts
- apps/io-services-cms-webapp/src/utils/feature-flag-handler.ts
- apps/io-services-cms-webapp/src/utils/subscription.ts
Handle Service Not Found on Service Ownership checks.
- Return 404 Not Found Response when Apim getSubscription call end up in 404.
> fix:[#IOPAE-964] Handle Service Not Found on Service Ownership checks

- .changeset/flat-doors-battle.md
- apps/backoffice/next.config.js
Add x-Frame-Options header to protect the application
change request after backoffice VA-PT
Local test
> [#IOPAE-956] Add x-frame-options header

- .changeset/itchy-pets-eat.md
- apps/backoffice/mocks/handlers/selfcare-handlers.ts
- apps/backoffice/package.json
- apps/backoffice/src/app/api/assistance/route.ts
- apps/backoffice/src/app/api/institutions/[institutionId]/route.ts
- apps/backoffice/src/app/api/institutions/route.ts
- apps/backoffice/src/app/api/keys/manage/[keyType]/route.ts
- apps/backoffice/src/app/api/keys/manage/cidrs/route.ts
- apps/backoffice/src/app/api/keys/manage/route.ts
- apps/backoffice/src/app/api/services/list/route.ts
- apps/backoffice/src/app/api/services/migrations/delegates/route.ts
- apps/backoffice/src/app/api/services/migrations/ownership-claims/[delegateId]/route.ts
- apps/backoffice/src/app/api/services/migrations/ownership-claims/latest/route.ts
- apps/backoffice/src/lib/be/__tests__/sanitize.test.ts
- apps/backoffice/src/lib/be/sanitize.ts
- apps/backoffice/src/lib/be/services/business.ts
- yarn.lock
Sanitize response payload in order to prevent XSS.
- Adding `xss` dependency to `backoffice`
- Adding `sanitizedNextResponseJson` function,a function which build a NextResponse with a sanitized response object
> [#IOPAE-955] Sanitize Route Handlers response objects

- .changeset/warm-spiders-tie.md
- apps/backoffice/src/app/api/auth/[...nextauth]/route.ts
Reduce session idle duration to 2 hours
> [IOPAE-845] Decrease session max idle duration on backoffice

- infra/src/00_network.tf
- infra/src/backoffice_webapp.tf
> [#IOPLT-208] Add Temp App gateway SNET routing

- infra/src/.terraform.lock.hcl
- infra/src/README.md
> [#IOPLT-208] fix tf format

- .changeset/giant-pots-walk.md
- apps/io-services-cms-webapp/src/main.ts
- infra/src/99_variables.tf
- infra/src/README.md
- infra/src/env/prod/terraform.tfvars
- infra/src/webapp.tf
> fix: [IOPAE-965] patch automatic checks

- infra/src/README.md
- infra/src/storage_account.tf
- infra/src/webapp.tf
> fix: [IOPAE-965] patch request validation queue name

- .changeset/sixty-crabs-work.md
- apps/io-services-cms-webapp/src/webservice/controllers/__tests__/upload-service-logo.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/upload-service-logo.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
Increase json request maximum size
- Increase json request maximum size to 5mb
- Better error responses on **UploadServiceLogo** AZF
> fix:[#IOPAE-974] Increase json request maximum size

- .changeset/witty-pianos-ring.md
- apps/backoffice/src/components/services/service-logo.tsx
> Fix: logo cdn refresh

- infra/src/00_network.tf
- infra/src/README.md
- infra/src/backoffice_webapp.tf
> [#IOPLT-208] Dismiss Temporary App Gw

- infra/src/README.md
- infra/src/apim_v2_api.tf
Add apim logger and diagnostic
- [add apim diagnostic](https://github.com/pagopa/io-services-cms/commit/68ae8394e039fda8bff75256174d18837a8f1a5e)
To monitor getServiceTopic cache policy behavior
> chore: [IOPAE-962] add apim diagnostic

- .opex/api_services_cms/env/prod/config.yaml
Try to bring the values to the default
> Tuning CMS API opex

- .changeset/good-tools-guess.md
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/service-validation-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/service-validation-handler.ts
Track service validation custom events
- [add telemetryClient to service-validation-handler](https://github.com/pagopa/io-services-cms/commit/bddfeb19ad71912b9622c8cff53d5a11cf59c12c)
- [IOPAE-980 fix ValidSecureChannelConfig](https://github.com/pagopa/io-services-cms/commit/640ce0a0976893fbd8a99f11f57e4eb524deb444)
> feat: [IOPAE-978] trace automatic service validation events

- .changeset/sweet-students-begin.md
- apps/io-services-cms-webapp/src/reviewer/__tests__/service-validation-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/service-validation-handler.ts
- apps/io-services-cms-webapp/src/utils/applicationinsight.ts
- apps/io-services-cms-webapp/src/utils/generic-service-retrieve.ts
- apps/io-services-cms-webapp/src/webservice/controllers/create-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/delete-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/edit-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-keys.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-lifecycle-internal.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-lifecycle.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-publication-internal.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-publication.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-services.ts
- apps/io-services-cms-webapp/src/webservice/controllers/publish-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/regenerate-service-keys.ts
- apps/io-services-cms-webapp/src/webservice/controllers/review-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/unpublish-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/upload-service-logo.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
To centralize TelemetryClient type definition, in order to prevent any type changes from having to be repeated in cascade
> refactor: replace TelemetryClient type import

- .changeset/fifty-readers-rush.md
- apps/io-services-cms-webapp/src/utils/converters/__tests__/service-lifecycle-converters.test.ts
- apps/io-services-cms-webapp/src/utils/converters/service-lifecycle-converters.ts
Avoid adding the default Sandbox Recipient when already present
Unit Tests
> [IOPAE-982] Avoid adding the default Sandbox Recipient when already present

- apps/io-services-cms-webapp/openapi.yaml
- packages/io-services-cms-models/openapi/services-cms-schemas.yaml
> [IOPAE-798] GET ServiceHistory OpenApi

- .changeset/gold-carrots-type.md
- apps/backoffice/openapi.yaml
Add `GetServiceHistory` into BackOffice backend api specification.
- BackOffice IO openapi.yaml
> [IOPAE-993] Add GetServiceHistory into BackOffice backend api specification

- apps/io-services-cms-webapp/README.md
- apps/io-services-cms-webapp/db/schema/migrations/reviewer/V8.0__create_readonly_user.sql
- apps/io-services-cms-webapp/db/schema/migrations/reviewer/V8.1__grant_readonly_user.sql
- apps/io-services-cms-webapp/db/scripts/run_flyway_on_azure.sh
- apps/io-services-cms-webapp/db/scripts/run_flyway_on_server.sh
- infra/src/99_variables.tf
- infra/src/README.md
- infra/src/database_review_credentials.tf
Add a new user to Postgres DB with only read permission
Add a flyway migration scripts
To allow other teams (such as Operation, Service Management, etc) to retrieve/monitor data
> create readonly user migrations scripts

- apps/io-services-cms-webapp/db/schema/migrations/reviewer/V8.0__create_readonly_user.sql
- apps/io-services-cms-webapp/db/scripts/run_flyway_on_azure.sh
> fix: patch flayway migration scripts

- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/mocks/handlers/backend-handlers.ts
Add `GetServiceHistory` **MSW** mock on BackOffice IO backend for frontend.
> [IOPAE-996] Add GetServiceHistory MSW mock

- infra/src/api/io_services_cms/v1/_swagger.yaml.tpl
Add GET /services/{serviceId}/history Api on infra
> [#IOPAE-992] Add GET /services/{serviceId}/history Api on infra

- .changeset/two-beans-approve.md
- apps/backoffice/src/app/api/services/[serviceId]/history/route.ts
- apps/backoffice/src/app/api/services/[serviceId]/route.ts
- apps/backoffice/src/lib/be/services/business.ts
Add GetServiceHistory Route Handler in Backoffice
> [IOPAE-994] Add GetServiceHistory Route Handler in Backoffice

- infra/src/README.md
- infra/src/container_app_job.tf
update container app module to fix infra drift detection failure
> [#IOPAE-1030]update container app module

- .changeset/rude-phones-laugh.md
- apps/io-services-cms-webapp/src/reviewer/service-validation-handler.ts
Case insensitive duplicate check
> [#IOPAE-335] Case insensitive duplicate check

- .changeset/famous-toys-knock.md
- apps/io-services-cms-webapp/src/reviewer/__tests__/service-validation-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/service-validation-handler.ts
Update duplicate rejection message
Unit test
> [IOPAE-335] Update duplicate rejection message

- .changeset/real-rivers-switch.md
- apps/io-services-cms-webapp/src/reviewer/__tests__/review-legacy-checker-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/review-legacy-checker-handler.ts
- packages/io-services-cms-models/src/service-publication/index.ts
Improve legacy review checker
- Add approvalDate when legacy ticket is approved
- Add reason when legacy ticket is rejected
Unit tests
> [#IOPAE-1040] Improve legacy review checker

- .changeset/five-llamas-search.md
- apps/io-services-cms-webapp/openapi.yaml
- packages/io-services-cms-models/openapi/services-cms-schemas.yaml
Redefine ServiceHistoryItemStatus in order to unify it.
> Unify service history status in Open Api

- .changeset/eleven-spoons-jog.md
- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/openapi.yaml
- apps/backoffice/src/components/services/service-history.tsx
Service history drawer: update history items _(shown in history right drawer)_ due to a response type update.
- Updated backoffice/openapi.yaml
- Updated **msw** mock with new `getMockServiceHistoryItem`
- Updated `ServiceHistoryComponent` with new ServiceHistoryItem status management
> Service history status unify backoffice

- .changeset/cyan-panthers-love.md
- apps/io-services-cms-webapp/src/utils/converters/__tests__/service-lifecycle-converters.test.ts
- apps/io-services-cms-webapp/src/utils/service-topic-validator.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__tests__/create-service.test.ts
- infra/src/api/io_services_cms/v1/_swagger.yaml.tpl
depends on https://github.com/pagopa/io-services-cms/pull/784
> [IOPAE-1001] Topic is now required on Service Creation/Edit

- infra/src/api/io_services_cms/v1/_swagger.yaml.tpl
Fix typo which was preventing the APIM openApi being updated
> [IOPAE-1053] Fix openApi Apim

- .changeset/little-peaches-impress.md
- apps/io-services-cms-webapp/CheckServiceDuplicationInternal/function.json
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/reviewer/service-validation-handler.ts
- apps/io-services-cms-webapp/src/utils/applicationinsight.ts
- apps/io-services-cms-webapp/src/webservice/controllers/check-service-duplication-internal.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
Add internal API(called by devPortal) in order to check for pure service duplicate on approval
> [#IOPAE-1089]add internal api to check for duplicates services

- apps/app-backend/openapi.yaml
- apps/app-backend/package.json
- apps/app-backend/tsconfig.json
- yarn.lock
Add openapi specs to `app-backend` project.
- Added openapi.yaml definitions
- Added `@pagopa/openapi-codegen-ts` dev dependency
- Added `generate` command in package.json
> [IOPAE-1079] Add openapi specs to app-backend project

- apps/app-backend/openapi.yaml
Update openapi specs for featured items: we could have both _institutions_ and/or _services_ as featured items.
> chore:Update openapi specs for featured items

- apps/app-backend/openapi.yaml
Update openapi specs for featured items
> chore:[IOPAE-1079] Update app-be openapi specs for featured items

- apps/app-backend/src/functions/__mocks__/featured-items.ts
- packages/io-services-cms-models/openapi/commons-schemas.yaml
Change PaginationResultSet openapi schema, set all parameters mandatory
> [#IOPAE-1079] PaginationResultSet mandatory parameters

- infra/_modules/ai_search/data.tf
- infra/_modules/ai_search/main.tf
- infra/_modules/ai_search/organizations.tf
- infra/_modules/ai_search/providers.tf
- infra/_modules/ai_search/services.tf
- infra/_modules/ai_search/variables.tf
- infra/_modules/networking/main.tf
- infra/prod/italynorth/.terraform.lock.hcl
- infra/prod/italynorth/data.tf
- infra/prod/italynorth/locals.tf
- infra/prod/italynorth/main.tf
- infra/prod/italynorth/providers.tf
Indices, datasources and indexers implemented and minor fixes to networking
Apart from the creation of mandatory ai search resources (indices, indexers and datasources), the networking changes are the following:
- Moved the ai search private endpoint to a dedicated common subnet
- Changed the cidr to fill the vnet block from the lowest class
Terraform plan
> EC-234 - Indices, datasources and indexers implemented 

- apps/app-backend/api/internal.yaml
- apps/app-backend/api/internal.yaml.template
Fix FeaturedService openapi schema.
- update `FeaturedService` schema
There was an indentation error.
With this fix, the `generate` command now generates correct **FeaturedService** model.
> fix: Fix FeaturedService openapi schema

- infra/src/README.md
- infra/src/database_cms.tf
There is the need to create a Services Read Model in order to use it when requesting service details from the app
- [add db and read model container for services app be](https://github.com/pagopa/io-services-cms/commit/e949a7f6fed3c1288eba2f00e28591d3be496971)
We will use read model to serve app request to isolate the two main flows: citizen-based (from app) and organization-based (from backoffice)
> [IOPAE-1080] add db and read model container for services app be

- .github/workflows/azure-deploy-manual.yaml
- .github/workflows/azure-deploy.yaml
A new Function App (App Backend) will be created, so it is necessary to automate its deployment.
- add app-backend deploy steps
Required to deploy the new App Backend Function App
> [IOPAE-1081] add app-backend deploy steps

- apps/app-backend/README.md
- apps/app-backend/src/config.ts
- infra/_modules/ai_search/outputs.tf
- infra/_modules/function_app/data.tf
- infra/_modules/function_app/main.tf
- infra/_modules/function_app/variables.tf
- infra/_modules/networking/main.tf
- infra/_modules/networking/outputs.tf
- infra/_modules/networking/variables.tf
- infra/prod/italynorth/.terraform.lock.hcl
- infra/prod/italynorth/locals.tf
- infra/prod/italynorth/main.tf
In order to adhere to the appbackend decomposition, it is necessary to create a new Function App that serves as the app's domain-specific backend for Enti&Servizi
- add new subnet for the new Function App 
- add new Function App 
- refactor: add a prefix to AI Search subnet in order to better distinguish it from each other
This resource is required to serve all requests from App IO related to Enti&Servizi domain (appbackend decomposition)
> [IOPAE-1080] add App Backend Function App

- .changeset/long-adults-buy.md
- apps/app-backend/generate-version.sh
- apps/app-backend/package.json
- apps/app-backend/src/functions/info.ts
- apps/app-backend/tsconfig.json
- yarn.lock
Fix version in info function
- Fix npm-pack-zip packge issue
- Generate a version.ts file instead of reading package.json
Local Application run
> chore: Fix Zip deploy package build

- infra/_modules/function_app/main.tf
- infra/_modules/function_app/variables.tf
- infra/_modules/networking/main.tf
- Fixed creation of storage account connected to the be function app
- Added needed delegation and service endpoints in the snet where the be is instantiated
Change is required for successful deployment of the be function app
> Iopae 1080 add services app be fn app

- .changeset/sharp-ducks-shave.md
- apps/io-services-cms-webapp/ServiceDetailLifecycleWatcher/function.json
- apps/io-services-cms-webapp/ServiceDetailPublicationWatcher/function.json
> fix watcher bindings

- .changeset/strange-wombats-appear.md
- apps/app-backend/api/internal.yaml
- apps/io-services-cms-webapp/src/detailRequestor/request-detail-handler.ts
> Fix query on request detail

- .changeset/heavy-tips-explain.md
- apps/app-backend/README.md
- apps/app-backend/src/config.ts
- apps/app-backend/src/main.ts
- apps/app-backend/src/utils/__tests__/azure-search.test.ts
- apps/app-backend/src/utils/azure-search/client.ts
- infra/_modules/function_app/main.tf
- infra/_modules/function_app/variables.tf
- infra/prod/italynorth/main.tf
In order to use the "Azure Search Aliases" needs to be used a specific Azure Search Service Version, in this pr we are introducing a confing ENV which contains it.
- Add AZURE_SEARCH_SERVICE_VERSION config
- Edit AZURE_SEARCH_ENDPOINT, now will start with `https://`
> Set Azure Search Searvice Version

- .identity/env/prod/terraform.tfvars
Fix cicd managed identity roles and resource group scope
The resource group of the infrastructure that resides in italy north has changed. Hence the CI/CD managed identity should change the scope where roles are assigned.
> EC-234 - Fix cicd managed identity roles and resource group scope

- .identity/env/prod/terraform.tfvars
- infra/_modules/ai_search/outputs.tf
> EC-234 - minor fixes to identity and aisearch output

- infra/_modules/ai_search/services.tf
Add org fiscal code ai search services
- Add org fiscal code ai search services
- removed orgName in services_publication_datasource
> [IOPAE-1080]Add org fiscal code ai search services

- infra/_modules/function_app/main.tf
Add missing `AZURE_SEARCH_SERVICE_VERSION` env config to staging slot for app-backend
> add missing  env to staging slot for app-backend

- .identity/env/prod/terraform.tfvars
Added contributor role to infra ci identity
The CI github action that deploys the infrastructure in Italy North needs additional permissions to execute the terraform plan
> Added contributor role to infra ci identity

- .identity/env/prod/terraform.tfvars
Assigned the role "Role Based Access Control Administrator" to the infrastructure CD identity
The CD must also create some azure role assignments
Currently the CD github action fails due to lack of these permissions ([example](https://github.com/pagopa/io-services-cms/actions/runs/8982000800/job/24668761670))
Terraform plan
> Add rbac management permissions to infra cd identity

- .changeset/ninety-cows-know.md
- .changeset/quick-pots-build.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/app-preview/app-preview.module.css
- apps/backoffice/src/components/app-preview/index.tsx
Added the phone frame to shows previews
In My local env
> [IOPAE-1128] Phone frame integration

- infra/prod/main.tf
Azure Search tuning after k6 Load Test
> Increase Search Unit 1->3 on Azure Search

- .changeset/cool-insects-hear.md
- apps/app-backend/api/internal.yaml
- apps/app-backend/src/functions/__tests__/search-institutions.test.ts
- apps/app-backend/src/functions/search-institutions.ts
Fix Count field on Search Institutions Response.
- Count field on `SearchInstitutions` response will now be limited by PAGINATION_MAX_OFFSET config value
Unit Tests
> [#IOPAE-1173] Fix Count field on Search Institutions Response

- .changeset/ten-pianos-collect.md
- apps/app-backend/README.md
- apps/app-backend/src/config.ts
- apps/app-backend/src/functions/__tests__/search-institutions.test.ts
- apps/app-backend/src/functions/search-institutions.ts
Refactor pagination config#### List of Changes
Unit Test
> [IOPAE-1173] Refactor pagination config

- .changeset/silver-balloons-remember.md
- apps/app-backend/api/internal.yaml
- apps/app-backend/src/functions/info.ts
- apps/app-backend/src/main.ts
- apps/app-backend/src/utils/azure-search/health-check.ts
- apps/app-backend/src/utils/cosmos-db/health-check.ts
- apps/app-backend/src/utils/health-check.ts
Add App backend health checks
- Add `CosmosDB` Health Check
- Add `AzureSearch` Health Check
- Add `AzureStorage` Health Check
> [IOPAE-1184] App backend health checks

- .changeset/tender-seahorses-bow.md
- apps/backoffice/src/lib/be/apim-service.ts
- apps/backoffice/src/lib/be/errors.ts
- packages/external-clients/src/apim-client/index.ts
Improve Apim Error
- Add More Details to Apim Error
- Minify the Apim HealthCheck error on Backoffice
> chore: Improve apim error

- .changeset/shy-papayas-thank.md
- apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
- apps/backoffice/src/lib/be/errors.ts
- packages/external-clients/src/apim-client/index.ts
> Fix Apim Error io-ts decoder

- infra/src/00_monitor_action_group.tf
- infra/src/README.md
- infra/src/storage_account_monitor.tf
- infra/src/webapp_monitor.tf
Add `Alert Rule` for `-poison` queue message presence
> Add poison queue element presency alert

- infra/src/storage_account_monitor.tf
> set poison-queue-alert severity to critical

- infra/src/00_monitor.tf
- infra/src/00_monitor_action_group.tf
- infra/src/README.md
- infra/src/monitor.tf
Add Queue diagnostic settings to IaC and fix the trigger query for poison queue alert (currently the alert is always fired)
- add Queue diagnostic settings
- fix poison queue alert query
> Add Queue diagnostic settings

- infra/src/monitor.tf
> fix window_duration property

- infra/_modules/ai_search/main.tf
Fix ai search private endpoint name by adding the service name in order to adhere the naming convention
> fix: ai search private endpoint name

- .changeset/thirty-points-play.md
- apps/app-backend/README.md
- apps/app-backend/local.settings.json.example
- apps/app-backend/src/config.ts
remove useless APPINSIGHTS_INSTRUMENTATIONKEY config reference
- remove useless APPINSIGHTS_INSTRUMENTATIONKEY config reference
This config reference is defined but unused. Furthermore, if we leave there when we change from APPINSIGHTS_INSTRUMENTATIONKEY to APPINSIGHTS_CONNECTION_STRING we should change the config reference
> Patch app be config

- .identity/.terraform.lock.hcl
- .identity/04_github_identity.tf
- .identity/env/prod/terraform.tfvars
- .identity/main.tf
Add `Role Based Access Control Administrator` role to CD infra identity
CD identity needs to add and remove roles from identities
> Add 'Role Based Access Control Administrator' role to CD infra identity

- infra/_modules/function_app/featured-institutions.json
- infra/_modules/function_app/featured-services.json
- infra/_modules/function_app/storage_account.tf
> add static contents to fn storage

- .github/workflows/azure-deploy-manual.yaml
- .github/workflows/azure-deploy.yaml
> fix deploy action fn slot name

- .github/workflows/azure-deploy-manual.yaml
- .github/workflows/azure-deploy.yaml
- infra/_modules/function_app/storage_account.tf
> revert deploy action

- .changeset/thick-chairs-sniff.md
- apps/app-backend/src/config.ts
> Fix storage account connection

- .github/workflows/azure-deploy-manual.yaml
- .github/workflows/azure-deploy.yaml
> fix deploy action

- .changeset/proud-trains-smile.md
- apps/app-backend/src/functions/featured-services.ts
> Use New Azure Storage account SDK

- .identity/env/prod/terraform.tfvars
Added Storage Blob Data Reader role to infra CI managed identity
Added Storage Blob Data Contrinutor role to infra CD managed identity
Needed to read and upload static contents to blob storage
> Added storage blob roles to ci/cd managed identities

- .changeset/fresh-coats-travel.md
- apps/app-backend/src/main.ts
Use Internal Storage Account on `GET /featured/services` and `GET /featured/institutions` AZF
Application run
> Use internal fn storage account for featured Institutions and Services

- .changeset/afraid-swans-build.md
- apps/app-backend/README.md
- apps/app-backend/api/internal.yaml
- apps/app-backend/src/config.ts
- apps/app-backend/src/functions/info.ts
- apps/app-backend/src/main.ts
- apps/app-backend/src/utils/blob-storage/health-check.ts
Clean App Backend config and old healthcheck
- Removed unused  `FEATURED_ITEMS_BLOB_CONNECTION_STRING` config param
- Removed `AzureStorage HealthCheck` which rely on the old SDK and not support Managed Identity
- Added HealthCheck for Azure Storage Blob using new SDK and ManagedIdentity
> Clean App Backend config and old healthcheck

- infra/_modules/function_app/data.tf
- infra/_modules/function_app/locals.tf
- infra/_modules/function_app/monitoring.tf
> chore: add services be fn autoscalers and basic alerts

- infra/_modules/ai_search/organizations.tf
- infra/_modules/ai_search/services.tf
It is requested to sort by name to both organizations and services indexes
- [IOPAE-1225 make name field sortable](https://github.com/pagopa/io-services-cms/pull/895/commits/bb24226c44908450f5704aa968b2c88d16aaeb0a)
- [IOPAE-1228 make name field sortable](https://github.com/pagopa/io-services-cms/pull/895/commits/cd5197d654f7c37855a1e285d8f9369be15b917d)
It is requested to sort by name to both organizations and services indexes
> Patch indexes sortable field

- infra/_modules/ai_search/organizations.tf
- infra/_modules/ai_search/services.tf
> Patch indexes alias

- .changeset/large-hotels-speak.md
- .changeset/sixty-meals-wave.md
- apps/app-backend/api/internal.yaml
- apps/app-backend/src/functions/__tests__/search-institutions.test.ts
- apps/app-backend/src/functions/__tests__/search-services.test.ts
- apps/app-backend/src/functions/search-institutions.ts
- apps/app-backend/src/functions/search-services.ts
- apps/app-backend/src/utils/azure-search/client.ts
Search Institution Services now will order by service name.
- Add Default order by service name on `GET /institutions/{institutionId}/services`
Unit tests
> [IOPAE-1227] Search service order

- .changeset/ten-shoes-search.md
- apps/app-backend/src/config.ts
- apps/app-backend/src/functions/search-services.ts
Fix pagination issues on app-backend
- Increase Default Max Pagination Offset on app-backend
- fix pagination offset and limit validation on `GET /institutions/{institutionId}/services`
> Increase Default Max Pagination Offset on app-backend

- infra/_modules/function_app/locals.tf
- infra/_modules/function_app/main.tf
Load Test results showed an overprovisioned Fn App plan
> decrease services be fn plan

- .changeset/sweet-toes-bake.md
- apps/app-backend/src/config.ts
- apps/app-backend/src/functions/__tests__/search-institutions.test.ts
- apps/app-backend/src/functions/search-institutions.ts
> fix return count value

- .opex/api_services_cms/env/prod/terraform.tfvars
> [#IOPAE-1271] update owner on dashboard

- infra/src/monitor.tf
> [IOPAE-1273] fix drift detection problem

- .changeset/cold-taxis-smell.md
- apps/app-backend/src/utils/applicationinsight/helper.ts
- infra/_modules/function_app/locals.tf
Set ApplicationInsight Sampling Percentage to 5% for `app-backend`
> [#IOPAE-1244] Set ApplicationInsight Sampling Percentage

- .changeset/tiny-hats-lie.md
- apps/backoffice/src/components/forms/controllers/text-field-array-controller.tsx
Now the IP inputs are unclickable outiside the edit mode
QA
Local env
https://github.com/pagopa/io-services-cms/assets/157382565/5232c160-4b80-4eba-906a-be0802396e1a
> [IOPAE-1181] IP inputs unclickable

- .github/workflows/code-review.yaml
- infra/src/webapp.tf
- [fix tf fn app health_check_maxpingfailures](https://github.com/pagopa/io-services-cms/commit/f908a580f7dcbef0d9d23b152bf3146c8fefe9b4)
- [fix code-review coverage report](https://github.com/pagopa/io-services-cms/commit/e320040d0d553778570cfc7a4dd2461aa9205c0d)
> Patch tf fn app health check maxpingfailures

- infra/_modules/function_app/monitoring.tf
App service Plan tuning for `app-backend`
Local Application Run and unit tests
> [#IOPAE-1272]App service Plan tuning for app-backend

- infra/_modules/ai_search/data.tf
- infra/_modules/ai_search/monitoring.tf
- [add alert on ai search latency](https://github.com/pagopa/io-services-cms/commit/8f5ea570a903877df16391d389ce9181e2c55a31)
- [add ThrottledSearchQueriesPercentage alert](https://github.com/pagopa/io-services-cms/pull/925/commits/d15e4025f21c5c35557976ef9da1bea9ec34696f)
> [IOPAE-1283] add alerts on ai search

- infra/src/99_variables.tf
- infra/src/README.md
- infra/src/env/prod/terraform.tfvars
- infra/src/webapp.tf
- infra/src/webapp_autoscale.tf
- Minimum Instances for `io-services-cms` 1 -> 3
- Default Instances for `io-services-cms` 1 -> 3
- Lower sku for `io-services-cms` PremiumV3 P1v3 -> PremiumV3 P0v3
- Enable Zone Redundancy for `io-services-cms`
- Scaling rule based on memory usage
> [IOPAE-1245] Zone Redundancy and lower sku for cms webapp plan

- infra/_modules/ai_search/monitoring.tf
change search hight latency alert severity to 2
> change search hight latency alert severity

- .changeset/orange-shirts-look.md
- apps/backoffice/src/components/dialog-provider/__TESTS__/dialog-provider.test.tsx
- apps/backoffice/src/components/dialog-provider/index.tsx
Added tests for DialogProvider component
Testing
Local env
> [IOPAE-1289] DialogProvider tests

- .changeset/swift-pots-notice.md
- apps/backoffice/src/components/drawer-provider/__tests__/drawer-base-content.test.tsx
- apps/backoffice/src/components/drawer-provider/__tests__/drawer-base.container.test.tsx
- apps/backoffice/src/components/drawer-provider/__tests__/drawer-provider.test.tsx
- apps/backoffice/src/components/drawer-provider/drawer-base-container.tsx
- apps/backoffice/src/components/drawer-provider/drawer-base-content.tsx
- apps/backoffice/src/components/drawer-provider/drawer-provider.tsx
Added tests for DrawerProvider component
Testing
Local env
> [IOPAE-1290] DrawerProvider tests

- .changeset/tall-stingrays-camp.md
- apps/backoffice/src/components/buttons/icon-button-close.tsx
- apps/backoffice/src/components/drawer-provider/__tests__/drawer-base.container.test.tsx
BackOffice IO: Fix `drawer` unit tests frontend
Fix unit tests error.
Local `dev` mode
> fix: BackOffice IO - Fix drawer unit tests

- .changeset/nine-keys-knock.md
- apps/backoffice/src/components/app-preview/components/mobile-typography.tsx
Fix MobileTypography component interface which caused an error in the BackOffice package build.
> fix: Fix MobileTypography component interface

- .github/workflows/azure-deploy-manual-itn-temp.yaml
- infra/_modules/cms_function_app/data.tf
- infra/_modules/cms_function_app/locals.tf
- infra/_modules/cms_function_app/main.tf
- infra/_modules/cms_function_app/monitoring.tf
- infra/_modules/cms_function_app/networking.tf
- infra/_modules/cms_function_app/storage_account.tf
- infra/_modules/cms_function_app/variables.tf
- infra/prod/.terraform.lock.hcl
- infra/prod/main.tf
Recreate all `io-services-cms-webapp-fn` resource into ItalyNorth region, enabling private endpoint and Zone Redundancy.
> [IOPAE-1244] io-services-cms ITN migration

- infra/_modules/cms_function_app/locals.tf
> fix snet cidr io-services-cms itn

- .changeset/small-humans-taste.md
- apps/backoffice/src/components/footer/__tests__/footer.test.tsx
Added tests for Footer component
Local env
> [IOPAE-1291] Footer tests

- packages/io-services-cms-models/src/service-publication/__tests__/index.test.ts
- packages/io-services-cms-models/src/service-publication/index.ts
a while ago we deprecated the `release` action for the fms , now we remove it along with the unit tests
> [#IOPAE-989]remove deprecated release and tests

- .github/CODEOWNERS
- .identity/03_github_environment_cd.tf
- .identity/03_github_environment_infra.tf
- .identity/04_github_identity.tf
- .identity/99_variables.tf
- .identity/env/prod/terraform.tfvars
- .identity/github_repository.tf
- CODEOWNERS
Gives roles to manage storage accounts queues
New queues created
> Update identity roles

- .changeset/tall-spoons-kick.md
- apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
> Stringify Json response error jira

- .changeset/orange-walls-shake.md
- apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
> include jira request details in case of error

- .changeset/stupid-keys-watch.md
- apps/io-services-cms-webapp/src/lib/clients/__tests__/jira-client.test.ts
- apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
- apps/io-services-cms-webapp/src/utils/__tests__/jira-proxy.test.ts
- apps/io-services-cms-webapp/src/utils/service-review-dao.ts
`ServiceReviewChecker` fix and improvements:
- Fix while exit condition `pg-client` method `executeOnPending` while loop exit condition, this in order to avoid an unnecessary loop iteration execution when the cursor is already empty.
- Better logs on `jira client`, now they includes `Jira error response`, `request body`, this to allow figuring out problems with Jira API invocation faster.
> Review checker jira fix and improvements

- .changeset/clean-years-float.md
- apps/backoffice/src/components/loaders/__tests__/loader-fullscreen.test.tsx
- apps/backoffice/src/components/loaders/__tests__/loader-skeleton.test.tsx
- apps/backoffice/src/components/loaders/loader-fullscreen.tsx
- apps/backoffice/src/components/loaders/loader-skeleton.tsx
Tests for loader component
Testing
local env
> [IOPAE-1293] Loader component tests

- .changeset/thirty-seals-drive.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
Update broken sensitive service documentation link in service create/update routes.
- update locales with correct links
> [IOPAE-1314] Update sensitive service link

- .changeset/light-mangos-pay.md
- apps/backoffice/src/components/markdown-view/__tests__/markdown-view.test.tsx
- apps/backoffice/src/components/markdown-view/markdown-view.tsx
Tests for MarkdownView component
testing
local env
> [IOPAE-1294] MarkdownView component tests

- .changeset/popular-cheetahs-beam.md
- apps/backoffice/src/components/notification/__tests__/notification.test.tsx
- apps/backoffice/src/components/notification/index.tsx
Tests for notification component
Testing
local env
> [IOPAE-1295] Notification component tests

- .changeset/mighty-games-poke.md
- apps/io-services-cms-webapp/src/webservice/controllers/__tests__/create-service.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__tests__/get-services.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/create-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-services.ts
Reverts pagopa/io-services-cms#991
> Revert "refactor: remove useless getUserByEmail calls"

- .changeset/hungry-shrimps-jump.md
- apps/io-services-cms-webapp/src/config.ts
- apps/io-services-cms-webapp/src/lib/middlewares/__tests__/selfcare-user-groups-middleware.test.ts
- apps/io-services-cms-webapp/src/lib/middlewares/selfcare-user-groups-middleware.ts
- apps/io-services-cms-webapp/src/utils/__tests__/comma-separated-list.test.ts
- apps/io-services-cms-webapp/src/utils/comma-separated-list.ts
Create a new middleware to get selfcare user groups from header
- [create SelfcareUserGroupsMiddleware](https://github.com/pagopa/io-services-cms/commit/5a8ebea1f52694d981a32d73fc2c2f3b1952dd26)
- [fix CommaSeparatedListOf typing](https://github.com/pagopa/io-services-cms/commit/911718c4b5655c18817eb1e554df6adde7c0277d)
- [fix BACKOFFICE_INTERNAL_SUBNET_CIDRS type](https://github.com/pagopa/io-services-cms/commit/8a5f0fbcbbc53a6444fc1cf20d2b811c484dcb6d)
Preparatory for the implementation of Use Cases related to Selfcare Groups management
Unit Tests
> [IOPAE-1350] selfcare user groups middleware

- .changeset/moody-keys-accept.md
- apps/app-backend/api/internal.yaml
- apps/io-services-cms-webapp/src/utils/check-service.ts
- apps/io-services-cms-webapp/src/webservice/controllers/__tests__/regenerate-service-keys.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-service-keys.ts
- apps/io-services-cms-webapp/src/webservice/controllers/regenerate-service-keys.ts
- apps/io-services-cms-webapp/src/webservice/index.ts
> [IOPAE-1372] fix regenerate service keys on deleted services

- apps/backoffice/package.json
- apps/backoffice/src/app/api/services/[serviceId]/history/route.ts
- apps/backoffice/turbo.json
Fix path in `clean:selfcare-api-models` yarn script and `generate:selfcare-api-models` turbo task.
> fix path for clean and generation selfcare-api-models in backoffice

- .changeset/eighty-pants-return.md
- apps/backoffice/openapi.yaml
- apps/backoffice/src/app/api/institutions/[institutionId]/groups/__tests__/route.test.ts
- apps/backoffice/src/app/api/institutions/[institutionId]/groups/route.ts
- apps/backoffice/src/lib/be/__tests__/institutions.test.ts
- apps/backoffice/src/lib/be/institutions/business.ts
- apps/backoffice/src/lib/be/institutions/selfcare.ts
- apps/backoffice/src/lib/be/selfcare-client.ts
- fix optional query param decode
- change `limit` and `offset` to `size` and `page` to match selfcare model
- add `PaginationResult` model in openapi
- fix mapping function
1. unit test
2. local backoffice start
> fix:[IOPAE-1373] GetInstitutionsGroups API

- .changeset/curvy-buses-occur.md
- apps/io-services-cms-webapp/src/utils/__tests__/synchronizer.test.ts
- apps/io-services-cms-webapp/src/utils/synchronizer.ts
- apps/io-services-cms-webapp/src/watchers/on-service-history-change.ts
Add a new Label to skip sync to the legacy a service
> [IOPAE-1397] Add skip sync to legacy label

- .changeset/chilled-bikes-sing.md
- apps/backoffice/src/app/api/services/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/route.ts
- apps/backoffice/src/lib/be/services/business.ts
- apps/backoffice/types/next-auth.d.ts
Add authorization logic to create service handler
- [add authorization logic to create service handler](https://github.com/pagopa/io-services-cms/commit/863f5dda10f032c45a5d8a8f76046cd927e30864)
- [lint fix](https://github.com/pagopa/io-services-cms/commit/257db68f7953e609788cd3eb0fa50b0eca05c077)
To be compliant with functional requirements
Unit Tests
> [IOPAE-1444] be authz group service relationship

- .changeset/clever-shirts-look.md
- apps/backoffice/src/app/api/institutions/[institutionId]/groups/route.ts
- apps/backoffice/src/app/api/services/[serviceId]/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/[serviceId]/route.ts
- apps/backoffice/src/app/api/services/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/route.ts
- apps/backoffice/src/app/api/subscriptions/route.ts
- apps/backoffice/src/lib/be/__tests__/authz.test.ts
- apps/backoffice/src/lib/be/__tests__/institutions.test.ts
- apps/backoffice/src/lib/be/__tests__/req-res-utils.test.ts
- apps/backoffice/src/lib/be/authz.ts
- apps/backoffice/src/lib/be/institutions/business.ts
- apps/backoffice/src/lib/be/req-res-utils.ts
Add authz logic related to service-group relationship
- [refactor: rename isBackofficeUserAdmin to isAdmin](https://github.com/pagopa/io-services-cms/commit/36430a1fe47d974b6c03076a6f84c39b08e6ae74)
- [add parseBody utility fn](https://github.com/pagopa/io-services-cms/commit/1d37ae76ad59cc37af8c2485c1aee49aea7b610e)
- [refactor: move groupExists fn to institution/business.ts](https://github.com/pagopa/io-services-cms/commit/dbb1d24b5951a187f06b31e141c0d012c17deff7)
- [refactor: use parseBody and groupExists utilities fn](https://github.com/pagopa/io-services-cms/commit/bb895d22dcecd315595812b566ef1db5ef04f027)
- [manage group authz on update service handler](https://github.com/pagopa/io-services-cms/commit/2033d21a41f0459fc30e2301d4fa442a3530f911)
Unit Tests
> [IOPAE-1451] be authz group edit service

- .changeset/calm-bananas-lie.md
- apps/backoffice/src/lib/be/__tests__/services.test.ts
- apps/backoffice/src/lib/be/services/business.ts
- apps/backoffice/src/lib/be/services/utils.ts
Resolve group name from its id and return it to the client
[retrive service list: resolve group name](https://github.com/pagopa/io-services-cms/commit/8a5314161d17aeb09bdfc14326a1c5d2bfef9863)
Unit Tests and local Dev Run
> [IOPAE-1351] get service handler return group name

- .changeset/stale-vans-dream.md
- apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
Bugfix related to improper input parameter passed to manage subscription creation
- [fix manage subscription creation](https://github.com/pagopa/io-services-cms/commit/b567ba7ff313c5260f5016de9502f74cb9a4766c)
Unit Test
> fix: [IOPAE-1461] bo manage key auth error

- .changeset/poor-bags-wave.md
- apps/backoffice/src/app/api/services/[serviceId]/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/[serviceId]/route.ts
- apps/backoffice/src/app/api/services/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/route.ts
- apps/backoffice/src/config/index.ts
- apps/backoffice/src/lib/be/__tests__/services.test.ts
- apps/backoffice/src/lib/be/services/business.ts
enable selfcare group-based authz by a feature flag
- [add selfcare group-based authz feature flag](https://github.com/pagopa/io-services-cms/commit/af430dadb6edb509234649398d5f02d10bc9ad14)
- Unit test
- Run locally connected to PROD resources
> fix:[IOPAE-1472] add selfcare group-based authz feature flag

- CODEOWNERS
add green unit to codeowners infra , this was suggested by team cloud
> add green unit to codeowners infra

- .changeset/fifty-pandas-grab.md
- apps/backoffice/openapi.yaml
- apps/backoffice/src/app/api/subscriptions/__tests__/route.test.ts
- apps/backoffice/src/app/api/subscriptions/route.ts
- apps/backoffice/src/lib/be/__tests__/institutions.test.ts
- apps/backoffice/src/lib/be/institutions/business.ts
- apps/backoffice/src/lib/be/subscriptions/__tests__/business.test.ts
- apps/backoffice/src/lib/be/subscriptions/business.ts
- packages/external-clients/src/apim-client/__tests__/apim-filters.test.ts
- packages/external-clients/src/apim-client/apim-filters.ts
> [IOPAE-1577] add type filter to getManageSubscriptions

- .changeset/purple-buses-exercise.md
- apps/io-services-cms-webapp/src/watchers/__tests__/on-service-detail-lifecycle-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-service-detail-lifecycle-change.ts
- [avoid group info propagation to app-backend](https://github.com/pagopa/io-services-cms/commit/53f2c44a166c22ce1f3897ab22604a9d0386d75e)
There is no need to propagate authz service-group relationship info to app-backend
Unit Tests
> [IOPAE-1476] avoid group info propagation to app-backend

- .changeset/violet-schools-jog.md
- apps/backoffice/openapi.yaml
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
- apps/backoffice/src/app/api/subscriptions/[subscriptionId]/cidrs/__tests__/route.test.ts
- apps/backoffice/src/app/api/subscriptions/[subscriptionId]/cidrs/route.ts
- apps/backoffice/src/app/api/subscriptions/[subscriptionId]/keys/[keyType]/__tests__/route.test.ts
- apps/backoffice/src/app/api/subscriptions/[subscriptionId]/keys/[keyType]/route.ts
- apps/backoffice/src/app/api/subscriptions/[subscriptionId]/keys/__tests__/route.test.ts
- apps/backoffice/src/app/api/subscriptions/[subscriptionId]/keys/route.ts
- apps/backoffice/src/lib/be/__tests__/authz.test.ts
- apps/backoffice/src/lib/be/authz.ts
Add missing getManageSubscriptionAuthorizedCidrs and updateManageSubscriptionAuthorizedCidrs handlers
Unit Tests
> [IOPAE-1584] bff add manage group sub cidrs endpoints

- .changeset/thick-shirts-fly.md
- apps/backoffice/openapi.yaml
- apps/backoffice/src/app/api/services/group-unbound/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/group-unbound/route.ts
- apps/backoffice/src/lib/be/__tests__/apim-service.test.ts
- apps/backoffice/src/lib/be/__tests__/services.test.ts
- apps/backoffice/src/lib/be/apim-service.ts
- apps/backoffice/src/lib/be/services/__tests__/apim.test.ts
- apps/backoffice/src/lib/be/services/__tests__/cosmos.test.ts
- apps/backoffice/src/lib/be/services/apim.ts
- apps/backoffice/src/lib/be/services/business.ts
- apps/backoffice/src/lib/be/services/cosmos.ts
- apps/io-services-cms-webapp/src/webservice/controllers/get-services.ts
- packages/io-services-cms-models/src/lib/__tests__/store.cosmos.test.ts
- packages/io-services-cms-models/src/lib/fsm/store.cosmos.ts
- packages/io-services-cms-models/src/lib/fsm/store.memory.ts
- packages/io-services-cms-models/src/lib/fsm/types.ts
- [add new getGroupUnboundedServicesByIds query](https://github.com/pagopa/io-services-cms/commit/c731efe1d4bfda4f695ef791678aa8f644923ea1)
- [add retrieve group-unbounded services handler](https://github.com/pagopa/io-services-cms/commit/479449a4cc1bf998f6292951feaf5b5a72e78a96)
- [refactor: use internal checkSourceIp](https://github.com/pagopa/io-services-cms/commit/566eef92a15058e5d74e5079137e0943cfca5dad)
> [IOPAE-1592] get group-unbounded services

- .changeset/three-turkeys-clap.md
- apps/backoffice/src/components/services/__tests__/adapters.test.ts
- apps/backoffice/src/components/services/adapters.ts
> [IOPAE-1620] Fix BackOffice IO service cta

- .changeset/tame-sheep-begin.md
- apps/backoffice/openapi.yaml
- apps/backoffice/src/app/api/services/[serviceId]/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/[serviceId]/route.ts
- apps/backoffice/src/app/api/services/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/group-unbound/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/group-unbound/route.ts
- apps/backoffice/src/app/api/services/route.ts
- apps/backoffice/src/lib/be/__tests__/services.test.ts
- apps/backoffice/src/lib/be/services/__tests__/business.test.ts
- apps/backoffice/src/lib/be/services/__tests__/cosmos.test.ts
- apps/backoffice/src/lib/be/services/business.ts
- apps/backoffice/src/lib/be/services/cosmos.ts
- packages/io-services-cms-models/src/lib/__tests__/store.cosmos.test.ts
- packages/io-services-cms-models/src/lib/fsm/store.cosmos.ts
- packages/io-services-cms-models/src/lib/fsm/store.memory.ts
- packages/io-services-cms-models/src/lib/fsm/types.ts
Add and manage services bulkPatch operation
- [add role check to getGroupUnboundedServices handler](https://github.com/pagopa/io-services-cms/commit/a99ea2c73041d0408b22ec3eb81935d4e9edd0a9)
- [add bulkPatch to store](https://github.com/pagopa/io-services-cms/commit/fcaa581eae6e9364645c65940a989c36a6024383)
- [add bulkPatch business logic](https://github.com/pagopa/io-services-cms/commit/48fe10cf8d7f53ad58612d5c4c50cef58ad948eb)
- [add bulkPatch API operation and handler](https://github.com/pagopa/io-services-cms/commit/cdc49ac11677b74183edc494a8638c2117b6c82f)
- [fix patchService handler](https://github.com/pagopa/io-services-cms/commit/19f52573c7f6ad38b500e6a4a6da8d7fe532f90b)
- [fix selcGroups setting when user is admin](https://github.com/pagopa/io-services-cms/pull/1088/commits/4cb6b2 …
> [IOPAE-1589] bulk patch

- .changeset/big-rice-battle.md
- apps/io-services-cms-webapp/src/watchers/on-selfcare-group-change.ts
> [IOPAE-1641] log eh trigger execution

- .changeset/lazy-wombats-explain.md
- apps/io-services-cms-webapp/src/lib/azure/misc.ts
- apps/io-services-cms-webapp/src/watchers/on-selfcare-group-change.ts
> [IOPAE-1641]  log context eh trigger execution

- .changeset/calm-wombats-join.md
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/watchers/on-selfcare-group-change.ts
> [IOPAE-1641] eh trigger custom retry

- .changeset/fluffy-rats-pull.md
- apps/backoffice/openapi.yaml
- apps/backoffice/package.json
- apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
- apps/backoffice/src/app/api/subscriptions/__tests__/route.test.ts
- apps/backoffice/src/app/api/subscriptions/route.ts
- apps/backoffice/src/lib/be/__tests__/apim-service.test.ts
- apps/backoffice/src/lib/be/__tests__/institutions.test.ts
- apps/backoffice/src/lib/be/__tests__/selfcare-client.test.ts
- apps/backoffice/src/lib/be/__tests__/services.test.ts
- apps/backoffice/src/lib/be/apim-service.ts
- apps/backoffice/src/lib/be/errors.ts
- apps/backoffice/src/lib/be/institutions/__tests__/selfcare.test.ts
- apps/backoffice/src/lib/be/institutions/business.ts
- apps/backoffice/src/lib/be/institutions/selfcare.ts
- apps/backoffice/src/lib/be/selfcare-client.ts
- apps/backoffice/src/lib/be/services/business.ts
- apps/backoffice/src/lib/be/subscriptions/__tests__/business.test.ts
- apps/backoffice/src/lib/be/subscriptions/business.ts
- apps/backoffice/turbo.json
- packages/external-clients/src/apim-client/__tests__/index.test.ts
- packages/external-clients/src/apim-client/index.ts
> [IOPAE-1380] manage subscription display name

- .changeset/healthy-pants-love.md
- apps/io-services-cms-webapp/SelfcareGroupWatcher/function.json
- apps/io-services-cms-webapp/host.json
- apps/io-services-cms-webapp/src/__tests__/main.test.ts
- apps/io-services-cms-webapp/src/main.ts
- apps/io-services-cms-webapp/src/utils/__tests__/sync-group-utils.test.ts
- apps/io-services-cms-webapp/src/utils/sync-group-utils.ts
- apps/io-services-cms-webapp/src/watchers/__tests__/on-selfcare-group-change.test.ts
- apps/io-services-cms-webapp/src/watchers/on-selfcare-group-change.ts
When there is an error during selfcare group synching, we put the failed event to a DLQ
- [handle DLQ](https://github.com/pagopa/io-services-cms/pull/1113/commits/f4f1cd83aae724d6c8b86dc4739d33b2da765e60)
Unit Tests and locally run
> [IOPAE-1645] handle DLQ

- apps/backoffice/openapi.yaml
The OpenAPI specification for the new api that check the existence of at least one group-unbounded service
[OpenAPI definition for checking the existence of a group unbounded se…](https://github.com/pagopa/io-services-cms/commit/e5e356c1140e35fece3a4247e91bddbe91528bf7)
> [IOPAE-1678] Backoffice OpenAPI check group unbound service existence

- apps/backoffice/openapi.yaml
- apps/backoffice/src/components/api-keys/api-key-create-update/api-key-create-update.tsx
> [IOPAE-1677] getInstitutionGroups API definition

- apps/backoffice/openapi.yaml
> [IOPAE-1674] add delete subscritpion definition to openapi

- .changeset/strange-queens-allow.md
- apps/io-services-cms-webapp/src/config.ts
- apps/io-services-cms-webapp/src/utils/applicationinsight.ts
> try to use only default ai client

- .changeset/shaggy-poets-change.md
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-groups-empty-state.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-groups.tsx
- apps/backoffice/src/pages/keys/index.tsx
Added empty state in ApiKeys page for operator users in one or more group without any group ApiKey
**Note:** _watch screenshot below to better appreciate developments._
> [IOPAE-1366] Added empty state in ApiKeys page for operator users in one or more group without any group ApiKey

- .changeset/gold-rocks-learn.md
- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/api-keys/api-keys-card/api-keys-card.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group-tag.tsx
- apps/backoffice/src/pages/services/index.tsx
Added **Group** column on **Services Page** `TableView`.
Need to have, if present, the group associated to a service.
> [IOPAE-1363] Added Group column on Services Page table view

- .changeset/wicked-cougars-jog.md
- apps/backoffice/mocks/handlers/backend-handlers.ts
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-groups.tsx
Added **delete** ApiKey Group action on _**ApiKeys**_ page.
**Note 1:** _Follow commits history to better understand developments._
**Note 2:** _Watch video below to better appreciate developed use case._
Admin users must delete Group ApiKeys
https://github.com/user-attachments/assets/e266e6d6-03e2-402d-b52d-eb1dcc402dda
> [IOPAE-1715] Added delete ApiKey Group action

- .changeset/brave-planes-breathe.md
- apps/backoffice/src/app/api/subscriptions/[subscriptionId]/__tests__/route.test.ts
- apps/backoffice/src/app/api/subscriptions/[subscriptionId]/route.ts
- apps/backoffice/src/lib/be/errors.ts
- apps/backoffice/src/lib/be/subscriptions/__tests__/business.test.ts
- apps/backoffice/src/lib/be/subscriptions/business.ts
- packages/external-clients/src/apim-client/__tests__/index.test.ts
- packages/external-clients/src/apim-client/index.ts
[added delete subscription api](https://github.com/pagopa/io-services-cms/commit/8dd6f5570db182f1e8134123ecf77a58a96d6865)
[added unit test](https://github.com/pagopa/io-services-cms/commit/392b6e798cc38db3112314085d4b17d28d41ad76)
[fix function signature](https://github.com/pagopa/io-services-cms/pull/1137/commits/3d70a283126dfc898c1e8e016fd3fde643af49bd)
[fix error messages](https://github.com/pagopa/io-services-cms/pull/1137/commits/0505fd3d309f7e6c7e59ce31dd3eea5589498a57)
Required to delete a manage group subscription for an admin
unit tests
> [IOPAE-1674] backoffice delete subscription api

- .changeset/sharp-kangaroos-check.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/services/adapters.ts
- apps/backoffice/src/components/services/service-info.tsx
- apps/backoffice/src/pages/services/[serviceId].tsx
- apps/backoffice/src/types/service.ts
Added **_group_** information in service details page.
Need to view info about service related group.
**Use Case 1:** Service bounded to a Group
**Use Case 2:** Unbounded service
> [IOPAE-1771] Added group information in service details page

- .changeset/empty-toes-tap.md
- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/mocks/data/selfcare-data.ts
- apps/backoffice/mocks/handlers/backend-handlers.ts
- apps/backoffice/openapi.yaml
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/dialog-provider/index.tsx
- apps/backoffice/src/components/groups/associate-group-to-service/associate-group-to-service.tsx
- apps/backoffice/src/components/groups/associate-group-to-service/index.tsx
- apps/backoffice/src/components/groups/group-info-tag/group-info-tag.tsx
- apps/backoffice/src/components/groups/group-info-tag/index.tsx
- apps/backoffice/src/components/services/service-info.tsx
- apps/backoffice/src/pages/services/[serviceId].tsx
Added _group association_ action in _**ServiceDetails**_ page.
_Follow commits history to better understand developments._
_**Note:** Watch videos and screenshots below to better appreciate developments._
Need to associate/change group for a service.
**Note:** _all data is mocked and therefore not consistent in subsequent fetch actions._
**USE CASE 1 - _Admin user, associate unbounded service:_**
https://github.com/user-attachments/assets/509ba97c-77af-4aa3-bd30-d86ea8437f15
**USE CASE 2 - _Admin user, edit/change service group association:_**
https://github.com/user-attachments/assets/18cd67f7-6c8e-413d-9999-c55236460646
**USE CASE 3 - _Operator user, unbounded service info:_**
**USE CASE 3 - _Operator user, service group info:_**
> [IOPAE-1772] service group associate

- .changeset/funny-turtles-switch.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/forms/controllers/select-controller.tsx
- apps/backoffice/src/components/forms/form-step-section-wrapper.tsx
- apps/backoffice/src/components/services/__tests__/adapters.test.ts
- apps/backoffice/src/components/services/adapters.ts
- apps/backoffice/src/components/services/service-create-update/service-builder-step-3.tsx
- apps/backoffice/src/components/services/service-create-update/service-create-update.tsx
- apps/backoffice/src/components/services/service-create-update/service-group-selector.tsx
- apps/backoffice/src/pages/services/[serviceId]/edit-service.tsx
- apps/backoffice/src/pages/services/new-service.tsx
- apps/backoffice/src/types/service.ts
Added group selection in service create funnel.
_Follow commits history to better understand developments.
Watch videos below to better appreciate use cases._
Need to associate a service to a group in creation funnel.
**USE CASE 1:** Admin user
https://github.com/user-attachments/assets/7fc07c8e-fedb-4d96-ac8c-e56f854c656e
**USE CASE 2:** Operator user in one group
https://github.com/user-attachments/assets/70b6374a-d9d2-4507-9d85-9afc93bfc3fa
**USE CASE 3:** Operator user in more groups
https://github.com/user-attachments/assets/ba49a09c-a562-4fb0-b598-7d748855a828
> [IOPAE-1371] Added group selection in service create funnel

- .changeset/happy-cows-turn.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-groups.tsx
Added ApiKey Group section **pagination** on ApiKey page.
**Note:** _watch video below to better appreciate developments._
Need to manage paginated group api keys.
https://github.com/user-attachments/assets/21988ffc-3c8f-4c9e-bb9f-ae453e4a39e1
> [IOPAE-1790] Added ApiKey Group section pagination on ApiKey page

- .changeset/witty-flowers-listen.md
- apps/backoffice/src/app/api/services/__tests__/route.test.ts
- apps/backoffice/src/app/api/services/route.ts
- apps/backoffice/src/lib/be/services/__tests__/business.test.ts
- apps/backoffice/src/lib/be/services/business.ts
[refactor wrapping logic](https://github.com/pagopa/io-services-cms/commit/76fc3e34bd2b33b1d75a59644391caaeaf041434)
[added unit tests](https://github.com/pagopa/io-services-cms/commit/34580ed8dfebce9df5b06e67921a899643a044cb)
unit test
> [IOPAE-1778] backoffice refactoring wrapping logic patch

- .changeset/rare-pigs-join.md
- apps/backoffice/src/components/forms/controllers/select-controller.tsx
- apps/backoffice/src/components/services/service-create-update/service-group-selector.tsx
Added clearable behaviour to group selector in service create funnel.
_**Note:** Watch video below to better appreciate developments._
https://github.com/user-attachments/assets/6ec15b10-d32f-4183-860c-dcadd4bea497
> [IOPAE-1839] Added clearable behaviour to group selector in service create funnel

- .changeset/eight-shrimps-build.md
- apps/backoffice/src/lib/be/services/business.ts
[fix service detail api](https://github.com/pagopa/io-services-cms/commit/e641147754f2382a10508c7e56f41969023c77d5)
a bug found when the user tries to call the service detail api and  is not an admin and belongs to at least one selfcare group
Unit test
> [IOPAE-1849] backoffice fix service detail api

- .changeset/forty-tigers-breathe.md
- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-groups-empty-state.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/button-generate-api-keys-group.tsx
- apps/backoffice/src/components/groups/button-associate-group.tsx
- apps/backoffice/src/components/groups/group-info-tag/group-info-tag.tsx
- apps/backoffice/src/layouts/app-layout.tsx
- apps/backoffice/src/pages/groups/associate.tsx
- apps/backoffice/src/pages/services/index.tsx
- apps/backoffice/src/utils/__tests__/auth-util.test.ts
- apps/backoffice/src/utils/auth-util.ts
Operator cannot access to services bounded to inactive _(SUSPENDED, DELETED)_ Selfcare groups.
> [IOPAE-1838] Operator users cannot access to services bounded to inactive group

- .changeset/beige-ways-fold.md
- apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
[remove group's feature from test institution](https://github.com/pagopa/io-services-cms/commit/54ad28cae8bea3eec63a8d37e647cd11f3397b1d)
> remove group's feature from test institution

- .changeset/itchy-monkeys-matter.md
- apps/backoffice/src/components/api-keys/api-keys-card/api-keys-card.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-groups-empty-state.tsx
- apps/backoffice/src/components/forms/controllers/select-controller.tsx
- apps/backoffice/src/components/services/service-create-update/service-builder-step-3.tsx
- apps/backoffice/src/components/services/service-create-update/service-create-update.tsx
- apps/backoffice/src/components/services/service-create-update/service-group-selector.tsx
- apps/backoffice/src/utils/__tests__/auth-util.test.ts
- apps/backoffice/src/utils/auth-util.ts
Avoid clearable SelectController when disabled, general improvements on group selector for create service form.
Integration Tests.
> Fix: [IOPAE-1871] Avoid clearable SelectController when disabled, general improvements on group selector for create service form

- .changeset/large-guests-invent.md
- apps/backoffice/mocks/handlers/backend-handlers.ts
- apps/backoffice/src/components/groups/associate-group-to-service/associate-group-to-service.tsx
- apps/backoffice/src/components/services/service-info.tsx
Update patchService response codec on client fetch.
Need to change from a 200 http response _(with response payload)_ to 204 _(no response)_.
> [IOPAE-1875] Update patchService response codec on client fetch

- .changeset/ten-numbers-call.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/pages/services/index.tsx
Added control for active groups on create service button for operator in at least one group.
_**Note:** watch video below to better appreciate developments._
Need to check active group existence for operator in at least one group.
https://github.com/user-attachments/assets/66bf3240-81fd-4404-aa61-8f56c79b7be5
> [IOPAE-1874] crate service check groups

- .changeset/little-colts-serve.md
- apps/backoffice/src/app/api/subscriptions/__tests__/route.test.ts
- apps/backoffice/src/app/api/subscriptions/route.ts
- apps/backoffice/src/config/constants.ts
- apps/backoffice/src/lib/be/errors.ts
- apps/backoffice/src/lib/be/subscriptions/__tests__/business.test.ts
- apps/backoffice/src/lib/be/subscriptions/business.ts
[added Precondition Failed error handler on upsert subscription](https://github.com/pagopa/io-services-cms/commit/cbfb94c64650716b3b4c98360c1967d31b8c3748)
Unit test
> Precondition failed error management

- .changeset/tidy-stingrays-grab.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/api-keys/api-keys-card/api-keys-card.tsx
- apps/backoffice/src/components/api-keys/api-keys-couple.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group-tag.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-groups.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/button-generate-api-keys-group.tsx
- apps/backoffice/src/components/api-keys/api-keys.tsx
- apps/backoffice/src/components/api-keys/api-single-key.tsx
- apps/backoffice/src/components/services/service-group-tag.tsx
- apps/backoffice/src/pages/keys/index.tsx
- apps/backoffice/src/pages/services/[serviceId].tsx
- apps/backoffice/src/utils/mix-panel.ts
Updated **_ApiKey_** copy.
Updated ApiKey copy:
- change "Rotate" to "Regenerate"
- change "Api Key Manage" to "Api key Manage Master"
- change "Api Key di Gruppo" to "Api Key Manage Group"
- change  "Api Key" to "Api Key Use" into service details page
Local `dev` mode.
> [IOPAE-1911] Updated Api Key copy

- .changeset/beige-plants-do.md
- apps/io-services-cms-webapp/avro/services-history.json
- apps/io-services-cms-webapp/avro/services-lifecycle.json
- apps/io-services-cms-webapp/src/utils/ingestion/formatter/__tests__/service-history-avro-formatter.test.ts
- apps/io-services-cms-webapp/src/utils/ingestion/formatter/__tests__/service-lifecycle-avro-formatter.test.ts
- apps/io-services-cms-webapp/src/utils/ingestion/formatter/service-history-avro-formatter.ts
- apps/io-services-cms-webapp/src/utils/ingestion/formatter/service-lifecycle-avro-formatter.ts
> [IOPAE-1929] send group_id to DataLake

- .changeset/healthy-llamas-cry.md
- apps/backoffice/src/pages/index.tsx
Update apikey group banner link.
> [IOPAE-1941] Update apikey group banner link

- apps/app-backend/package.json
- yarn.lock
update azure functions core tools for app backend
> fix : app be update azure functions core tools

- .changeset/dry-badgers-push.md
- .changeset/tiny-beds-buy.md
- apps/app-backend/api/internal.yaml
- apps/app-backend/api/internal.yaml.template
- apps/app-backend/src/functions/__mocks__/get-service-by-id-mock.ts
- apps/app-backend/src/functions/__tests__/get-service-by-id.test.ts
- apps/app-backend/src/functions/get-service-by-id.ts
update openapi definition for getServiceById
> [IOPAE-1921] update open api

- .changeset/dull-ladybugs-pump.md
- apps/backoffice/src/pages/index.tsx
Updated Group ApiKey info banner link.
Local `dev` mode.
> [IOPAE-1964] Updated Group ApiKey info banner link

- .changeset/bright-falcons-greet.md
- apps/app-backend/src/utils/__tests__/azure-search.test.ts
- apps/app-backend/src/utils/azure-search/client.ts
- apps/app-backend/src/utils/azure-search/health-check.ts
Perform a getDocumentCount intead of a full text search within check probe
- add `getDocumentCount` to `AzureSearchClient`
- add unit tests
- replace `fullTextSearch` with `getDocumentCount` within `makeAzureSearchHealthCheck`
> patch: fix app be health-check

- apps/app-backend/package.json
- apps/app-backend/src/utils/__tests__/blob-storage.test.ts
- apps/backoffice/package.json
- apps/backoffice/vitest.config.react.ts
- apps/io-services-cms-webapp/package.json
- package.json
- packages/external-clients/package.json
- packages/io-services-cms-models/package.json
- yarn.lock
- bump vitest to 3.1.2
- "hoist" vitest deps
> bump vitest to 3.1.2

- .changeset/witty-mice-listen.md
- apps/backoffice/src/components/api-keys/api-key-create-update/api-key-create-update.tsx
- apps/backoffice/src/components/api-keys/api-keys-couple.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group.tsx
- apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-groups.tsx
- apps/backoffice/src/components/api-keys/api-keys.tsx
- apps/backoffice/src/components/api-keys/api-single-key.tsx
- apps/backoffice/src/components/cards/card-rows.tsx
- apps/backoffice/src/components/groups/associate-group-to-service/associate-group-to-service.tsx
- apps/backoffice/src/components/groups/associate-groups-create-update/associate-groups-create-update.tsx
- apps/backoffice/src/components/groups/button-associate-group.tsx
- apps/backoffice/src/components/groups/group-info-tag/group-info-tag.tsx
- apps/backoffice/src/components/services/service-info.tsx
- apps/backoffice/src/components/services/subscriptions-migration/migration-manager.tsx
- apps/backoffice/src/hooks/use-fetch.ts
- apps/backoffice/src/pages/groups/associate.tsx
- apps/backoffice/src/pages/keys/index.tsx
- apps/backoffice/src/pages/keys/new-group-api-key.tsx
- apps/backoffice/src/pages/services/[serviceId].tsx
- apps/backoffice/src/pages/services/[serviceId]/edit-service.tsx
- apps/backoffice/src/pages/services/new-service.tsx
- apps/backoffice/src/types/api-key.ts
- apps/backoffice/src/utils/mix-panel.ts
Track events for new Group ApiKey features on MixPanel.
- update useFetch hook 5f5e623d51eb4ec6a534dc07014f938c60e824b0
- update mix-panel util functions 8a7955751c227298a95f34f95028a878f090df96
- fix service create/update end event result 38feab1d2106352ef63deabed4392d3b4fe6dc46
- add group api key tracking event implementation 7c8293aa0ee4369ef373dcf8ae06d9b15354d15c
Need to track user experience on BackOffice IO for new Group ApiKey feature.
> [IOPAE-1803] Track group apikey events on mixpanel

- .changeset/nice-toes-glow.md
- apps/io-services-cms-webapp/src/webservice/controllers/__tests__/create-service.test.ts
- apps/io-services-cms-webapp/src/webservice/controllers/create-service.ts
- packages/io-services-cms-models/src/service-lifecycle/index.ts
[fix override category on special services](https://github.com/pagopa/io-services-cms/commit/25c15f13d085c189e76eb9d3447b8f550b4be648)
local environment connected to prod resources and unit tests
> [IOPAE-1953] special services avoid override field category

- .devcontainer/devcontainer.json
- .vscode/settings.json
- apps/app-backend/package.json
- apps/io-services-cms-webapp/package.json
- yarn.lock
Add basic devcontainer config
- ddd basic devcontainer config
> add devcontainer config

- .changeset/two-coats-brush.md
- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/mocks/handlers/backend-handlers.ts
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/pages/delegated-institutions.tsx
Added delegated institutions basic table view.
**Note:** watch video below to better appreciate ux/ui result _(first step)_.
Need to show the list of delegated institutions.
https://github.com/user-attachments/assets/967225ed-1f5c-49ef-b046-9d1f92be7a1b
> [IOPAE-2048] Added delegated institutions basic table view

- .changeset/spotty-apes-battle.md
- apps/io-services-cms-webapp/src/utils/ingestion/formatter/activation-avro-formatter.ts
[conversion modifiedAt field into millis](https://github.com/pagopa/io-services-cms/commit/f8ab3e5449d552998605abce93584d1f3775c507)
> [IOPAE-2075] fix ingestion activations timestamp format

- .changeset/twenty-moles-change.md
- apps/backoffice/src/pages/index.tsx
Removed static banner refs on **_Home_** page.
Local `dev` mode.
> [IOPAE-2078] Removed static banner refs on home page

- .changeset/fifty-pens-shake.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/institutions/index.ts
- apps/backoffice/src/components/institutions/institution-search-by-name.tsx
- apps/backoffice/src/pages/delegated-institutions.tsx
This PR implements search by institution name into _delegated-institutions_ page.
_**Note:** watch video below to better appreciate ux/ui developments behaviour._
Follow commits history to better understand developments.
Need to search an institution by name for aggregator institutions that have a lot of delegated institutions.
**Search by institution name** _(search result is a mocked random response)_:
https://github.com/user-attachments/assets/364f13bb-6e15-4a88-b2a3-de872a7f5b1f
> [IOPAE-2052] Added search by institution name into delegated-institutions page

- .changeset/silver-swans-sing.md
- apps/backoffice/src/app/api/institutions/[institutionId]/delegations/__tests__/route.test.ts
- apps/backoffice/src/app/api/institutions/[institutionId]/delegations/route.ts
- apps/backoffice/src/app/api/institutions/[institutionId]/groups/__tests__/institution-group-util.test.ts
- apps/backoffice/src/app/api/institutions/[institutionId]/groups/institution-groups-util.ts
- apps/backoffice/src/app/api/subscriptions/__tests__/route.test.ts
- apps/backoffice/src/app/api/subscriptions/route.ts
- apps/backoffice/src/lib/be/__tests__/institutions.test.ts
- apps/backoffice/src/lib/be/__tests__/req-res-utils.test.ts
- apps/backoffice/src/lib/be/__tests__/selfcare-client.test.ts
- apps/backoffice/src/lib/be/institutions/__tests__/selfcare.test.ts
- apps/backoffice/src/lib/be/institutions/business.ts
- apps/backoffice/src/lib/be/institutions/selfcare.ts
- apps/backoffice/src/lib/be/req-res-utils.ts
- apps/backoffice/src/lib/be/selfcare-client.ts
- apps/backoffice/turbo.json
- [refactoring: create and use specific functions for parsing limit and …](https://github.com/pagopa/io-services-cms/commit/abb35719e5c3a43fc7c9698a28a62a53c0fed43c)
- [add getInstitutionDelegations](https://github.com/pagopa/io-services-cms/commit/17840dc7a1ca4d4400e5913940393f02ea28713e)
- [using selfcare getDelegations paginated version](https://github.com/pagopa/io-services-cms/commit/5ff39503135b796ef5369bf828ae8b3737e1b63f)
- [add getDelegatedInstitutions](https://github.com/pagopa/io-services-cms/commit/b7629c34484042c1b06ca4e1143e9a80b1c14919)
- [add getDelegatedInstitutions api operation handler](https://github.com/pagopa/io-services-cms/commit/eab4585c6e7f635d0f73490cae5d7ef705d65382)
- [add docs to parseQueryParam](https://github.com/pagopa/io-services-cms/commit/c7cb9c64b5a3c8c …
> [IOPAE-2047] implements get delegated institutions api

- apps/io-services-cms-webapp/openapi.yaml
restore openapi schema absolute references
- CMS openapi definition
To allow opex dashboard to be applied
> [IOPAE2026] restore openapi schema absolute references

- .changeset/clever-pugs-pump.md
- apps/backoffice/src/pages/delegated-institutions.tsx
- apps/backoffice/src/utils/mix-panel.ts
Added new mix-panel events for _delegated-institutions_ page.
Need to track user actions on new _delegated-institutions_ page.
> [IOPAE-2055] Added new mix-panel events for delegated-institutions page

- .opex/api_services_cms/env/prod/config.yaml
the dashboard is on west europe and not on italy north
> [IOPAE-2105]revert location change

- infra/resources/_modules/postgres/main.tf
- infra/resources/_modules/postgres/providers.tf
> Remove dx next cidr resource

- .devcontainer/devcontainer.json
- apps/io-services-cms-webapp/ActivationsSyncFromLegacy/function.json
- infra/resources/_modules/cms_function_app/locals.tf
- infra/resources/_modules/cms_function_app/rbac.tf
- infra/resources/prod/main.tf
- infra/resources/prod/tfmodules.lock.json
[add blob storage writer role to cms function app](https://github.com/pagopa/io-services-cms/commit/ff40df55e108d3bdee0a3ba4c7fc1b351bd38e4e)
The cms function app lacks the role of blob writer for the storage account
> chore: add blob storage writer role to cms function app

- .changeset/twelve-clouds-kick.md
> chore: add changeset for activaton sync from legacy deploy

- .changeset/lazy-foxes-type.md
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/api-keys/api-keys-card/api-keys-card.tsx
added show more label
we not have an total element
in local with test msw
> [#IOPAE- 1893] FE - Overview Api Key Manager Group , add label "..." when we have over 5 elements

- .changeset/fuzzy-roses-buy.md
- apps/backoffice/mocks/data/selfcare-data.ts
- apps/backoffice/mocks/handlers/selfcare-handlers.ts
- apps/backoffice/openapi.yaml
- apps/backoffice/src/app/api/institutions/[institutionId]/products/__tests__/route.test.ts
- apps/backoffice/src/app/api/institutions/[institutionId]/products/route.ts
- apps/backoffice/src/lib/be/__tests__/institutions.test.ts
- apps/backoffice/src/lib/be/__tests__/selfcare-client.test.ts
- apps/backoffice/src/lib/be/institutions/__tests__/selfcare.test.ts
- apps/backoffice/src/lib/be/institutions/business.ts
- apps/backoffice/src/lib/be/institutions/selfcare.ts
- apps/backoffice/src/lib/be/selfcare-client.ts
added new api to get user institution products
required new api from backoffice portal to show the list of institutional active products
in local and with unit test
> [IOPAE-2119] - Added new api get user institution products

- infra/resources/_modules/cms_function_app/main.tf
> chore: activate the ingestion activations function

- infra/resources/_modules/function_app/locals.tf
- infra/resources/prod/tfmodules.lock.json
Scale up tier of function app be from standard to premium
> [IOPAE 2135] Scale up tier of function app be from standard to premium

- .changeset/tender-trees-relate.md
- apps/backoffice/mocks/data/backend-data.ts
- apps/backoffice/public/locales/en/common.json
- apps/backoffice/public/locales/it/common.json
- apps/backoffice/src/components/markdown-view/markdown-view.tsx
- apps/backoffice/src/components/services/service-preview.tsx
- apps/backoffice/src/components/services/service-reject-reason-content.tsx
> Add markdown rendering to service rejection reason

- .devcontainer/.env.devcontainer
- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yaml
cosmosdb emulator integration to devcontainer
Local run
> [IOPAE-2130] devcontainer: cosmosdb emulator integration

- .changeset/tender-icons-mix.md
- apps/io-services-cms-webapp/src/reviewer/__tests__/review-checker-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/__tests__/review-legacy-checker-handler.test.ts
- apps/io-services-cms-webapp/src/reviewer/review-checker-handler.ts
- apps/io-services-cms-webapp/src/reviewer/review-legacy-checker-handler.ts
Save only the last comment of a Jira ticket if present
Resolves IOPAE-2160
> Save only the last comment of a Jira ticket
