pagopa/io-services-cms

apps/io-services-cms-webapp/src/utils/__tests__/service_review_proxy.test.ts
apps/io-services-cms-webapp/src/utils/service_review_proxy.ts
packages/io-services-cms-models/src/service-lifecycle/types.ts

This utility will be used in **Service Review Process** for:
- create a ticket on jira after a request for a service review
- search for one or more tickets on jira
- by issue key
- by serviceId **_(new)_**
- Added `getJiraIssueByServiceId` method for retrievieng a single Jira Issue given the related _serviceId_
- Added unit tests
Unit Tests and manual integration tests

[#IOPAE-303] Service Review Proxy - Add getJiraIssueByServiceId

---

infra/src/common.tf

fixes a typo and regenerate resources accordingly

Rename Azure resources

---

.changeset/fifty-chicken-learn.md
packages/io-services-cms-models/index.js
packages/io-services-cms-models/package.json
packages/io-services-cms-models/src/index.ts

* set a dummy `index.js` entrypoint
* export FSM types
We encountered an issue while executing tests with `vitest` on apps that uses the package `@io-services-cms`. `vitest` seems not to understand what the correct entrypoint is, giving the following error:
```
Failed to resolve entry for package "@io-services-cms". The package may have incorrect main/module/exports specified in its package.json.
```
This can be solved by defining a `main` field in package.json with `dist/index.js`. However, such value breaks the application build (which would otherwise expect just `index.js`). 
A similar issue has been reported https://github.com/vitest-dev/vitest/issues/2922
The found workaround is to have a _dummy_ `index.js` that just proxies `dist/index.js`. Being that the default value for the …

Fix `@io-services-cms` package

---

infra/src/storage_account.tf

A Storage Account requires either public access or a private endpoint. Otherwise its endpoint cannot be accessed and no operation on it can be performed

fix: storage account public access unless private endpoint

---

apps/io-services-cms-webapp/src/config.ts

Fix webapp configuration keys in which a default value is expected.
With this fix it is possible to use correctly the default value of the "_withDefault_" keys without necessarily having to enter the value in the environment.
- apps/io-services-cms-webapp/src/config.ts

[#IOPEA-369] Fix withDefault config keys

---

.changeset/gold-tigers-return.md
packages/io-services-cms-models/src/lib/fsm/types.ts
packages/io-services-cms-models/src/service-lifecycle/__tests__/index.test.ts
packages/io-services-cms-models/src/service-lifecycle/index.ts
packages/io-services-cms-models/src/service-publication/__tests__/index.test.ts
packages/io-services-cms-models/src/service-publication/index.ts

Add override action to both FSM (lifecycle and publication) to bypass FSM constraints and "force" update when sync from legacy in order to get both system in-sync
- add override action to FSM lifecycle
- add override action to FSM publication
It is required to get in-synch both legacy and new cms systems
Unit tests

feat: [IOPAE-320]  add force/override action on fsm

---

packages/io-services-cms-models/src/service-lifecycle/index.ts

Just a refactor on https://github.com/pagopa/io-services-cms/pull/140.
The aim is to flatten a code with too many indentations.

Refactor on #140

---

.changeset/nasty-plums-raise.md
apps/io-services-cms-webapp/src/lib/clients/apim-client.ts
apps/io-services-cms-webapp/src/webservice/controllers/__test__/get-service-keys.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/get-service-keys.ts

Change apim api call to retrieve subscription's keys `subscription.get` -> `subscription.listSecrets`
Unit Test and Local Application run

fix: change apim api to retrieve subscription keys

---

apps/io-services-cms-webapp/src/lib/clients/apim-client.ts

Fix regenerate service key API.
- Change apim api call to retrieve subscription's keys `subscription.get` -> `subscription.listSecrets` after regenerate them.
Unit test and Local Application run

fix: regenerate serviceKey

---

.changeset/tiny-tigers-wink.md
apps/io-services-cms-webapp/src/watchers/__tests__/on-service-lifecycle-change.test.ts
apps/io-services-cms-webapp/src/watchers/on-service-lifecycle-change.ts

Add a filter to service lifecycle watcher to avoid opening a review or publication request for services from legacy system.
- Add a filter (`item.fsm.lastTransition`) to service lifecycle watcher
To avoid "side effects" on synching CMS from Legacy
Unit Tests

chore: [IOPAE-385] add legacy filter to service lifecycle watcher

---

.changeset/dull-parrots-draw.md
apps/io-services-cms-webapp/src/utils/converters/service-lifecycle-converters.ts
apps/io-services-cms-webapp/src/utils/converters/service-publication-converters.ts
apps/io-services-cms-webapp/src/webservice/controllers/__test__/get-service-lifecycle.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/__test__/get-service-publication.test.ts
openapi.yaml

With the way we wrote the openApi using an **allOf** object and the required parameter outside of it , the generator does not generate the : `id` , `status` and `last_update` for the serviceLifecycle/Publication model to be mandatory , but sets them as optional
- Moved required parameter inside the allOf object in the openApi
- update converters
- update tests
First the Old one , Second the New one

fix:[BUG][#IOPAE-455]Generator doesn't generate correctly required parameter inside allOf in openApi

---

.changeset/nine-readers-wave.md
apps/io-services-cms-webapp/src/watchers/__tests__/on-legacy-service-change.test.ts
apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts

A freshly created service on Dev portal `lack of description`, this cause a sync problem, cause the description is required in CMS application, in order to fix this issue we set a placeholder value as `metadata.description` while mapping a legacy service who lack of it.
Unit test

fix: [BUG] Placeholder metadata description on legacy cms mapping

---

.changeset/soft-dogs-boil.md
apps/io-services-cms-webapp/src/watchers/__tests__/on-legacy-service-change.test.ts
apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts

unpublish service when deleting id coming from legacy sync
- add an unpublish item to requestSyncCms when a legacy service is deleted
Unit Test

fix: [IOPAE-479] unpublish service when deleting id coming from legacy sync

---

.changeset/odd-jeans-agree.md
apps/io-services-cms-webapp/src/lib/clients/__tests__/jira-legacy-client.test.ts
apps/io-services-cms-webapp/src/lib/clients/jira-legacy-client.ts

Add retry capabilities to Jira Legacy Client on Throttled response
- Handle `Retry-After` header on Jira response, this header contains the number of seconds which needs to be Re-Done the REST API call to the Jira API.
- Add related unit tests.
Manage throttled responses received from jira accordin to this [documentation page](https://developer.atlassian.com/cloud/jira/platform/rate-limiting/#rate-limit-responses).
Unit Tests

chore: Add retry capabilities to Jira Legacy Client on Throttled response

---

.changeset/nine-chairs-warn.md
apps/io-services-cms-webapp/src/lib/clients/jira-legacy-client.ts

The field `statuscategorychangedate` is not always valued, so we should set it as an optional value in our ` io-ts codec` for the jira legacy response.
Fetching data from the Jira Legacy board we received the following error:
```
LegacyServiceWatcher|Error while processing serviceId censored, the reason was => value [null] at [root.0.issues.0.fields.statuscategorychangedate] is not a valid [non empty string], the stack was => Error: value [null] at [root.0.issues.0.fields.statuscategorychangedate] is not a valid [non empty string]
at Object.toError (/home/site/wwwroot/node_modules/fp-ts/lib/Either.js:1229:37)
at /home/site/wwwroot/dist/lib/clients/jira-legacy-client.js:97:543
at /home/site/wwwroot/node_modules/fp-ts/lib/Either.js:643:56
at process.processTicksAndRejections …
```

chore(fix): Status category optional legacy jira

---

.changeset/lemon-rockets-knock.md
apps/io-services-cms-webapp/src/main.ts
apps/io-services-cms-webapp/src/watchers/__tests__/on-legacy-service-change.test.ts
apps/io-services-cms-webapp/src/watchers/on-legacy-service-change.ts
packages/io-services-cms-models/src/queue/index.ts
packages/io-services-cms-models/src/service-legacy/index.ts

Removed Jira call and update status mapping on LegacyServiceWatcher
- Removed `Jira REST API call` on `LegacyServiceWatcher`
- Add Fetch `previous service Version` to correctly intercept `unpublish actions` on legacy.
- Update `status mapping` on `LegacyServiceWatcher`
- Update `LegacyServiceWatcher Unit Test` according to the changes
When a service is submitted for a review or a review is rejected, on the legacy service management application, the service Itself will not change, so no Change Feed notification will be intercepted by this watcher, this means that we need to intercept the creation of new Jira Ticket and Jira ticket status changes on dedicated Functions to fully sync those kind of changes on legacy and sync in io-services-cms.
Unit Tests

[#IOPAE-510] Removed Jira call and update status mapping on LegacyServiceWatcher

---

.changeset/soft-ads-train.md
apps/backoffice/next-i18next.config.js
apps/backoffice/next.config.js
apps/backoffice/package.json
apps/backoffice/public/locales/en/common.json
apps/backoffice/public/locales/it/common.json
apps/backoffice/src/components/footer/index.tsx
apps/backoffice/src/components/headers/top-bar.tsx
apps/backoffice/src/components/sidenav/index.tsx
apps/backoffice/src/components/utils/page-html-head-title.tsx
apps/backoffice/src/pages/_app.tsx
apps/backoffice/src/pages/apikeys/index.tsx
apps/backoffice/src/pages/index.tsx
apps/backoffice/src/pages/services/[serviceId].tsx
apps/backoffice/src/pages/services/[serviceId]/edit-service.tsx
apps/backoffice/src/pages/services/index.tsx
apps/backoffice/src/pages/services/new-service.tsx
yarn.lock

Add multilingual _(Italian, English)_ feature to IO BackOffice.
_Follow the commit history for a step-by-step understanding of the implementation._
Below is the documentation followed in the development of the feature:
- [NextJS official docs](https://nextjs.org/docs/pages/building-your-application/routing/internationalization)
- [Codemotion tutorial](https://www.codemotion.com/magazine/frontend/multilingual-site-in-next-js-with-next-i18next/)
https://github.com/pagopa/io-services-cms/assets/118166285/c10d62c5-6ceb-4b1b-a79b-ee848eb6ae55

[IOPAE-507] BackOffice Internazionalization (i18n)

---

.changeset/fifty-actors-punch.md
apps/io-services-cms-webapp/ServiceReviewLegacyChecker/function.json
apps/io-services-cms-webapp/src/main.ts
apps/io-services-cms-webapp/src/reviewer/__tests__/review-checker-handler.test.ts
apps/io-services-cms-webapp/src/reviewer/__tests__/review-legacy-checker-handler.test.ts
apps/io-services-cms-webapp/src/reviewer/review-checker-handler.ts
apps/io-services-cms-webapp/src/reviewer/review-legacy-checker-handler.ts
apps/io-services-cms-webapp/src/utils/logger.ts
infra/src/webapp.tf

Add New `ServiceReviewLegacyChecker`, Azure Function that will sync any Jira Legacy status change to the imported legacy services.
- ADD ServiceReviewLegacyChecker AF `function.json`
- ADD AzureWebJobs.ServiceReviewLegacyChecker.Disabled in `webapp.tf`
- ADD `ServiceReviewLegacyChecker` Azure Function
- ADD Unit Test for `ReviewLegacyCheckerHandler`
When a Service is Submitted for an approval on Legacy Service a Jira Ticket is created, the workflow on those tickets needs to be tracked in order to correctly intercept all Legacy service status change and sync them in `io-services-cms`
Unit Test

[#IOPAE-493] Service review legacy checker

---

.changeset/fluffy-wombats-check.md
apps/backoffice/public/locales/en/common.json
apps/backoffice/public/locales/it/common.json
apps/backoffice/src/components/sidenav/index.tsx
apps/backoffice/src/pages/keys/index.tsx

The routing of the "_**API Keys"**_ section _(where Manage key will be present)_, was defined by the `apikeys` route _(io-services-cms/apps/backoffice/src/pages/apikeys/index.tsx)_
**Problem:**
The fact that route name starts with **"api"** generates a conflict in the _NextJs routing system_ which identifies that route as a _Route Handler API_ _(io-services-cms/apps/backoffice/src/app/api/ …)_
**Solution:**
We rename the route `apikeys` in `keys` _(io-services-cms/apps/backoffice/src/pages/keys/index.tsx)_

fix: [IOPAE-517] NextJS Routing conflict: rename page apikeys to keys

---

.changeset/twenty-pigs-train.md
apps/io-services-cms-webapp/src/reviewer/__tests__/request-review-legacy-handler.test.ts
apps/io-services-cms-webapp/src/reviewer/__tests__/review-legacy-checker-handler.test.ts
apps/io-services-cms-webapp/src/reviewer/request-review-legacy-handler.ts
apps/io-services-cms-webapp/src/reviewer/review-legacy-checker-handler.ts

In order to prevent unwanted status changes from `deleted` -> `other_status` we will skip services marked as `deleted` in `OnRequestReviewLegacy` and `RequestReviewLegacyChecker` Azure Functions
Unit Test

chore: skip currently deleted services on legacy review

---

.changeset/strong-frogs-beam.md
README.md
apps/io-services-cms-webapp/env.example
apps/io-services-cms-webapp/src/config.ts
apps/io-services-cms-webapp/src/main.ts
apps/io-services-cms-webapp/src/reviewer/__tests__/request-review-handler.test.ts
apps/io-services-cms-webapp/src/reviewer/request-review-handler.ts
apps/io-services-cms-webapp/src/utils/feature-flag-handler.ts

As disclosed in #326 we are introducing an `Automatic Service Approval mechanism`.
- Added `USERID_AUTOMATIC_SERVICE_APPROVAL_INCLUSION_LIST` config
- Added `isUserAllowedForAutomaticApproval` feature flag utility method
- Refactor `request-review-handler`
- Add the Automatic Service Approval capability in `request-review-handler`
- Add `unit test` for automatic service approval
- Introduced FeatureFlags in `README.md`
Some trusted PAs and relative Technological Partners, may massively create and submit for review new services, so in a short time interval we can receive thousands request for service approval, which will cause an excessive overload on L1 service reviews.
To Solve this we will implements an automatic approval mechanism for submitted services for such PAs and Technological …

[#IOPAE-536] Automatic Service Approval Capability

---

.changeset/dull-scissors-learn.md
apps/backoffice/openapi.yaml
packages/io-services-cms-models/openapi/backoffice-schemas.yaml

`openapi-codegen-ts` module is ignoring inline schemas, so in order to properly generate them we need to export them to an external Schema.
- moved `/auth` requestBody schema from inline to an external one `SelfCareIdentity`

chore: Export Selfcare Identity payload from inline to an external Schemas

---

.changeset/lucky-humans-fetch.md
apps/backoffice/src/components/snackbar-provider/index.tsx
apps/backoffice/src/providers/app.tsx

Added **SnackbarProvider** component to perform notification programmatically in form of _MUI Snackbar alerts_.
**Snackbar Options:**
```
type SnackbarOptions = (item: SnackbarItem) => void;
type SnackbarItem = {
/** The severity of the alert. This defines the color and icon used.  */
severity: AlertColor;
/** Alert title */
title?: string;
/** Alert body message content */
message?: string;
};
```
**How to use it:**
```
import { useSnackbar } from "@/components/snackbar-provider";
const showSnackbar = useSnackbar();
...
return (
...
<Button
size="medium"
variant="contained"
onClick={() =>
showSnackbar({
severity: "success",
title: "Operation completed",
message: "This is a successful notification with title and message..."
})
}
>
Test Success
</Button>
```
_See this example below in …

[IOPAE-585] Add Snackbar Provider component

---

apps/backoffice/openapi.yaml

Add Manage Keys APIs definitions in `backoffice/openapi.yaml`
- ADD `GET /keys/manage` definition in `backoffice/openapi.yaml`, this api will allow an user to retrieve it's own Manage Keys
- ADD `PUT /keys/manage/{keyType}` definition in `backoffice/openapi.yaml`, this api will allow an user to regenerate either it's own primary or secondary Manage Key

[#IOPAE-608] Add Manage Key APIs definitions

---

.changeset/big-pumas-sip.md
apps/backoffice/mocks/data/backend-data.ts
apps/backoffice/mocks/handlers/backend-handlers.ts
apps/backoffice/src/app/api/keys/manage/cidrs/route.ts

Add Manage Keys Authorized CIDRs APIs route handler placeholders.
- ADD `GET /keys/manage/cidrs` route handler placeholders, this api will retrieve the Authorized CIDRs associated to the Manage Keys currently in use(which is located in auth JWT).
- ADD `PUT /keys/manage/cidrs` route handler placeholders, this api will update the Authorized CIDRs associated to the Manage Keys currently in use(which is located in auth JWT).

[#IOPAE-621] ADD Authorized CIDRs B4F API api route placeholders, and mws mocks

---

.changeset/famous-ducks-cry.md
apps/io-services-cms-webapp/src/lib/clients/jira-client.ts
apps/io-services-cms-webapp/src/lib/clients/jira-legacy-client.ts
apps/io-services-cms-webapp/src/reviewer/review-checker-handler.ts
apps/io-services-cms-webapp/src/reviewer/review-legacy-checker-handler.ts
apps/io-services-cms-webapp/src/utils/__tests__/jira-proxy.test.ts
apps/io-services-cms-webapp/src/utils/jira-proxy.ts

Handle changed jira issue status names
Jira api seems to be inconsistent, the field `issue.fields.status.name` sometimes is returned in UPPERCASE, sometime in PascalCase, so we are removing the field validator(which was an union of io-ts literals, which are case sensitive), and normalize it when is needed.
- Remove Type JiraIssueStatus`type literal.
- Add `decodeJiraIssueStatus` in `review-checker-handler.ts` to normalize the value before saving it on DB.
Unit test

fix:[#IOPAE-638] Handle Jira Issue status name case change

---

.changeset/quiet-comics-draw.md
apps/backoffice/openapi.yaml
apps/backoffice/src/app/api/health/__tests__/route.test.ts
apps/backoffice/src/app/api/health/route.ts

Add a lightweight HealthCheck api, this API will be used by Azure to determine if the application is Healthy or not
- ADD `GET /health` API in Backoffice B4F `openapi.yaml`
- Implement  `GET /health`Route Handler
- ADD Unit tests for `GET /health`Route Handler
Unit Test

[#IOPAE-737] ADD GET health api in B4F

---

.changeset/cool-wombats-reply.md
apps/backoffice/openapi.yaml
apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
apps/backoffice/src/app/api/services/[serviceId]/route.ts
apps/backoffice/src/app/api/services/route.ts
apps/backoffice/src/components/headers/header.tsx
apps/backoffice/src/components/services/__tests__/adapters.test.ts
apps/backoffice/src/components/services/adapters.ts
apps/backoffice/src/lib/be/__tests__/cms-proxy.test.ts
apps/backoffice/src/lib/be/cms/business.ts
apps/backoffice/src/pages/services/[serviceId]/edit-service.tsx
apps/backoffice/src/pages/services/new-service.tsx
apps/backoffice/types/next-auth.d.ts

Make the setting of organization fields transparent to the user when creating and updating the service.
- Add `organization.name` and `organization.fiscal_code` as user session fields
- Remove `organization` property from create and update service request body (B4F API)
- Add `organization` fields (picked from user session) from create and update service request body before forward request to services-cms
Improve user experience and system robustness

chore: [IOPAE-715] add institution fields to createService and updateService

---

.changeset/beige-singers-push.md
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/publish-service.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/publish-service.ts

This PR fix the bug mentioned in IOPAE-741 ticket regarding the response returned when the publish API was called for a non approved Service.
Before Calling the FSM Publication publish method we now check for service existence and return a 404 response in negative cases.
**Before the fix the response was**:
```json
HTTP 500 INTERNAL SERVER ERROR
{
"detail": "Error executing endpoint handler: Cannot read properties of undefined (reading 'data')",
"status": 500,
"title": "Internal server error"
}
```
**After the fix the response is**:
```json
HTTP 404 NOT FOUND
{ 
"detail": "no item with id s1 found", 
"status": 404, 
"title": "Not found" 
}
```
PS: Another way to solve the issue can be done by renaming the action `publish` on `FSM Publication` for transition from `'*'` -> `published` to …

fix: [IOPAE-741] publish non approved service

---

.changeset/pink-cherries-repeat.md
apps/backoffice/public/locales/en/common.json
apps/backoffice/public/locales/it/common.json
apps/backoffice/src/components/create-update-process/create-update-process.tsx
apps/backoffice/src/components/services/service-create-update/service-builder-step-1.tsx

Add equality check on update service form: avoid to send update and notify user if initial form values are equal to submitted values.
**Watch the video to appreciate the development.**
- added notification translations
- added equality check on **CreateUpdateProcess** component
- minor: hide some create/update service form fields that should be developed in next MVPs
Avoid saving multiple identical versions of the same service.
https://github.com/pagopa/io-services-cms/assets/118166285/6108df78-0efc-4956-bafe-aeba3259e7e4

[IOPAE-756] Add equality check on update service form

---

.changeset/silent-dryers-push.md
apps/backoffice/src/app/api/health/route.ts
apps/backoffice/src/app/api/info/route.ts
apps/backoffice/src/lib/be/__tests__/selfcare-client.test.ts
apps/backoffice/src/lib/be/apim-service.ts
apps/backoffice/src/lib/be/cms-client.ts
apps/backoffice/src/lib/be/cosmos-store.ts
apps/backoffice/src/lib/be/legacy-cosmos.ts
apps/backoffice/src/lib/be/selfcare-client.ts
apps/backoffice/src/lib/be/subscription-migration-client.ts

**Refactor clients singleton**
- ADD client healthchecks in /info and /health Route Handler
- REMOVE react cache and transform into a classic singleton `@/lib/be/selfcare-client`
- REMOVE react cache and transform into a classic singleton `@/lib/be/apim-service`
- REMOVE react cache and transform into a classic singleton `@/lib/be/cms-client`
- REMOVE react cache and transform into a classic singleton `@/lib/be/cosmos-store`
- REMOVE react cache and transform into a classic singleton `@/lib/be/legacy-cosmos`
- REMOVE react cache and transform into a classic singleton `@/lib/be/subscription-migration-client`
Unit Tests

chore: Transform external clients into regular singleton instead of caching instance using react cache

---

.changeset/nervous-countries-reflect.md
apps/backoffice/public/locales/en/common.json
apps/backoffice/public/locales/it/common.json
apps/backoffice/src/components/cards/card-rows.tsx
apps/backoffice/src/components/markdown-view/index.ts
apps/backoffice/src/components/markdown-view/markdown-view.tsx
apps/backoffice/src/components/services/service-info.tsx
apps/backoffice/src/components/services/service-preview.tsx

Update of the drawer that displays service details data.
In particular:
- added _"Sensitive Service"_ label after the description, in case of flag `require_secure_channel = true`
- added rendering of description markdown syntax
- Added the ability to show the label/value pair on two lines
- new translations
- new reusable **MarkdownView** component
- add `renderValueOnNewLine` prop on **CardRows** component
- update service-info for service details data
Need to correctly show all the data of a service.
https://github.com/pagopa/io-services-cms/assets/118166285/ef909fe8-15d6-46d3-adef-2654ce7cfd44

[IOPAE-784] Update service details drawer

---

.changeset/tender-items-ring.md
.sonarcloud.properties
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/publish-service.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/unpublish-service.test.ts
packages/io-services-cms-models/src/lib/fsm/types.ts
packages/io-services-cms-models/src/service-lifecycle/__tests__/index.test.ts
packages/io-services-cms-models/src/service-lifecycle/index.ts
packages/io-services-cms-models/src/service-publication/__tests__/index.test.ts
packages/io-services-cms-models/src/service-publication/index.ts

Make publish and unpublish actions (Publication FSM) idempotent
- add action publish: published -> published
- add action unpublish: unpublished -> unpublished
To avoid errors (and, thus, log entropy) when the requested action makes no change to the current state of the item
Unit tests

feat: [IOPAE-816] make publish and unpublish actions idempotent

---

.changeset/healthy-apricots-remember.md
apps/backoffice/mocks/data/selfcare-data.ts
apps/backoffice/mocks/handlers/backend-handlers.ts
apps/backoffice/openapi.yaml
apps/backoffice/src/components/headers/header.tsx

The way `UserAuthorizedInstitutions` list is retrieved has been changed.
Before this change the list was present in the session token, which caused size problems for delegates of many entities.
For this reason, the session token has been _(in another PR)_ streamlined from this list and it will be a frontend task to retrieve the list of `UserAuthorizedInstitutions` from the specific B4F api, i.e. `getUserAuthorizedInstitutions`.
_Follow commits history to better understand developments._
- fix a typo in b4f openapi
- update mocks
- change header components way of fetch UserAuthorizedInstitutions
Local `dev` mode with `msw` mock

bugfix: [IOPAE-826] FE - Get user authorized institutions from api instead of session token

---

.changeset/young-pets-laugh.md
apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts
apps/backoffice/src/app/api/auth/types.ts

Truncate organization name to 100 characters before set apim user lastName fields during apim user creation
Unit tests

bugfix: [IOPAE-829] patch apim user lastname max length

---

.changeset/tricky-cherries-sniff.md
apps/io-services-cms-webapp/src/synchronizer/__tests__/request-sync-legacy-handler.test.ts
apps/io-services-cms-webapp/src/synchronizer/request-sync-legacy-handler.ts

- call `findLastVersionByModelId` instead of deprecated `findOneByServiceId` method

fix: [#IOPAE-912] replace findOneByServiceId method call with findLastVersionByModelId

---

.changeset/orange-dancers-refuse.md
apps/backoffice/src/app/api/auth/[...nextauth]/__tests__/auth.test.ts
apps/backoffice/src/app/api/auth/[...nextauth]/auth.ts

Flip `firstName` and `note` values (respectively set with `organizationName` and `organizationFiscalCode`)
- [flip apim user firstName and note values](https://github.com/pagopa/io-services-cms/commit/b3a165a8627b0f06d55a0b40760473658c8c96c5)
Organization name may have special characters that Apim User field `firstName` do not support.

fix: [IOPAE-891] patch organization name spacial characters

---

.changeset/silver-avocados-arrive.md
apps/backoffice/src/components/__tests__/service-status.test.tsx
apps/backoffice/src/components/services/service-status.tsx
apps/backoffice/src/pages/services/index.tsx

Change layout of _**deleted services**_ displayed in table-view of **Services** Page.
The update consists in having made the layout of all the cells that make up the row of a deleted service in a disabled style.
_Watch screenshot below to better appreciate development result._
- `services` page
- `service-status` component _(and related unit tests)_
Unit tests

[IOPAE-914] Update deleted service table row layout in Services Page

---

.changeset/modern-spies-help.md
apps/backoffice/src/components/sidenav/index.tsx

Change **sidenav** bottom menu icon for opening/collapsing sidenav
_Watch screenshot to better appreciate result._

[IOPAE-870] Change sidenav bottom menu icon for opening/collapsing sidenav

---

.changeset/orange-poems-push.md
apps/backoffice/src/components/footer/index.tsx

If the browser has configured an _english_ language preference, different from the default one _(i.e. Italian)_, the application is shown correctly in english but the language selector _(in the footer)_ remained set to Italian.
With this fix, the selector is also consistent with the language currently used in the application.
**Note:**
_At the moment the supported languages are **Italian** `it`, **English** `en`._

[IOPAE-850] Fix language selector

---

.changeset/calm-penguins-tease.md
apps/backoffice/public/locales/en/common.json
apps/backoffice/public/locales/it/common.json
apps/backoffice/src/components/buttons/button-exit.tsx
apps/backoffice/src/components/buttons/index.ts
apps/backoffice/src/components/headers/page-header.tsx
apps/backoffice/src/pages/services/[serviceId]/edit-service.tsx
apps/backoffice/src/pages/services/new-service.tsx

Replace breadcrumbs with exit shortcut on service create/update pages.
_Follow commits history to better understand developments.
Watch screenshots below to appreciate changes._
- Add translations
- Add new exit button
- Update PageHeader component with new implementations:
- Update Create/Update Service Pages replacing breadcrumbs with exit button
Quality Assurance activity
**On Exit click:**

[IOPAE-887]  Page Header: replace breadcrumbs with exit shortcut on service create/update pages

---

.changeset/three-eggs-behave.md
apps/backoffice/src/components/services/subscriptions-migration/migration-latest.tsx

Fix responsive layout on migration overview.
_Watch screenshot and video below to better appreciate changes._
Replace **MUI Grid** with a **MUI Table**.
Need to fix a minor break on layout responsivity on some small screen sizes.
**Responsivity sample issue:**
**Video with new layout behaviour:**
https://github.com/pagopa/io-services-cms/assets/118166285/2ec69215-7885-4abc-93a0-2e20e2918eb3

[IOPAE-873] Fix responsive layout on migration overview

---

.changeset/ten-moose-worry.md
apps/io-services-cms-webapp/src/synchronizer/__tests__/request-sync-legacy-handler.test.ts
apps/io-services-cms-webapp/src/synchronizer/request-sync-legacy-handler.ts

add "default" cidrs when services get synched and cidrs list is empty
add "default" cidrs when services get synched and cidrs list is empty
there is a check on the devportal when a service is approved/published that if the cidrs are not set it marks the service as "coming soon" in the app and with "incomplete data" on the devportal, this is because theoretically the cidrs are mandatory for the publication of a service, but in the CMS this is not the case. The CIDRS are optional so some entities do not set them and even though the service is approved they then find themselves in the app with a service "coming soon" because this does not pass the quality check due to the fact that the service has no cidrs set

[#IOPAE-903]add default cidrs in sync if the service has an empty one

---

.changeset/unlucky-maps-crash.md
apps/backoffice/public/locales/en/common.json
apps/backoffice/public/locales/it/common.json
apps/backoffice/src/components/services/service-version-switcher.tsx

Fix frontend _xss vulnerability_ on `ServiceVersionSwitcher` component.
**Note:**
_This is a first frontend step for broader remediation of the XSS vulnerability._
- replace `dangerouslySetInnerHTML` with _next-i18next_ `Trans` function on **ServiceVersionSwitcher** component
**Problem description from VA/PT Security Assessment**
While selecting versions of a service, a pop-up appears showing the name of the service inserted insecurely into the html code. Any text inserted into the service name and rendered in this section, causes the exploit of an xss capable of executing javascript code.

fix:[IOPAE-952] Fix frontend xss vulnerability on ServiceVersionSwitcher component

---

.changeset/shiny-candles-rule.md
apps/backoffice/public/locales/en/common.json
apps/backoffice/public/locales/it/common.json
apps/backoffice/src/app/api/auth/[...nextauth]/route.ts
apps/backoffice/src/components/loaders/loader-fullscreen.tsx
apps/backoffice/src/pages/auth/error.tsx

Customized next-auth error page, to display authentication/authorization error in page.
- add required **translations**
- update **LoaderFullscreen** component by adding a `loading` state prop
- update _next-auth pages options_ (add custom error page route)
- add custom _**/auth/error**_ page
Need to better display what kind of error is returned by next-auth.
**Before changes _(no error detail on screen)_:**

[IOPAE-801] Add custom error page for next-auth errors

---

.changeset/late-shoes-remember.md
apps/backoffice/src/components/__tests__/page-breadcrumbs.test.tsx
apps/backoffice/src/components/headers/page-breadcrumbs.tsx

Fix inconsistent data in **PageBreadcrumbs** calling the app url with certain characters as query parameters.
**Issue:**
There was an error on query params cleanup on PageBreadcrumbs component.
_Watch screenshots below to better appreciate developments or check added unit tests to better understand issue._
- fix _**PageBreadcrumbs**_ business logic in query params cleanup
- add basic component _**unit tests**_
Mitigation for VA/PT Security assessment.
- Local `dev` mode with `msw` mock
- Unit tests
Sample of inconsistent page breadcrumbs with unexpected query parameters.
**After changes (issue fixed):**

fix:[IOPAE-960] Fix possible inconsistent data in PageBreadcrumbs

---

.changeset/green-knives-draw.md
apps/io-services-cms-webapp/src/reviewer/review-checker-handler.ts
apps/io-services-cms-webapp/src/utils/service-review-dao.ts
infra/src/webapp.tf

Fix pg cursor by disabling Application Insight patching, according to https://github.com/microsoft/node-diagnostic-channel/issues/67
- Improve `ServiceReviewChecker` logs
- Handling cursor creation with an E.tryCatch
- Add `APPLICATION_INSIGHTS_NO_PATCH_MODULES` property in order to disabling Application insight patching module per pg.
Local Application run

fix:[#IOPAE-965] Fix service review checker

---

.changeset/curly-paws-live.md
apps/io-services-cms-webapp/src/publicator/__tests__/request-publication-handler.test.ts
apps/io-services-cms-webapp/src/publicator/request-publication-handler.ts
packages/io-services-cms-models/src/service-publication/__tests__/index.test.ts
packages/io-services-cms-models/src/service-publication/index.ts

Create a new release fn intead of the one that uses publication fsm.
If this changes will pass "production tests", then we will clean codebase from useless publication FSM functions
- add new release fn to bypass publication fsm
To fix a bug when releasing a new approved version on an "already" unpublished service. Furthermore, there is no need to use a FSM on a Publication lifecycle, because there are only two possible states (`published`, `unpublished`) and there aren't any constraints on the actions/transitions witch can change states (currently is allowed to perform any combinations of actions)
Unit tests

fix: [IOPAE-983] patch publication-lifecycle release fn

---

.changeset/shaggy-frogs-shave.md
apps/io-services-cms-webapp/src/config.ts
apps/io-services-cms-webapp/src/main.ts
apps/io-services-cms-webapp/src/synchronizer/__tests__/request-sync-cms-handler.test.ts
apps/io-services-cms-webapp/src/synchronizer/request-sync-cms-handler.ts

Handle `topic_id` in Legacy -> CMS sync process.
- Preserve current topic_id both for ServiceLifecycle and ServicePublication sync items when present.
- Fallback to the ServiceLifecycle `topic_id` on ServicePublication sync and no item is found on the ServicePublication collection (this happen when the first publication is done on  legacy Developer Portal)
- Use the Default `topic_id` when this service is not found on Both ServiceLifecycle and ServicePublication collections.
Unit Tests

[#IOPAE-968] preserve topic_id on sync legacy

---

.changeset/fuzzy-cycles-beam.md
apps/backoffice/src/components/forms/schemas.ts
apps/backoffice/src/components/services/service-create-update/service-builder-step-2.tsx
apps/backoffice/src/components/services/service-create-update/service-builder-step-3.tsx

Fix service create/update URL fields in which it was possible to insert blanks at the beginning or end of the url values.
With this fix, blanks are now correctly detected and, in this case, the field changes its status to error _(red color with error helpertext)._
_Watch video below to better appreciate fix._
- add new `getUrlSchema`, `getOptionalUrlSchema` on **schemas**
- update service create/update **url fields** schema
Avoid start/end spaces on url fields in service create/update form.
https://github.com/pagopa/io-services-cms/assets/118166285/93b7d8f4-f998-4725-83ff-a3a15905c967

fix:[IOPAE-988] Avoid start/end spaces on url fields in service create/update form

---

.changeset/shiny-birds-visit.md
apps/io-services-cms-webapp/src/reviewer/__tests__/service-validation-handler.test.ts
apps/io-services-cms-webapp/src/reviewer/service-validation-handler.ts

Remove option from ValidSecureChannelService tos_url type
even if in a service the `require_secure_channel` fiel was true adding a value to the `tos_url` field would cause the service to be automatic rejected
unit tests

bugfix:[#IOPAE-997]Remove option from ValidSecureChannelService tos_url type

---

.changeset/five-bugs-dress.md
packages/io-services-cms-models/src/service-lifecycle/__tests__/index.test.ts
packages/io-services-cms-models/src/service-lifecycle/index.ts
packages/io-services-cms-models/src/service-publication/__tests__/index.test.ts
packages/io-services-cms-models/src/service-publication/index.ts

Trim Service Name before save FSM store.
This will help in Pure duplicates identification implemented here https://github.com/pagopa/io-services-cms/pull/767
- trim service name before saving in FSM store
Unit tests

chore:[IOPAE-1043] Trim Service Name before save

---

.changeset/six-shirts-destroy.md
apps/io-services-cms-webapp/openapi.yaml
apps/io-services-cms-webapp/src/utils/converters/service-history-converters.ts

Unified the `status` field of the ServiceHistory API response between "service-publication" and "service-lifecycle" 
derived elements.
Prior to this modification the response Payload was:
```lang=json
// status object (history object related to lifecycle)
{
...params,
"status" : {
"value" : <String>,
"reason": <String>
},
...other params
}
// status string (history object related to publication)
{
...params,
"status" : <String>,
...other params
}
```
After modification
```lang=json
// status object in both history object related to lifecycle and publication
{
...params,
"status" : {
"kind": "lifecycle" | "publication" // this allow to discriminate between lifecycle and publication items
"value" : <String>,
"reason": <String>
},
...other params
}
```
Unit tests(previously developed) and …

Service history status unify Implementation

---

packages/io-services-cms-models/openapi/services-cms-schemas.yaml

Set `topic_id` field required on ServicePayloadMetadata Schema

[IOPAE-1001] topic_id is now required in service payload Metadada schema

---

.changeset/cool-actors-sing.md
apps/backoffice/src/components/forms/controllers/autocomplete-controller.tsx
apps/backoffice/src/components/services/service-create-update/service-builder-step-1.tsx

Make topic required on service create/update form.
_Watch video below to better appreciate development._
- add required property for topic schema validation
- update AutocompleteController component in order to manage validation error
https://github.com/pagopa/io-services-cms/assets/118166285/35fb9e10-1bec-4739-a93f-a511081cf46b

[IOPAE-1065] BackOffice IO: Topic is now required on service create/update form

---

.changeset/twelve-scissors-wink.md
apps/app-backend/api/internal.yaml
apps/app-backend/api/internal.yaml.template
apps/app-backend/src/functions/__mocks__/featured-items.ts

Add `organization_name` optional property to **FeaturedService**.
- update openapi definitions
- update FeaturedItems mocks
Need to have the possibility to specify Organization Name for a featured service.

[IOPAE-1123] Add organization_name to featured service

---

infra/_modules/ai_search/outputs.tf

To allow tls handshake to work properly
search_service_url output returning raw cname to allow tls handshake to work properly
The privatelink url was returned, but this caused the tls handshake to fail due to certificate validation issues.

search_service_url output returning raw cname

---

.github/workflows/infra-cd.yml
.github/workflows/infra-ci.yml

Changed path triggers for infrastructure ci/cd workflows to run only when terraform configuration is changed inside apps/infra/src.
As of now, ci/cd workflows that plan and apply terraform code for weu infrastructure, are launched also for changes in the new itn infrastructure configuration.

Infra ci/cd for weu infrastructure now runs only for infra/src path

---

infra/_modules/ai_search/data.tf
infra/_modules/ai_search/main.tf
infra/prod/italynorth/.terraform.lock.hcl
infra/prod/italynorth/providers.tf

Assigned "Search Index Data Reader" role to the group of the project's developers
Instead of using AI Search API Keys, developers will be able to locally test the application and authenticate to AI Search via their identity
Terraform plan and pre-commit run -a

Allowed io-p-adgroup-services-cms group to query AI Search

---

.github/workflows/infra-release-p-itn.yml
.github/workflows/infra-review-p-itn.yml

The CI and CD workflows will also be triggered on changes done in the infra/_modules folder
If edits are done in the _modules folder (actual folder containing terraform resources configuration), the CI/CD workflows wouldn't start

ITN infra cicd should start also when editing _modules files

---

infra/_modules/ai_search/organizations.tf
infra/_modules/ai_search/services.tf
infra/_modules/ai_search/variables.tf

Added datachange policy to the organizations datasource to allow incremental indexing
Set scheduling of the three indexers with a 1 hour interval
The services and organizations indexes must be updated automatically to follow the addition and/or deletion of records in cosmosdb

[EC-288] Set scheduling of indexers with 1 hour interval

---

infra/_modules/ai_search/main.tf
infra/_modules/ai_search/variables.tf

Created sku variable in AI Search module
Changed AI Search sku to standard
⚠️ Apply will be executed locally to overcome issues caused by the restapi provider that make the plan fail.
The current sku (basic) does not allow to scale above 3 replicas. This capacity may not be enough for production loads, hence the standard sku has been chosen.

[EC-311] change AI search sku to standard

---

infra/src/README.md
infra/src/monitor.tf

An `evaluation_frequency` equalsTo a `window_duration` can lead, in some edge cases, to a loss of events
- upgrade the version of query alerts terraform resource
- increment `window_duration`
- add `mute_actions_after_alert_duration` to avoid receiving alerts for the same event
There might be a delay on audit log, so we have to increment alert time_window to manage those edge cases

use azurerm_monitor_scheduled_query_rules_alert_v2

---

.changeset/neat-waves-hide.md
apps/backoffice/src/pages/services/[serviceId].tsx

Currently the first call to the ServiceHistory API includes an unintended continuationToken(react passes a SyntheticBaseEvent which is mistakenly then used in the call as a continuationToken), as shown in the following screen.
- remove any Parameter on serviceHistory first call

[IOPAE-1201] Remove unwanted continuationToken on serviceHistory first call

---

.changeset/large-hotels-speak.md
apps/app-backend/api/internal.yaml
apps/app-backend/src/functions/__tests__/search-institutions.test.ts
apps/app-backend/src/functions/search-institutions.ts
apps/app-backend/src/utils/azure-search/client.ts

Order search Institutition based on `name` when no fullText search is involved(no search queryString param is provided when calling the API `GET /institutions`)
- Add `orderBy` parameter on Azure Search Client
- Add default `orderBy` use on no `search` queryParam is provided when calling the API `GET /institutions`
Unit Tests

[IOPAE-1224] Search institution default order on no searchtext provided

---

.changeset/wet-horses-suffer.md
.github/workflows/code-review.yaml
apps/app-backend/src/config.ts
apps/app-backend/src/functions/__tests__/search-institutions.test.ts
apps/app-backend/src/functions/search-institutions.ts

We have introduced a custom offset limit to avoid performance issue when paging a large response
- use custom offset limit only when requested a full text search
By using custom offset limit when requested either national institutions list or institution's services list, may return partial data

[IOPAE-1262] use custom offset limit only when requested a full text search

---

.changeset/calm-waves-behave.md
apps/backoffice/package.json
apps/backoffice/src/components/__tests__/setup.ts
yarn.lock

Added Jest dom node package and appropriate configuration to manage jest methods with vitest testing library
Remove the lint error for the jest method and enable the snippets
Local env

[IOPAE-1286] Fixed lint error for jest method

---

.changeset/four-poems-destroy.md
apps/backoffice/src/lib/be/__tests__/selfcare-client.test.ts
apps/backoffice/src/lib/be/institutions/selfcare.ts
apps/backoffice/src/lib/be/selfcare-client.ts

When user is logged in to IO Backoffice, only his active institutions need to be retrieved using the Selfcare API.
- [filter only ACTIVE user's institutions retrieved from selfcare API](https://github.com/pagopa/io-services-cms/commit/1e03449372b7a14c367ad4187147da8ec957e00c)
To retrieve only active user's institutions
unit tests

[IOPAE-1334]  fix get user authorized institutions

---

.changeset/rotten-clocks-rush.md
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/create-service.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/get-services.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/create-service.ts
apps/io-services-cms-webapp/src/webservice/controllers/get-services.ts

Both Backoffice and APIM set the APIM USerId as `x-user-id` header, so all request handlers already have this info
To avoid an APIM call to retrieve the ApimUserId....this info is already available from `x-user-id` header
unit tests

refactor: remove useless getUserByEmail calls

---

.changeset/brown-dolls-march.md
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/create-service.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/get-services.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/create-service.ts
apps/io-services-cms-webapp/src/webservice/controllers/get-services.ts

Optimization change for GetServices and CreateServices first one by removing a call to APIM second one using a method that uses an `Id` to search instead of an `email`
GetServices -> avoid an APIM call to retrieve the ApimUserId....this info is already available from x-user-id header
CreateServices -> using GetUsers instead of GetUserByEmail should speed up the api
local test

refactor:remove getUserByEmail calls

---

.changeset/dull-crews-listen.md
apps/app-backend/api/internal.yaml
apps/io-services-cms-webapp/host.json
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/get-service-keys.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/get-service-keys.ts
apps/io-services-cms-webapp/src/webservice/index.ts

`GET /service/{serviceId}/keys` will now return 404 on logically deleted services
Unit Test and Local Application Run

fix: [#IOPAE-1358] Get service key API behaviour on deleted service invocation.

---

.changeset/silent-donkeys-share.md
apps/backoffice/openapi.yaml
apps/backoffice/src/app/api/institutions/[institutionId]/groups/__tests__/route.test.ts
apps/backoffice/src/app/api/institutions/[institutionId]/groups/route.ts
apps/backoffice/src/app/api/subscriptions/__tests__/route.test.ts
apps/backoffice/src/app/api/subscriptions/route.ts
apps/backoffice/src/lib/be/__tests__/req-res-utils.test.ts
apps/backoffice/src/lib/be/req-res-utils.ts
apps/backoffice/src/lib/be/subscriptions/__tests__/business.test.ts
apps/backoffice/src/lib/be/subscriptions/business.ts
apps/backoffice/src/lib/be/types.ts
packages/external-clients/src/apim-client/__tests__/index.test.ts
packages/external-clients/src/apim-client/index.ts

Retrieving all manage subscriptions ("root" manage and "groups" manage) is required in order to allow API Keys management
User will be able to create a new type of subscription (aka "manage group") related to selfcare group, so retrieving all types of manage subscriptions ("root" manage and "groups" manage) is required in order to allow proper API Keys management
- [add PositiveInteger and PositiveIntegerFromString io-ts types](https://github.com/pagopa/io-services-cms/commit/90e647d8830d4a27ac1abe2b947360847cd54901)
- [add a common/generic getQueryParam fn](https://github.com/pagopa/io-services-cms/commit/13f48d141312e5d217af0269436e4f892396519c)
- [move out 'filter' param from getUserSubscriptions fn](https://github.com/pagopa/io-services-cms/commit/8bf8c991175081c5e09a263702765be85b6103 …

[IOPAE-1338] retrieve subscriptions manage group

---

.changeset/honest-pets-begin.md
apps/backoffice/openapi.yaml
apps/backoffice/package.json
apps/backoffice/src/app/api/services/[serviceId]/__tests__/route.test.ts
apps/backoffice/src/app/api/services/[serviceId]/route.ts
apps/backoffice/src/app/api/services/__tests__/route.test.ts
apps/backoffice/src/app/api/services/route.ts
apps/backoffice/turbo.json
apps/io-services-cms-webapp/PatchService/function.json
apps/io-services-cms-webapp/openapi.yaml
apps/io-services-cms-webapp/package.json
apps/io-services-cms-webapp/src/lib/middlewares/__tests__/channel-middleware.test.ts
apps/io-services-cms-webapp/src/lib/middlewares/channel-middleware.ts
apps/io-services-cms-webapp/src/utils/__tests__/check-source-ip.test.ts
apps/io-services-cms-webapp/src/utils/check-source-ip.ts
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/edit-service.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/patch-service.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/create-service.ts
apps/io-services-cms-webapp/src/webservice/controllers/patch-service.ts
apps/io-services-cms-webapp/src/webservice/index.ts
apps/io-services-cms-webapp/turbo.json
packages/io-services-cms-models/openapi/services-cms-schemas.yaml
packages/io-services-cms-models/src/lib/fsm/store.cosmos.ts
packages/io-services-cms-models/src/lib/fsm/store.memory.ts
packages/io-services-cms-models/src/lib/fsm/types.ts
packages/io-services-cms-models/src/service-history/index.ts
packages/io-services-cms-models/src/service-lifecycle/__tests__/index.test.ts
packages/io-services-cms-models/src/service-lifecycle/definitions.ts
packages/io-services-cms-models/src/service-lifecycle/index.ts
turbo.json

Allow operator to edit service without overriding group
- create a new `patchService` endpoint to allow group overriding (only for admin users)
- FSM edit actions now do not override `group_id`
- remove any group's logics from BO edit-service
To prevent the group change request from causing a status change in the FSM
- Unit Tests
- Run app locally

[IOPAE-1477] operator with group edit service

---

.changeset/big-tools-know.md
.changeset/five-zoos-give.md
apps/backoffice/src/app/api/institutions/[institutionId]/groups/any/route.ts
apps/backoffice/src/app/api/subscriptions/[subscriptionId]/keys/__tests__/route.test.ts
apps/backoffice/src/app/api/subscriptions/[subscriptionId]/keys/route.ts
apps/backoffice/src/lib/be/errors.ts
packages/external-clients/src/apim-client/index.ts

We have to implement missing `getManageSubscriptionKeys` route handler
- fix listSecrets return type
- add getManageSubscriptionKeys route handler
`getManageSubscriptionKeys` OpenAPI operation had been defined, but its implementation has been lacking.
- Unit Tests
- Run app locally

[IOPAE-1568] bff add manage group keys retrieve endpoint handler

---

.changeset/healthy-goats-decide.md
apps/backoffice/src/app/api/institutions/[institutionId]/groups/__tests__/route.test.ts
apps/backoffice/src/app/api/institutions/[institutionId]/groups/route.ts

Change `getInstitutionGroups` API implementation in order to handle a new query param that will eventually filter the instutution groups
- [getInstitutionGroups api implementation](https://github.com/pagopa/io-services-cms/commit/8b2d1a3a7de4179f816acfec745854e1e4300542)
Required to get either all active groups or only unbounded groups
Unit Tests

[IOPAE-1677] bff get institution groups api

---

.changeset/red-months-sniff.md
apps/backoffice/src/app/api/services/group-unbound/any/__tests__/route.test.ts
apps/backoffice/src/app/api/services/group-unbound/any/route.ts

Added the checkGroupUnboundedServiceExistence api in order to check if there is at least one group unbound service for the given user
[added group unbuond service any api](https://github.com/pagopa/io-services-cms/commit/056eecbdd86f448f2abf4706262b6e1670007433)
[added unit test](https://github.com/pagopa/io-services-cms/commit/823c24a7b8df049ad4f35b1bd6615c8ae5502d8b)
Required to check if the user has at least one  group unbound service
Unit test
Local environment connected to Prod resources

[IOPAE-1678] backoffice group unbound any api

---

.changeset/large-cameras-joke.md
apps/backoffice/src/app/api/subscriptions/__tests__/route.test.ts
apps/backoffice/src/app/api/subscriptions/route.ts
apps/backoffice/src/lib/be/__tests__/authz.test.ts
apps/backoffice/src/lib/be/authz.ts

[added auth control on get subscriptions](https://github.com/pagopa/io-services-cms/commit/0bc028d8e5a243b017a52c23e7bbcf9a192dbb98)
[added and refactor unit test](https://github.com/pagopa/io-services-cms/commit/4900eb031163e71c80adc297a520eb41a3e1c7c5)
[fix auth requirements](https://github.com/pagopa/io-services-cms/pull/1131/commits/84e3e09e854e4f0f13fc70751451980556b37f0e)
[fix unit tests](https://github.com/pagopa/io-services-cms/pull/1131/commits/215879d808351ad472fdbe6feb13d24b5308fd10)
Required to make a check if the query param of the request is MANAGE_GROUP and the user is not an admin and hasn't any group
Unit test

[IOPAE-1679] auth control on get subscriptions

---

.changeset/eighty-trainers-work.md
apps/backoffice/mocks/handlers/backend-handlers.ts
apps/backoffice/public/locales/en/common.json
apps/backoffice/public/locales/it/common.json
apps/backoffice/src/components/dialog-provider/index.tsx
apps/backoffice/src/components/groups/button-associate-group.tsx
apps/backoffice/src/components/groups/index.ts
apps/backoffice/src/pages/groups/associate.tsx
apps/backoffice/src/pages/services/index.tsx

Added `ButtonAssociateGroup` on **Services** page.
**Note 1:** _Follow commits history to better understand developments._
**Note 2:** _Watch videos below to better appreciate developed use cases._
Need to associate one or more services to a group.
**Use Case 1:** happy flow _(Associate page is just a placeholder)_
https://github.com/user-attachments/assets/2fd1cade-19e8-4ed2-bc22-378dee6a0c25
**Use Case 2:** no group unbounded services _(All services are asociated to a group)_
https://github.com/user-attachments/assets/3210027c-f68c-4641-b186-390823b4e5a9

[IOPAE-1363] Added ButtonAssociateGroup on Services page

---

.changeset/rude-colts-drive.md
apps/backoffice/src/lib/be/__tests__/services.test.ts
apps/backoffice/src/lib/be/services/business.ts

[addded service list filter by active groups](https://github.com/pagopa/io-services-cms/commit/b10780651be20b21ef4fda025423df47911f58cf)
[added unit tests](https://github.com/pagopa/io-services-cms/commit/baf7c587efdb96d779c3a777b37ad2e36de59ace)
Required to retrieve only a list of services associated with active groups for an operator
unit test

[IOPAE-1675] backoffice active group filter on service list

---

.changeset/rude-stingrays-perform.md
apps/backoffice/src/app/api/services/__tests__/route.test.ts
apps/backoffice/src/app/api/services/route.ts

[added check on group status on bulkpatch api](https://github.com/pagopa/io-services-cms/commit/a800802d3a0b23bae6ebc79f86b6204f1bdfbd14)
[added unit test](https://github.com/pagopa/io-services-cms/commit/50a2909c7ff86b70d5e35773bb188074f6010592)
the necessity to check if the group passed in the service bulk patch is active.
Unit test

[IOPAE-1815] backoffice bulkpatch check on active group

---

.changeset/silly-houses-applaud.md
apps/backoffice/mocks/data/backend-data.ts
apps/backoffice/public/locales/en/common.json
apps/backoffice/public/locales/it/common.json
apps/backoffice/src/components/api-keys/api-key-tag.tsx
apps/backoffice/src/components/api-keys/api-keys-card/api-keys-card.tsx
apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group-tag.tsx
apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group.tsx
apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-groups.tsx
apps/backoffice/src/components/groups/group-info-tag/group-info-tag.tsx
apps/backoffice/src/components/services/index.ts
apps/backoffice/src/components/services/service-group-tag.tsx
apps/backoffice/src/components/services/service-info.tsx
apps/backoffice/src/pages/services/index.tsx

Added ux/ui for suspended group/apikeys.
In general, all use cases related to the active, suspended and deleted states of an apikey/group have been handled.
_**Note:** Watch videos and screenshots below to better appreciate developments use cases._
Follow commits history to betetr understannd developments.
Need to have different layout and actions for different apikey/group state.
**Overview of API KEY GROUPS card:** 
**ApiKeys Groups section in ApiKeys Page:** 
https://github.com/user-attachments/assets/914c774d-2613-4796-8ce5-c2e23b259dcc
**Group column in Services table:** 
https://github.com/user-attachments/assets/b7ec23a7-3740-4e30-8fe0-f2fb03248b40
**Group info in 
Service Details page:**

[IOPAE-1800] Added ux/ui for suspended group/apikeys

---

.changeset/proud-melons-applaud.md
apps/backoffice/openapi.yaml
apps/backoffice/src/components/api-keys/api-keys-groups/button-generate-api-keys-group.tsx

Added GroupFilterType on checkInstitutionGroupsExistence and set filter=UNBOUNDED on generate ApiKey Group initial check.
When Admin user click on "Generate Group ApiKey" the starting check must control the existence of any active and unbounded group, not only the existence of active groups.

[IOPAE-1852] Added GroupFilterType on checkInstitutionGroupsExistence openapi and set it on generate ApiKey Group initial check

---

.changeset/shiny-lies-tan.md
apps/backoffice/src/lib/be/__tests__/services.test.ts
apps/backoffice/src/lib/be/services/business.ts

[fix group on service list](https://github.com/pagopa/io-services-cms/commit/0aab0dd3ca65ee22d75d4a0ad0c9ab63b20fb9a9)
[fix unit test](https://github.com/pagopa/io-services-cms/commit/7328e28d32a10dd02fae7f0d31d5f445fd84a871)
It was necessary to fix a bug where the service group was not returned when the service list was fetched by an admin or operator without groups.
Unit test

[IOPAE-1845] backoffice fix service list group

---

.changeset/bright-peas-retire.md
apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group.tsx

When user try to expand a single apikey group accordion item, a circular loader is displayed during the loading waiting time.
_**Note:** watch video below to better appreciate development behaviour._
Need to return an UI feedback during loading waiting time.
https://github.com/user-attachments/assets/18ec8ce1-33fd-4929-aa4a-311074a155b9

[IOPAE-1854] Added loader on single apikey group accordion item

---

.changeset/strange-plants-flash.md
apps/backoffice/src/lib/be/__tests__/institutions.test.ts
apps/backoffice/src/lib/be/__tests__/services.test.ts
apps/backoffice/src/lib/be/__tests__/wrappers.test.ts
apps/backoffice/src/lib/be/institutions/business.ts
apps/backoffice/src/lib/be/institutions/selfcare.ts
apps/backoffice/src/lib/be/selfcare-client.ts
apps/backoffice/src/lib/be/services/business.ts
apps/backoffice/src/lib/be/wrappers.ts

[refactor list service with suspended groups](https://github.com/pagopa/io-services-cms/commit/71836f0577f04c27490744dc843ca19b276ba8ab)
[added filter on selfcare client](https://github.com/pagopa/io-services-cms/commit/7274bb1dbd422c10d5e703021fc1ec0220dadb20)
The service list didn't contain the infos about the suspended groups
unit test

[IOPAE-1867] backoffice add suspended group detail on service list

---

.changeset/proud-poets-film.md
apps/backoffice/openapi.yaml
apps/backoffice/src/app/api/services/[serviceId]/__tests__/route.test.ts
apps/io-services-cms-webapp/openapi.yaml
apps/io-services-cms-webapp/src/webservice/controllers/__tests__/patch-service.test.ts
apps/io-services-cms-webapp/src/webservice/controllers/patch-service.ts

[change openapi patch service response status code into 204](https://github.com/pagopa/io-services-cms/commit/7eb6358f4f64ed790544bce6659ad1b589bb24e1)
[implementation change status code on patch service](https://github.com/pagopa/io-services-cms/commit/15ba0bc20a52d5d91cbf6c8c8633e31ac7cf0148)
Unit tests

[IOPAE-1873] add empty response patch service

---

.changeset/happy-onions-clap.md
apps/backoffice/src/app/api/keys/manage/cidrs/__tests__/route.test.ts
apps/backoffice/src/app/api/keys/manage/cidrs/route.ts
apps/backoffice/src/app/api/subscriptions/[subscriptionId]/cidrs/__tests__/route.test.ts
apps/backoffice/src/app/api/subscriptions/[subscriptionId]/cidrs/route.ts

[add auth check on update authorized cidr for admin](https://github.com/pagopa/io-services-cms/commit/440994bb6ecf3ef6f59eb33429d794df95dcd6a3)
The necessity to grant the invocation on update authorized cidrs operations only for the admin
Unit test

[IOPAE-1879] backoffice change auth controls update manage key authorized cidr

---

.changeset/sixty-spies-grab.md
apps/backoffice/src/app/api/keys/manage/[keyType]/__tests__/route.test.ts
apps/backoffice/src/app/api/keys/manage/[keyType]/route.ts
apps/backoffice/src/app/api/subscriptions/[subscriptionId]/keys/[keyType]/__tests__/route.test.ts
apps/backoffice/src/app/api/subscriptions/[subscriptionId]/keys/[keyType]/route.ts

[add auth check on regenerater manage api key for admin](https://github.com/pagopa/io-services-cms/commit/c767f3e926df8e806b11774c11ddcceb83ea640e)
[added feature flag check](https://github.com/pagopa/io-services-cms/pull/1196/commits/191f607531e2132b471af2629fdcdd464e203629)
The necessity to grant the invocation on regenerate manage api keys operations only for the admin
unit test

[IOPAE-1876] backoffice change auth controls regenerate keys

---

.changeset/poor-spoons-cover.md
apps/backoffice/src/components/__tests__/access-control.test.tsx
apps/backoffice/src/components/access-control/index.tsx
apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group.tsx
apps/backoffice/src/components/api-keys/api-single-key.tsx
apps/backoffice/src/pages/keys/index.tsx

With this PR  a user control has been added, in this case `admin`, to enable the _**Key Rotation**_ and **_CIDRs update_** features.
**Note:** this restriction is related to the activation of the Group ApiKeys feature flag (`GROUP_APIKEY_ENABLED`).
Need to check admin role to enable some critical actions.

[IOPAE-1877] Added admin control to enable keys rotate and cidrs update actions

---

.changeset/yellow-turtles-sniff.md
apps/backoffice/src/components/api-keys/api-keys-couple.tsx
apps/backoffice/src/components/api-keys/api-single-key.tsx

Added control to allow USE apikey rotation for all user types.
Both admin and operator role must have USE apikey rotation capability.

[IOPAE-1886] Added control to allow USE apikey rotation for all user types

---

.changeset/five-dogs-joke.md
apps/backoffice/src/components/services/service-create-update/service-create-update.tsx

**Fix:** Prevent form fields from resetting on tab focus change due to `next-auth` session refetch.
**Details:**
Refactored the form initialization to memoize _defaultValues_ using `useMemo`, ensuring that `react-hook-form` does not reset field values when the component re-renders _(e.g., during automatic session refresh triggered by next-auth when switching browser tabs)._

Fix: [IOPAE-1971] Fix create service form reset

---

.changeset/tough-donuts-cry.md
apps/backoffice/src/app/api/services/[serviceId]/__tests__/route.test.ts
apps/backoffice/src/app/api/services/[serviceId]/route.ts
apps/backoffice/src/app/api/services/__tests__/route.test.ts
apps/backoffice/src/app/api/services/route.ts
apps/backoffice/src/utils/organization-name-utils.ts
apps/backoffice/src/utils/rename-pagopa-organization.ts

[fix organization name override with temporary workaround](https://github.com/pagopa/io-services-cms/commit/4579775557a4478c271dbd25678adf8f7b1585b2)
When a service from the pagopa organization is updated or created the organazation name needs to be remapped
Local environment connected to prod resources and unit tests

[IOPAE-2004] backoffice workaround override io organization name

---

.changeset/hip-cups-cry.md
apps/backoffice/public/locales/en/common.json
apps/backoffice/public/locales/it/common.json
apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group-tag.tsx
apps/backoffice/src/components/api-keys/api-keys-groups/api-keys-group.tsx
apps/backoffice/src/components/services/service-group-tag.tsx

Added suspended group name interpolation in tooltips for `ServiceGroupTag` and `ApiKeysGroupTag`.
Group name interpolation in tooltips: Added tooltip logic with group name interpolation in **ServiceGroupTag** and **ApiKeysGroupTag**, using the `{{name}}` syntax directly in the translation JSON files.
Need to display the name of the suspended group where this is wrapped with text ellipsis.
tested in local environment with mock data
https://github.com/user-attachments/assets/c7234033-5ed2-4707-9177-e4b40dd81f46

[IOPAE-1899] Added suspended group name interpolation in tooltips for ServiceGroupTag and ApiKeysGroupTag

---

.changeset/pink-carpets-refuse.md
apps/backoffice/src/components/headers/header.tsx

Fix the switch to Reserved Area, forcing BackOffice IO logout.
This PR addresses a bug that occurred when a user switched from the BackOffice IO to the Reserved Area, changed their institution, and then returned to the BackOffice.
Previously, this sequence of actions could lead to the incorrect institution being displayed.
This fix resolves the issue by forcing a BackOffice IO logout whenever a user switches to the Reserved Area, ensuring that the correct entity is always shown upon their return.
Closes IOPAE-2155 Resolves IOPAE-2156

Fix switch to Reserved Area forcing BackOffice IO logout
